### ISSUE TITLE
How to remove or hide built-in map objects, such as bus stops and businesses?

### ISSUE THREAD

**Issue by assansh** [yandex/mapkit-android-demo#101]
I'd like to replace the default markers for some of the objects, is there a way to do it?

These bus stops, for example:

![bus-stops](https://user-images.githubusercontent.com/4612367/60321836-b78f9180-999f-11e9-9134-edcccf0bf3db.jpg)

**Comment by nassa** [comment]
Since there's no reply, I decided to just draw a larger icon on top of the built-in one. But it would be nice to have an option to hide the built-in icons in order to draw pin-style placemarks for example.
