### ISSUE TITLE
Невозможно использовать вместе с AndroidX

### ISSUE THREAD

**Issue by alexkashapov** [yandex/mapkit-android-demo#102]
Нельзя исползовать на проектах на AndroidX.

**Comment by iFr0z** [comment]
Хм, спокойно использую вместе с androidx, ktx, kotlin synthetic и прочей нечестью.

**Comment by dsvoronin** [comment]
enableJetifier в больших проектах здорово замедляет сборку, поэтому нужен и вариант собранный с androidX

**Comment by iFr0z** [comment]
@dsvoronin это само собой разумеется, и я думаю ребята занимаются над этим. Но речь не шла о больших проектах, а именно про здесь и сейчас :)
