### ISSUE TITLE
Данные из BusinessImagesObjectMetadata

### ISSUE THREAD

**Issue by CeH9** [yandex/mapkit-android-demo#108]
Как их обрабатывать? Где брать ид для вставки в шаблон? Есть ли описание **BusinessImagesObjectMetadata** в документации? 

![image](https://user-images.githubusercontent.com/7687412/60825368-36f93e00-a1b4-11e9-8519-66114e8844a5.png)

`https://avatars.mds.yandex.net/get-altay/223006/2a0000015b19222d131711047d866611eaf2/%s`

**Comment by CeH9** [comment]
Вообще цель этого всего - отобразить фотку, ассоциируемую с объектом(SearchType.BIZ).

**Comment by maklas** [comment]
Подставляй вместо %s:

"S" - маленькая фотка
"h168" - фотка размером X*168
"M" - средняя
"L" - Большая
"orig" - Оригинал

Возможно есть больше вариантов, но этого достаточно думаю
