### ISSUE TITLE
MapView overlapping in Fragments

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#109]
MapView из одного фрагмента наслаивается на другой MapView из другого фрагмента, все остальные вью работают корректно, трансакция фрагментов происходит через метод add.  Как поправить такое поведение, необходимо использовать add вместо replace, так как есть необходимость возвращаться на предыдущий фрагмент.

**Comment by Ramozjikevic** [comment]
<MapView app:movable="true"/> пробовали?

**Comment by Ramozjikevic** [comment]
app:movable="true" пробовали?

**Comment by MaratBR** [comment]
Для тех, кому также как и мне лень лезть в документацию: `app:movable="true"` нужно установить для всех карт, которые могут пересекать друг-друга.


[Ссылка на документацию](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/mapview/MapView-docpage/)
