### ISSUE TITLE
Placemark tap listener issue

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#11]
<img width="702" alt="screen shot 2018-05-09 at 17 24 00" src="https://user-images.githubusercontent.com/25398143/39812399-6017fcd6-53ae-11e8-9a97-b733d4cb957c.png">

I've written code above, where added placemarks, add then tapped on it. In logs I've got Point(43.22710205032152 76.95960232840031), but I've put latitude=43.228027, longitude=76.959441, why it's happened. Thank you

**Comment by eberkovich** [comment]
point argument contains coordinates of tap, that is why it is not equal to coordinates of placemark.
If you need to get coordinates of placemark, you can cast mapObject to PlacemarkMapObject type and call geometry() method.

**Comment by ToleubekRauan** [comment]
@eberkovich Thank you, friend.

**Comment by Ulugbe7** [comment]
how to create location picker with yandex mapkit
