### ISSUE TITLE
Работа с метками

### ISSUE THREAD

**Issue by sviter-pro** [yandex/mapkit-android-demo#110]
создаю метку! надо что бы на ней была информация обьекта!!! mapView.getMap().addTapListener(new GeoObjectTapListener() {
            public boolean onObjectTap(GeoObjectTapEvent geoObjectTapEvent) {
                GeoObject obj = geoObjectTapEvent.getGeoObject();
                obj.getDescriptionText();

как обработать: obj.getDescriptionText(); ???
 ато приходит всегда "obj: GeoObject@5544"

**Comment by nassa** [comment]
Можно использовать `getUserData()` & `setUserData(object)` класса PlacemarkMapObject:

```java
MapObjectCollection pointCollection = map.getMapObjects().addCollection();
pointCollection.addTapListener(this);
PlacemarkMapObject placemark = pointCollection.addPlacemark(...);
placemark.setUserData(data)

...

@Override
public boolean onMapObjectTap(MapObject mapObject, Point point) {
    WhateverType data = (WhateverType) mapObject.getUserData();
}
```

**Comment by eberkovich** [comment]
Для обработки нажатий на пользовательские объекты нужно использовать MapObjectTapListener, который устанавливается с помощью MapObject.addTapListener.

GeoObjectTapListener нужен для обработки нажатий на объекты в слоях карты.
Кроме того, пожалуйста обратите внимание на то, что mapkit сохраняет слабые ссылки на листнеров, по этому их необходимо сохранять на стороне приложения.

**Comment by sviter-pro** [comment]
можно ли вообще сделать обработку нажатий только остановок в определенном куске страны, города или поселка?

**Comment by eberkovich** [comment]
- В данный момент способа определить, что объект является остановкой нет. 
Эта возможность появится в одном из следующих релизов.

- По поводу ограничения области для обработки нажатий. Можно использовать GeoObject.getBoundingBox() и на стороне приложения проверять попадание в заданную область.

**Comment by sviter-pro** [comment]
не получается!
делаю так:
`
implements MapObjectTapListener в AppCompatActivity

 private Object data;

MapObjectCollection pointCollection = mapView.getMap().getMapObjects().addCollection();
        pointCollection.addTapListener(this);
        PlacemarkMapObject placemark = pointCollection.addPlacemark(my_point, ImageProvider.fromResource(this, R.drawable.search_layer_pin_icon_default));
        placemark.setUserData(data);

        placemark.addTapListener(new MapObjectTapListener() {
            @Override
            public boolean onMapObjectTap(MapObject mapObject, Point point) {
                mapObject.getUserData();
                return true;
            }});`
 ругается вот тут: PlacemarkMapObject placemark = pointCollection.addPlacemark(my_point, ImageProvider.fromResource(this, R.drawable.search_layer_pin_icon_default)); 
на ImageProvider.fromResource(this, R.drawable.search_layer_pin_icon_default)

**Comment by eberkovich** [comment]
> Кроме того, пожалуйста обратите внимание на то, что mapkit сохраняет слабые ссылки на листнеров, по этому их необходимо сохранять на стороне приложения.

**Comment by eberkovich** [comment]
На всякий случай, у Point первая координата это широта.

**Comment by sviter-pro** [comment]
ну поменял я наоборот! но храбрости мне это не придало! все ровно ничего не происходит! в чем может быть дело? карта запускается, гео.локация работает, значит и остальное должно!

**Comment by eberkovich** [comment]
-  что значит ничего не происходит: иконка не показывается или не срабатывают нажатия?
-  если речь про то,  что не видно иконку, ее не видно даже если перейти на масштаб на котором виден весь мир?

**Comment by sviter-pro** [comment]
дико извиняюсь! все заработало! мой касяк был в том, что я все делал тут:
placemark.addTapListener(new MapObjectTapListener() {
            @Override
            public boolean onMapObjectTap(MapObject mapObject, Point point) {
                mapObject.getUserData();
                return true;
            }});
а надо то в implements MapObjectTapListener......

**Comment by sviter-pro** [comment]
это пол беды!!! подскажите как вывести текст с обьекта на котором стоит placemark  ??? ничего не понятно....

**Comment by MrWhiteShapi** [comment]
У меня такая же проблема. Листенер нажатия на обьект на работает, однако сам листенер орпеделен как указано в примере в github  и  там еще указанно что такой метод создания листенера - создает сильную ссылку

` private MapObjectTapListener mapObjectTapListener = new MapObjectTapListener() {
        @Override
        public boolean onMapObjectTap(@NonNull MapObject mapObject, @NonNull Point point) {
            Build build = (Build) mapObject.getUserData();
            if (build.getOwner() == "empty"){
                FreeDialog freeDialog = new FreeDialog();
                freeDialog.showDialog(getContext(), build);
            }
            else {

            }

            return true;
        }
    };`
