### ISSUE TITLE
При расширении MapView метод onTouchEvent не вызывыется

### ISSUE THREAD

**Issue by KonstantinProgram** [yandex/mapkit-android-demo#111]
Задача создать пользовательское рисование на карте с помощью canvas и передача точек в Polygon. При расширении MapView не вызывается  onTouchEvent. Рассмотрите пожалуйста мой вопрос. Спасибо!

**Comment by eberkovich** [comment]
Для того, чтобы карта не перехватывала TouchEvent можно положить прозрачную view поверх карты.

**Comment by KonstantinProgram** [comment]
каким образом тогда перехватывать координаты latitude и longitude где было движение по карте?

**Comment by eberkovich** [comment]
для этого можно использовать MapWindow.screenToWorld().

**Comment by KonstantinProgram** [comment]
Спасибо!
