### ISSUE TITLE
как геокодингу внести координаты?

### ISSUE THREAD

**Issue by sviter-pro** [yandex/mapkit-android-demo#112]
пытаюсь получить адрес по указанным координатам? как это лучше сделать?

я делаю так:
```
    Runnable runnable = new Runnable() {
        public void run() {
searchManager.submit(resultLocation, 18, SearchOptions().setSearchTypes(
            SearchType.GEO.value |
                    SearchType.BIZ.value |
                    SearchType.TRANSIT.value), this);
        }
    };
```

но мне бьет ошибку:
java.lang.NullPointerException: Attempt to invoke interface method 'com.yandex.mapkit.search.Session com.yandex.mapkit.search.SearchManager.submit(com.yandex.mapkit.geometry.Point, java.lang.Integer, com.yandex.mapkit.search.SearchOptions, com.yandex.mapkit.search.Session$SearchListener)' on a null object reference

**Comment by elricbk** [comment]
Замечания не относятся конкретно к ошибке, но без них всё равно не заработает:
* `Runnable`, по-моему, не нужен, вызывать методы MapKit нужно на UI-потоке
* Обратный поиск [требует][1] на вход только один `SearchType`
* Метод `submit` возвращает сессию, которую [нужно сохранять][2]

[1]: https://habr.com/ru/company/yandex/blog/428564/#obratnyy-poisk
[2]: https://habr.com/ru/company/yandex/blog/428564/#kak-ustroen-zapros

**Comment by sviter-pro** [comment]
- Метод submit возвращает сессию, которую нужно сохранять! 
это как? подробнее расскажите? типа так:
searchManager = SearchFactory.getInstance().createSearchManager(
    SearchManagerType.ONLINE)

**Comment by elricbk** [comment]
Это `SearchManager` сохраняется. Сессию тоже нужно сохранять:

```
session = searchManager.submit(...);
```

где `session` – это поле класса.

**Comment by sviter-pro** [comment]
хорошо! спасибо! а почему ругается на это:
searchManager = SearchFactory.getInstance().createSearchManager(
SearchManagerType.ONLINE)

вот такой ошибкой:

    java.lang.UnsatisfiedLinkError: No implementation found for com.yandex.mapkit.search.Search com.yandex.mapkit.search.SearchFactory.getInstance() (tried Java_com_yandex_mapkit_search_SearchFactory_getInstance and Java_com_yandex_mapkit_search_SearchFactory_getInstance__)
        at com.yandex.mapkit.search.SearchFactory.getInstance(Native Method)

**Comment by sviter-pro** [comment]
так а как достать информацию то?

ArrayList<BusinessFilter>list = new ArrayList<BusinessFilter>(); создал
session.setFilters(list ); сделал
в list приходит 0

**Comment by elricbk** [comment]
В примере кода обратный поиск делается по топонимам (`SearchType.GEO`), а метаданные извлекаются для организации (`.getItem(BusinessObjectMetadata.class)`) и почему-то для транспорта, что совсем смысла для обратного поиска не имеет.
