### ISSUE TITLE
Можно ли фокусировать карту не в центре но без UserLocationLayer?

### ISSUE THREAD

**Issue by SpeedFire0** [yandex/mapkit-android-demo#117]
Хочется смещения центра карты (как при режиме Coarse) но без UserLocationLayer
`userLocationLayer.setAnchor(
      new PointF((float)(mapviewYandex.getWidth() * 0.5), (float)(mapviewYandex.getHeight() * 0.83)),
      new PointF((float)(mapviewYandex.getWidth() * 0.5), (float)(mapviewYandex.getHeight() * 0.83)));
`

И в GoogleMap и в MapBox это решалось просто:
mapView.setPadding(0,300,0,0);
Но в отличие от этих двух - в мапките данный отступ сверху остается пустым и не заполняется отрисовываемой картой. 

Есть ли варианты?

**Comment by eberkovich** [comment]
Да, для этого есть метод MapWindow.setFocusRect.

```
    /**
     * When using controls that overlay the map view, calculating the proper
     * camera position can be tricky. This method simplifies the task by
     * defining the area of interest (the focus rectangle) inside the view.
     * This area serves as a reference for all subsequent camera movements.
     *
     * For example, when using a semi-transparent control that overlays the
     * top half of the map view, define the focus rectangle as the lower
     * half of the view to ensure that all camera movements will have the
     * center of the lower half as their target.
     *
     * On iOS, if you change the focus rectangle in the
     * viewDidLayoutSubviews callback, it's recommended to call
     * MapView.layoutIfNeeded just before that action.
     *
     * Optional property, can be null.
     */
    @Nullable
    public ScreenRect getFocusRect();
    public void setFocusRect(@Nullable ScreenRect focusRect);
```

**Comment by SpeedFire0** [comment]
Спасибо. Есть ли какой-нибудь пример реализации данной функции на андроид?

Пытался применить ее следующим образом и не увидел никаких изменений. Камера продолжает фокусировать в центр карты при любом offsetY:
   int left = 0;
      int top = 0;
      int right = 500;
      int bottom = 500;
      int offsetY = 300;
      Log.d(LOG_TAG, "relayoutMapView before left, top, right, bottom = " + left + ", " + top + ", " + right + ", " + bottom);
      top = top + offsetY;
      Log.d(LOG_TAG, "relayoutMapView after left, top, right, bottom = " + left + ", " + top + ", " + right + ", " + bottom);
      mapviewYandex.getMapWindow().setFocusRect(new ScreenRect(new ScreenPoint(left,top), new ScreenPoint(right, bottom)));

---
getFocusRect() до применения этого куска кода всегда возвращал null. После применения возвращает объект. Поэтому функция вроде как применяется, но результаты не видны. Кастомные слои никакие не использую применяю напрямую к MapWindow().

Где может быть ошибка?

**Comment by eberkovich** [comment]
Вызов

**Comment by SpeedFire0** [comment]
Да, понятное дело. После применения setFocusRect я вызываю перемещение камеры (mapviewYandex.getMap().move) на позицию маркера, но маркер, к сожалению, показывается ровно по центру экрана, а не ниже.

**Comment by eberkovich** [comment]
На всякий случай перепроверил,  сделал такой же тест: работает,  как ожидается.

**Comment by SpeedFire0** [comment]
Можете полный код скинуть? Может увижу ошибку. Мапкит версии 3.4.0 для андроид?

**Comment by eberkovich** [comment]
Полный к сожалению не могу, проверял в рамках внутреннего тестового приложения.
```
onCreate() {
   center = mapview.getMap().getMapObjects().addPlacemark(new Point(65, 35));
}

onClick() {
    mapview.getMap().move(new CameraPosition(center.getGeometry(), 15.f, 0.f, 0.f));
    mapview.setFocusRect(new ScreenRect(new ScreenPoint(0, 0), new ScreenPoint(500, 500)));
}
```

Версия у меня немного отличается от 3.4.0, но никаких изменений связанных с работой камеры после 3.4.0 не производилось.
Не могли бы Вы выложить минимальный пример?

**Comment by SpeedFire0** [comment]
Спасибо большое!
Теперь повторил и все заработало.

Похоже что моя основная ошибка была в следующем:
Карта занимает у меня только часть экрана. Я полагал что для setFocusRect необходимо указывать координаты границ физического экрана. Оказалось, что нужно указывать относительные (!) координаты, где (0,0) - это левый верхний угол карты, а не левый верхний угол физического экрана. Из документации было не очень понятно. (вообще мне кажется что в такой ситуации было бы логичнее задавать координаты как в setAnchor от 0 до 1f по горизонтали и вертикали).
