### ISSUE TITLE
Инициализация SearchFactory вне UI потока

### ISSUE THREAD

**Issue by svbutko** [yandex/mapkit-android-demo#121]
Возможно ли произвести инициализацию SearchFactory не UI потока?
Например, мне требуется делать запрос на получение подсказок для текстового поля, но при этом карты у меня может не быть на экране, подскажите что делать в этом случае?
Возможно есть статические вызовы API для таких целей?

**Comment by elricbk** [comment]
Все методы MapKit должны вызываться из UI-потока. Но `SearchManager` никак не связан с картой, поэтому его вполне можно использовать для получения подсказок для текстового поля.
