### ISSUE TITLE
setMapLoadedListener вызывается не всегда

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#122]
Метод из MapView.Map setMapLoadedListener вызывается через раз, причем, карта визуально подгружена.

**Comment by eberkovich** [comment]
У этого могут быть следующие причины:
- Визуально сложно понять, полностью ли загрузилась карта, например могли загрузиться не все 3d модели, или могли не загрузиться какие-то подписи и иконки в тайлах частично вылезающих за границы экрана. Кроме того, многие тайлы содержат информацию для нескольких масштабов и может получиться так, что текущий масштаб загрузился полностью (он загружается в первую очередь), а остальные нет.
- MapLoadedListener сбрасывается после каждого вызова,  возможно он не был выставлен заново.
- на стороне приложения не сохранен листнер.

**Comment by ToleubekRauan** [comment]
@eberkovich не могли бы подробней про 3 пункт. Сразу задам вопрос, правда не по этой теме. При добавлении PlaceMark–ов карта сильно притормаживает, элементов более 90.
ImageProvider использую один. 
`
val markerImageProvider = getMarkerByResource(it, R.drawable.ic_marker)
            list.forEach { item ->
                val marker = mapView?.map?.mapObjects?.addPlacemark(
                    Point(item.location?.latitude ?: 0.0, item.location?.longitude ?: 0.0),
                    markerImageProvider
                )
             }
`

**Comment by eberkovich** [comment]
- по поводу listener: мапкит сохраняет слабую ссылку на листнер, по этому если не сохранять его на стороне приложения он будет умирать в произвольные моменты времени.

- addPlacemark: 
Попробуйте воспользоваться 
```
/**
     * Creates new placemarks and adds them to the current collection.
     * Relevant for Android: this method provides better performance for
     * adding a large number of placemarks than multiple calls of
     * addPlacemark.
     */
    @NonNull
    public List<PlacemarkMapObject> addPlacemarks(
        @NonNull List<Point> points,
        @NonNull ImageProvider image,
        @NonNull IconStyle style);
```
