### ISSUE TITLE
Внутри полигона показать кластеры

### ISSUE THREAD

**Issue by kostyanchikoff** [yandex/mapkit-android-demo#124]
Если ли в SDK метод который фильтрует полученные Point-ы  при выделении области с помощью Polygon? Пользователь выделил область, а внутри выделенной области появились Point-ы. Спасибо!

**Comment by eberkovich** [comment]
Если, я правильно понял вопрос, то требуется функция определяющая попадание точки в область. Такой функции в api сейчас нет и пока нет планов по добавлению.

**Comment by KonstantinProgram** [comment]
У google maps есть метод google.maps.geometry.poly containsLocation(), может у вас есть что нибудь подобное?

**Comment by ilya842** [comment]
@eberkovich Подскажите, пожалуйста, функция по определению попадания точки в область все еще отсутствует в SDK?

**Comment by eberkovich** [comment]
да, тут ничего не изменилось.
