### ISSUE TITLE
Не отображается карта при возврате из бэкграунда

### ISSUE THREAD

**Issue by alaytsev** [yandex/mapkit-android-demo#126]
Здравствуйте. У нас имеется фрагмент с MapView и другими вьюхами. Если в этом фрагменте полностью перекрыть MapView другой вьюхой, свернуть приложение, вернуться в него и сделать так, чтобы карта стала видна, то вместо карты видим серую вьюху. Если пересоздать этот фрагмент, то карта снова нормально отображается. Проблема повторяется и на последней версии MapKit.

> W/yandex.maps: yandex::maps::mapkit::textures::Atlas::addTexture: Atlas: LayersAtlas. Page: 7 created. That could seriously decrease rendering speed
W/View: requestLayout() improperly called by android.view.View{caa2ebb V.ED..... ......I. 0,15-324,339} during layout: running second layout pass
E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x895dc008) failed (0xffffffed) (already connected to another API?)
E/libEGL: eglCreateWindowSurface:693 error 3003 (EGL_BAD_ALLOC)
W/GLSurfaceView: Warning, !readyToDraw() but waiting for draw finished! Early reporting draw finished.
V/FA: Inactivity, disconnecting from the service
E/yandex.maps: decltype: Access denied.
E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x825fd808) failed (0xffffffed) (already connected to another API?)
E/libEGL: eglCreateWindowSurface:693 error 3003 (EGL_BAD_ALLOC)

>

**Comment by eberkovich** [comment]
Здравствуйте,

Зовете ли Вы MapView.onStart/onStop из соответствующих методов фрагмента?

**Comment by alaytsev** [comment]
> Здравствуйте,
> 
> Зовете ли Вы MapView.onStart/onStop из соответствующих методов фрагмента?

Да, все как в гайдах, вызываю onStart/onStop у MapKitFactory и MapView.

**Comment by eberkovich** [comment]
Стоит проверить не происходит ли утечки фрагмента/MapView.

**Comment by alaytsev** [comment]
> Стоит проверить не происходит ли утечки фрагмента/MapView.

LeakCanary не находит утечек в этом фрагменте, по профайлеру тоже ничего подозрительного нет.

**Comment by eberkovich** [comment]
Не могли бы Вы сделать минимальный пример?
