### ISSUE TITLE
Zoom to span 

### ISSUE THREAD

**Issue by j7arsen** [yandex/mapkit-android-demo#13]
How make zoom to span?

**Comment by vbazhenov** [comment]
You can use [cameraPosition](https://tech.yandex.ru/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_cameraPosition__BoundingBox) method to convert arbitrary bounding box to camera position that can be passed to `map.move` method.
