### ISSUE TITLE
Очень сырая документация

### ISSUE THREAD

**Issue by mancj** [yandex/mapkit-android-demo#130]
Документация к классам очень сырая. Вот несколько примеров
- **Layer**: Interface for working with the layer.
- **TileId**: The ID of a tile on the map.
- **Version**: Dot-separated version string.
и т.п.

То что **tile id** это **the id of a tile** понятно и без документации. Но что это такое и для чего оно нужно – этой информации очень не хватает.
За что ответает класс **Version** тоже абсолютно непонятно непросвещенному пользователю. **Версия чего**?

**Comment by Erdemtsynduev** [comment]
@mancj Прошло полгода и ничего не изменилось))

**Comment by AlexSuvorov2k** [comment]
@Erdemtsynduev прошло 2 с половиной года и ничего не изменилось)

**Comment by YandexMapKit** [comment]
TileId: в целом TileId [описан](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/TileId.html), состоит из трех координат: x, y, z:

x - координата по горизонтали;
y - по вертикали
z - масштаб

На каждом масштабе тайлы делятся пополам по горизонтали и вертикали.

На 0 масштабе - есть всего один тайл с координатами 0, 0, 0.
На первом масштабе четыре тайла:
0, 0, 1 | 1, 0, 1

0, 1, 1 | 1, 1, 1

И так далее.

Version: версия применяется в слоях, где данные могут меняться со временем.
В случае если версия изменилась, мапкит запросит для слоя новые тайлы, даже если у него уже есть закешированные тайлы покрывающие видимую область карты. В случае если пользовательскому слою версионирование не нужно, можно передавать "0" в качестве версии.
Изменение версии слоя происходит при вызове Layer.invalidate(Version).

Документация будет пополняться в рамках улучшения API.
