### ISSUE TITLE
Не отображается logo на релизной сборке.

### ISSUE THREAD

**Issue by Ramozjikevic** [yandex/mapkit-android-demo#132]
Пропадает logo yandex когда собираю религиозную версию, во всех остальных случаях все работает.

**Comment by Ramozjikevic** [comment]
Разобравшись я попробую описать более подробно свою проблему. Приложение которое я использую состоит из нескольких модулей, и карты находятся в отдельном модуле. В главном gradle у меня написаны следующие строчки 
    buildTypes {
        getByName("release") {
            isShrinkResources = true
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
        }
    }
И именно из-за строчки isShrinkResources = true у меня не отображается логотип на картах, я пробовал писать в proguard множество все различных правил.

-keep class ru.yandex**
-keep class com.yandex** 
-keep class ru.yandex.** { *; }
-keep class com.yandex.** { *; }

пакет с моим модулем
-keep com.feature.map** { *; }
-keep com.feature.map**

Ничего не помогает, кроме как установить   isShrinkResources = false, но как мне кажется это не решение проблемы

**Comment by september669** [comment]
Вот эти ресурсы необходимы для логотипа
```
R.drawable.yandex_logo_ru
R.drawable.yandex_logo_ru_white
R.drawable.yandex_logo_en
R.drawable.yandex_logo_en_white
```

**Comment by archiecrown** [comment]
А есть уже решение проблемы?

**Comment by iFr0z** [comment]
Актуалочка до сих пор?! Я хочу релиз под Android 11, А логотипа нет... Если я релизну без логотипа на карте, меня не накажут?)

**Comment by Ramozjikevic** [comment]
> Актуалочка до сих пор?! Я хочу релиз под Android 11, А логотипа нет... Если я релизну без логотипа на карте, меня не накажут?)

Если релизнишь без логотипа думаю накажут, это их условия использование карты. Для меня решением было это обращаться к ресурсам на прямую, где небуть в программе, тогда proguard не вырежет. Вот пример, того, что я указал: 

ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_en)
ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_en_white)
ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_ru)
ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_ru_white) 

Возможно не самое лучшее решение, но перепробовав многое, только это мне помогло.

**Comment by westracer** [comment]
> ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_en)
> ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_en_white)
> ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_ru)
> ContextCompat.getDrawable(requireContext(), R.drawable.yandex_logo_ru_white)
> 
> Возможно, не самое лучшее решение, но перепробовав многое, только это мне помогло.

Можно создать xml файл и указать ресурсы в tools:keep атрибуте:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@drawable/yandex_logo*" />
```

**Comment by YandexMapKit** [comment]
Исправление данной ситуации ожидается в версии 4.3.0.
