### ISSUE TITLE
ErrorBinding или CacheUnavailableError при использовании searchManager.submit и searchManager.suggest

### ISSUE THREAD

**Issue by nk2IsHere** [yandex/mapkit-android-demo#133]
в manifest'e есть android:usesCleartextTraffic="true"
ключ от api действителен
интернет есть

**Comment by elricbk** [comment]
В случае ошибки поиска ещё обычно что-то в логах должно быть по этому поводу. Есть там что-нибудь?

**Comment by mkRustam** [comment]
@nk2IsHere 
Появилась какая-нибудь информация как решить эту проблему?
