### ISSUE TITLE
Не отображается карта в примерах

### ISSUE THREAD

**Issue by vkotovv** [yandex/mapkit-android-demo#134]
Склонировал пример, ревизия https://github.com/yandex/mapkit-android-demo/commit/0d493e2470e4793570aff1324ab15ccbaccb008c

Заменил на 2 экранах ключ API на только что полученный мной.

Экран Map:
- карта не отображается, белый фон с сеткой

Экран Search:
- карта не отображается
- при поиске возникает Unknown Error, в дебаггере увидел что это ErrorBinding.

В logcat никаких подсказок нет.

Как мне попробовать примеры? Мне нужно оценить, будем ли мы интегрировать mapkit.

**Comment by eaniconer** [comment]
Добрый день, 

> Заменил на 2 экранах ключ API на только что полученный мной.

Попробовал воспроизвести ситуации. Тоже использовал только что созданный ключ и получил те же эффекты. Через некоторое время все заработало, проверьте еще раз.

**Comment by vkotovv** [comment]
@eaniconer Спасибо, действительно заработало спустя какое-то время. В первые полчаса после получения ключа не работало.

Думаю, стоит как-то исправить это или хотя бы отразить в документации.
