### ISSUE TITLE
Callback при перемещении карты

### ISSUE THREAD

**Issue by kumold** [yandex/mapkit-android-demo#137]
Здравствуйте. Как можно узнать что карту двинули (драгнули)? В версии 2.* делали с помощью 
`DragAndDropOverlay`, а в  новой альтернативы не могу найти.

**Comment by eberkovich** [comment]
Здравствуйте,

Для этого нужно воспользоваться  методом [Map.addCameraListener](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_addCameraListener___NonNullCameraListener).

Пожалуйста обратите внимание: ссылка на листнер должна быть сохранена на стороне приложения.
