### ISSUE TITLE
Mapkit крашится во время инициализации. ClassNotFoundException на android API 21 

### ISSUE THREAD

**Issue by afborodin** [yandex/mapkit-android-demo#139]
При инициализации мапкита приложение крашится с ошибкой

`Caused by java.lang.ClassNotFoundException
Didn't find class "com.yandex.runtime.device.internal.DeviceInfo" on path: DexPathList[[zip file "/data/app/com.google.android.webview-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-2/lib/arm, /vendor/lib, /system/lib]]`

Фикс из https://github.com/yandex/mapkit-android-demo/issues/56 не помогает

**Comment by muratbalcitr1** [comment]
you should do minimum sdk 21

**Comment by bagza** [comment]
На какой версии mapKit? 3.4.0? 3.3.1?

**Comment by afborodin** [comment]
3.3.1

**Comment by bagza** [comment]
на 3.4.0 не воспроизводилось, но там други баги, не лучше. #138 и связанные
