### ISSUE TITLE
Не всегда отображается pin который я задал

### ISSUE THREAD

**Issue by dgumarov** [yandex/mapkit-android-demo#140]
При отображении карты в методах использую UserLocationObjectListener
Но при этом мой пин отображается не всегда.
Из 10 открытий экрана с картой может 2-3 раза отображается нормально, а в остальных случаях отображается желтый треугольник.
Версия 3.3.1

`
override fun onObjectAdded(userLocationView: UserLocationView) {        
        applyLocationPinIcon(userLocationView)
    }

    override fun onObjectUpdated(userLocationView: UserLocationView, event: ObjectEvent) {       

        when (event) {
            is UserLocationIconChanged,
            is UserLocationAnchorChanged -> {
                applyLocationPinIcon(userLocationView)
            }
        }
    }`

`
private var iconStyle1 = IconStyle().apply {
        anchor = PointF(0.5f, 0.5f)
        scale = 1f
    }

    private var iconStyle2 = IconStyle().apply {
        anchor = PointF(0.5f, 1f)
        scale = 1f
    }

    private fun applyLocationPinIcon(userLocationView: UserLocationView) {
        userLocationView.pin.useCompositeIcon().apply {
            setIcon("circlePin",
                userEllipseProvider,
                iconStyle1)
            setIcon("pin",
                userPinProvider,
                iconStyle2)
        }

        userLocationView.accuracyCircle.geometry = Circle(userLocationView.accuracyCircle.geometry.center, RADIUS_CIRCLE_METERS)
        userLocationView.accuracyCircle.fillColor = ContextCompat.getColor(context, R.color._80e5f1ff)
    }`

**Comment by eberkovich** [comment]
Сохраняется ли UserLocationObjectListener на стороне приложения?
Mapkit сохраняет все листнеры по слабой ссылке.

**Comment by dgumarov** [comment]
> Сохраняется ли UserLocationObjectListener на стороне приложения?
> Mapkit сохраняет все листнеры по слабой ссылке.

Да сохраняется он лежит в объекте, который связан с жизненным циклом активности.
В любом случае, если бы он не сохранялся, то после второго открытия всегда бы был желтый треугольник. Самая сложность в том, что то нрмально отрабатывает, то нет. UserLocationObjectListener при этом не пересоздается он всегда один и тот же.

**Comment by eberkovich** [comment]
а если попробовать для теста безусловно заменять иконку в onObjectUpdated?

**Comment by dgumarov** [comment]
> а если попробовать для теста безусловно заменять иконку в onObjectUpdated?

это ничего не дает, имеется ввиду перенести код из функции applyLocationPinIcon в onObjectUpdated?

**Comment by eberkovich** [comment]
> перенести код из функции applyLocationPinIcon в onObjectUpdated
да

Странно, сможете сделать минимальный пример?

**Comment by dgumarov** [comment]
> > перенести код из функции applyLocationPinIcon в onObjectUpdated
> > да, ну точнее не перенести, а звать и там и там.
> 
> Странно, сможете сделать минимальный пример?

Я решил проблему. Суть в том, что координаты постоянно обновляются и в момент открытия карты происходит смещение указателя. А при смещении используется уже не pin, а arrow.
Соответственно надо в метод applyLocationPinIcon добавить еще 

`userLocationView.arrow.setIcon(...)`

Вопрос теперь такой: стоит ли вызывать этот метод каждый раз при обновлении? Может можно это сделать 1 раз иначе, мне кажется, это не супер производительно.
