### ISSUE TITLE
Отображение меток с произвольными иконками

### ISSUE THREAD

**Issue by pdapnz** [yandex/mapkit-android-demo#141]
Пользуемся [старым MapKitом](https://github.com/yandexmobile/yandexmapkit-android) пока, но хотели бы перейти на новый. Очень смущает вот это из [FAQ](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/faq-docpage/).

> **Можно ли использовать произвольный объект в качестве метки на карте?**
> 
> _На данный момент такой возможности нет._

Т.е. если у меня стоит задача нарисовать метки каких-то событий с произвольной иконкой. то этого сделать не получится?

В старом MapKit я это делаю при помощи:
`new OverlayItem(new GeoPoint(lat, lon), mMyIcon)`

Есть ли вообще какой-нибудь гайд по переходу и сравнению возможностей старого MapKit и нового, чтобы оценить реальность решения текущих задач. А то я сейчас руководство уговорю на платную лицензию, а окажется, что API скудное для реализации наших задач...

**Comment by eberkovich** [comment]
> Можно ли использовать произвольный объект в качестве метки на карте?
> На данный момент такой возможности нет.

Под произвольным объектом имелось ввиду какое-то View.
Иконки в качестве меток на карте, конечно, использовать можно, вот [пример](https://github.com/yandex/mapkit-android-demo/blob/0d493e2470e4793570aff1324ab15ccbaccb008c/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L139).
Да и View уже тоже [можно](https://github.com/yandex/mapkit-android-demo/blob/0d493e2470e4793570aff1324ab15ccbaccb008c/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L206), так что из FAQ это удалим.

> Есть ли вообще какой-нибудь гайд по переходу

Такого нет, но опять же есть [примеры](https://github.com/yandexmobile/yandexmapkit-android).
