### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by afborodin** [yandex/mapkit-android-demo#142]
Xiaomi Redmi 6, Android 9

`Fatal Exception: java.lang.RuntimeException
thread constructor failed: Try again Caused by: # 0: 1525664 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev # 1: 1525164 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so __cxa_throw # 2: 1425396 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so # 3: 1424364 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so # 4: 1432968 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so # 5: 1423976 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so # 6: 1428668 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.runtime.so _ZN6yandex4maps7runtime5async10backgroundENS2_18DispatcherPriorityE # 7: 5177476 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so # 8: 5173796 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so # 9: 5200112 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so #10: 5199628 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so #11: 5173240 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so #12: 5199404 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so #13: 5173056 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so #14: 5274524 /data/app/com.avito.android-xj1p0iUHpnqRyoEsdWOdwg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libcom.yandex.mapkit.so Java_com_yandex_mapkit_MapKitFactory_getInstance`

**Comment by eberkovich** [comment]
уточните пожалуйста версии mapkit/runtime и сценарий использования.

**Comment by afborodin** [comment]
Mapkit 3.3.1 от 12-Feb-2019 https://search.maven.org/artifact/com.yandex.android/mapkit/3.3.1/aar

Сценарий использования – Activity --> Fragment --> MapView с 2 маркерами.

**Comment by eberkovich** [comment]
Крешится конструктор Mapkit. 
Стоит проверить, что, обращение к Mapkit происходит из UI потока.

Кроме того рекомендую обновиться на mapkit 3.4, а также использовать 64 битную версию mapkit для arm64 устройств, в противном случае на некоторых устройствах могут возникать проблемы с OpenGL драйверами.

**Comment by afborodin** [comment]
Проверил, UI.

**Comment by eberkovich** [comment]
Тогда предлагаю обновиться на 3.4 и переключиться на 64 битную версию для 64 битных устройств, как я понимаю это все равно [необходимо](https://developer.android.com/distribute/best-practices/develop/64-bit). 
Если это не поможет, то понадобится минимальный пример.

**Comment by eberkovich** [comment]
Удалось ли разобраться?
