### ISSUE TITLE
Подключение через библиотеку привязок Xamarin, ошибка

### ISSUE THREAD

**Issue by mizantrop777** [yandex/mapkit-android-demo#143]
При портировании через библиотеку привязок ругается на Runtime и MapKit. 
Тип "JobPreconditions" уже определяет член "CheckNotEmpty" с такими же типами параметров.
"FixedJobIntentService.FixedJobServiceEngineImpl" не реализует член интерфейса "JobIntentService.ICompatJobEngine.DequeueWork()".	
"ClientBinding" не реализует член интерфейса "IInterface.AsBinder()".

Остальные дополнительные библиотеки компилятся нормально. 
Скрин ошибок прилагаю 
![2019-11-25_00-26-49](https://user-images.githubusercontent.com/30718125/69501934-d1b3a880-0f1a-11ea-89b4-c4d32f3b4e31.png)

**Comment by DmitryMitin** [comment]
Привет, получилось что-то сделать с mapKit? У вас на скриншоте есть привzзка на runtime, что это за привязка?

**Comment by DmitryMitin** [comment]
У меня все завелось, спасибо за скрин с зависимостями без него ничего б не получилось

**Comment by jokerpnz** [comment]
> У меня все завелось, спасибо за скрин с зависимостями без него ничего б не получилось

А можно подробнее? с какими версиями aar завелось? Если не сложно, опишите, что делали. 2 дня бьюсь, не получается, те же ошибки, что и выше(
