### ISSUE TITLE
Runtime.loadLibrary line 3 UnsatisfiedLinkError:Couldn't load c++_shared

### ISSUE THREAD

**Issue by afborodin** [yandex/mapkit-android-demo#145]
Fatal Exception: java.lang.UnsatisfiedLinkError
Couldn't load c++_shared

Android 9.0

**Comment by afborodin** [comment]
Mapkit 3.3.1 от 12-Feb-2019 https://search.maven.org/artifact/com.yandex.android/mapkit/3.3.1/aar

Сценарий использования – Activity --> Fragment --> MapView с 2 маркерами.

Повторяется **только на Android 9.0**

**Comment by afborodin** [comment]
@yandex

**Comment by mizantrop777** [comment]
они не отвечают, им пофиг

**Comment by IUdalov** [comment]
Скорее всего не хватает 64 битных библиотек.
Скорее это то же самое что и https://github.com/yandex/mapkit-android-demo/issues/4.
В 3.4 должно быть всё ок.
Под какую архитектуру ошибка?
