### ISSUE TITLE
How to get coords (lat/long) ?

### ISSUE THREAD

**Issue by savvavolobuev** [yandex/mapkit-android-demo#15]
How to get coords (lat/long) ? obj seems no be empty after this. 

 mapview.getMap().addTapListener(new GeoObjectTapListener() {
            @Override
            public boolean onObjectTap(GeoObjectTapEvent geoObjectTapEvent) {
                GeoObject obj = geoObjectTapEvent.getGeoObject();     
                return false;
            }
        });

I'm looking for any option to get coords from tap. Thx

**Comment by elricbk** [comment]
Use `InputListener` instead of `TapListener`. It has `onMapTap` event.
