### ISSUE TITLE
Не правильно работает mapView!!.map.move (kotlin)

### ISSUE THREAD

**Issue by MobileSolutionsRu** [yandex/mapkit-android-demo#150]
Не понимаю почему так, сейчас пытаюсь приблизить участок на карте так:
`mapView!!.map.move(
            CameraPosition(petersburgPoint, 200f, 1.0f, 1.0f),
            Animation(Animation.Type.SMOOTH, 15f),
            null
        )`
Получаю
<img width="404" alt="Screenshot 2019-12-21 at 13 21 14" src="https://user-images.githubusercontent.com/57910916/71306697-d9b91800-23f4-11ea-99e8-cb5871f1d005.png">
это явно не приближение которое я хочу

**Comment by MobileSolutionsRu** [comment]
+ еще : яндекс компания русская, а карты на английском. Почему нигде не сказано как сменить язык?

**Comment by eberkovich** [comment]
- 200 - некорректный масштаб, максимальный масштаб 19.
- карта используется язык системы, а он в эмуляторе по умолчанию английский.

**Comment by MobileSolutionsRu** [comment]
Спасибо

**Comment by Je-Hunter** [comment]
>     * еще : яндекс компания русская, а карты на английском. Почему нигде не сказано как сменить язык?

Такая же проблема была, решил так: MapKitFactory.setLocale("Ru_Ru");
