### ISSUE TITLE
Не понимаю как добавить GeoObjectTapListener к картам

### ISSUE THREAD

**Issue by MobileSolutionsRu** [yandex/mapkit-android-demo#151]
делаю так:
`mapView!!.map.addTapListener(clickListener)`
clickListener - GeoObjectTapListener
но при нажатии на объект, который добавлен на карте через
`mapView!!.map.mapObjects.addPlacemark`
не вызывается метод у GeoObjectTapListener
`onObjectTap`

**Comment by eberkovich** [comment]
Вам нужно использовать MapObjectTapListener.

На карте есть два типа объектов:
GeoObject - объекты в слоях карты, например: poi, дома.
MapObject - пользовательские объекты добавленные на карту, Placemark - наследник MapObject.

Нажатия на MapObject обрабатываются с помощью MapObjectTapListener, на GeoObject c помощью GeoObjectTapListener.

**Comment by MobileSolutionsRu** [comment]
А то что я использую `Placemark` и добавляю через`mapView!!.map.mapObjects.addPlacemark` - это нисего?

**Comment by MobileSolutionsRu** [comment]
mapObjects - же

**Comment by eberkovich** [comment]
Не понял вопрос.

**Comment by MobileSolutionsRu** [comment]
> Placemark

 - подкласс mapObject, да?

**Comment by MobileSolutionsRu** [comment]
а куда добавить MapObjectTapListener? mapView!!.map? тм нет такого метода

**Comment by eberkovich** [comment]
> > Placemark
> 
> подкласс mapObject, да?

Да.
https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/PlacemarkMapObject-docpage/

>> а куда добавить MapObjectTapListener? mapView!!.map? там нет такого метода

В коллекцию или конкретный placemark.
https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObject-docpage/#method_detail__method_addTapListener___NonNullMapObjectTapListener
