### ISSUE TITLE
Почему Search отдает не все точки включенные в видимую область карты?

### ISSUE THREAD

**Issue by murrcha** [yandex/mapkit-android-demo#152]
Осуществляю поиск по строке c помощью SearchManager.submit(): 
**Общество с ограниченной ответственностью микрокредитная компания «Деньги»**

```
searchManager.submit(
                   name, 
                   geometry, 
                   new SearchOptions()
                        .setSearchTypes(SearchType.BIZ.ordinal()),
                   searchListener);
```

Передаю текущий экран карты в качестве Geometry:
**map.getVisibleRegion()**

Полученные объекты вывожу на карту.
При изменении масштаба или при перемещении карты перезапрашиваю объекты (SearchManager.submit()) по этой же самой поисковой строке и вывожу на карту.

Проблема в том, что на карте при отображении одного и того же видимого региона, при незначительном изменении масштаба, объекты то отображаются, то нет. 
То есть при незначительном изменении видимого региона мы можем не получить точки, которые в него включены.

Аналогичная ситуация наблюдается в веб на картах Яндекс.Карты.

К примеру, вот скриншот1, где нет запрашиваемых точек:
![screen1](https://user-images.githubusercontent.com/18559291/71508784-66a31c00-28a2-11ea-9487-8e9cfcbbd6c8.png)

И вот скриншот2, с незначительным изменением масштаба, но уже с точками:
![screen2](https://user-images.githubusercontent.com/18559291/71508791-6d319380-28a2-11ea-908c-65a22e7a4590.png)

_Почему мы не получаем объекты, которые находятся в запрашиваемой геометрии (видимая область карты)? 
По какому принципу отдаются объекты исходя из передаваемой геометрии?_

**Comment by elricbk** [comment]
Такое поведение связано с тем, что запрос не совпадает с названием организации ("Деньга"). Скорее всего, поиск разбирает этот запрос как поиск микрокредитных организаций. И из-за особенностей работы серверного алгоритма может находить тот или иной набор организаций в зависимости от окна карты/процента текстового совпадения названия организации и запроса пользователя. Точнее, к сожалению, не подскажу.

Если поменять запрос так, чтобы он совпадал с названием организации – `Общество с ограниченной ответственностью микрокредитная компания «Деньгa»`, то находиться будут одни и те же организации.

В MapKit, чтобы сгладить негативные эффекты от такого поведения, можно попробовать использовать [поисковый слой][1]. Он сам будет перезадавать запрос при приближении/отдалении карты, и в нём есть дополнительная логика по сохранению пинов, чтобы они не пропадали.

[1]: https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/search_layer/package-summary-docpage/

**Comment by murrcha** [comment]
Спасибо за ответ. 
Правильно ли понимаю, что если не нашлась конкретная организация именно с таким названием (Общество с ограниченной ответственностью микрокредитная компания «Деньги»), то такое поведение будет всегда (без использования поискового слоя)?
И только в случае точного совпадения наименования организации будут отображаться одни и те же пины?

**Comment by elricbk** [comment]
Тут может играть роль, что запрос длинный и одно из слов почти совпадает с названием. Для обычных рубричных запросов ("мфо") пины будут вести себя более ожидаемым образом – появляться при "призуме", исчезать при "отзуме".
