### ISSUE TITLE
TileProvider out of memory при работе с geojson

### ISSUE THREAD

**Issue by AlexShilkin** [yandex/mapkit-android-demo#153]
TileProvider { tileId, version, etag ->
      RawTile(version, etag, RawTile.State.OK, rawGeoJson)
}

В TileProvider  в RawTile заргужаю geojson  c большим количеством объектов (10000 - 15000) 
TileProvider часто вызывает метод load и если некоторое время постоянно перемещаться по карте то происходит вылет из приложения, так как заканчивается доступная память.
Каждый раз при вызове метода load загружается целый geojson.
При вылете не возникает ошибок.

Есть ли возможность это исправить?

**Comment by eberkovich** [comment]
уточните пожалуйста, что это за объекты:  сколько в них точек?

**Comment by AlexShilkin** [comment]
В состав geojson входят LineString и Polygon.
LineString в основном из 2 точек  но бывают и больше

{
      "type": "Feature",
      "id": "id_868",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            39.209618,
            51.677668
          ],
          [
            39.203574,
            51.677591
          ],
          [
            39.204505,
            51.678964
          ],
          [
            39.205533,
            51.698227
          ]
        ]
      }

Polygon  в основном состоит из 5 точек но бывает и 10
{
      "type": "Feature",
      "id": "id_1019",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              39.202002,
              51.651073
            ],
            [
              39.204788,
              51.679116
            ],
            [
              39.253735,
              51.659176
            ],
            [
              39.131649,
              51.709143
            ],
            [
              39.202002,
              51.651073
            ]
          ]
        ]
      },
      "properties": {
        "layerName": "GJL",
        "classId": 882433023,
        "presentation": {
          "classes": [
            {
              "name": "PStl",
              "id": 882433023,
              "slices": [
                {
                  "poly": {
                    "color": 882433023
                  }
                }
              ]
            }
          ]
        }
      }
    }

Json сотовляет около 3 мб. ~ 10000 объектов
Проблема начинается когда часто меняются тайлы особенно на высоких зумах (с 14), т.к. каждый раз в TileProvider загружает целый json.

**Comment by eberkovich** [comment]
>3 мб. ~ 10000 объектов
Уточните пожалуйста, речь про размер одного тайла?
Если нет,  сколько точек в одном тайле?

Есть ли в TileProvider кеширование и если да, то сколько тайлов хранится в RAM?

**Comment by AlexShilkin** [comment]
Кеширование включено 
        val layerOptions = LayerOptions()
        layerOptions.animateOnActivation = true
        layerOptions.overzoomMode = OverzoomMode.WITH_PREFETCH
        layerOptions.cacheable = true

В Java heap храниться 64 тайла по 44 байта.
Вы же про это имели ввиду?

**Comment by eberkovich** [comment]
Нет, я имел ввиду, не кешируете ли вы тайлы еще на своей стороне внутри TileProvider.

Ну и вот это тоже я не понял:
>> 3 мб. ~ 10000 объектов

>Уточните пожалуйста, речь про размер одного тайла?
>Если нет, сколько точек в одном тайле?

**Comment by AlexShilkin** [comment]
3 мб. - это размер byte[] rawData который передается в tileProvider 
10000 объектов(feature) - это кол-во объектов в geojson, которые передаются в tileProvider, суммарно около 40000 точек.

Внутри TileProvider не кешируются объекты. Табота с TileProvider осуществляется по примеру  mapkit-android-demo/src/main/java/com/yandex/mapkitdemo/GeoJsonActivity.java

**Comment by eberkovich** [comment]
40000 точек на тайл - это слишком много, мы исходили из того, что в целом кадре будет в районе 100к точек.  У Вас если на экран влезет 20 тайлов, что вполне может быть, получится 800к точек. 
Видимо, нужно симплифицировать геометрию. Как вариант, можно попробовать рисовать на 14 масштабе данные которые сейчас используются для 13(или еще какого-то более обзорного масштаба).
