### ISSUE TITLE
get center Map.

### ISSUE THREAD

**Issue by bogdanovkp** [yandex/mapkit-android-demo#154]
Подскажите, как получить координаты центра карты.

**Comment by eberkovich** [comment]
Нужно воспользоваться [Map.getCameraPosition](
https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_getCameraPosition).

По умолчанию (если не был вызван [MapWindow.setFocusRect](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapWindow-docpage/#method_detail__method_setFocusRect___NullableScreenRect))cameraPosition будет в середине экрана.
