### ISSUE TITLE
Поддержка отображения нескольких ViewHolder с MapView в RecyclerView

### ISSUE THREAD

**Issue by afborodin** [yandex/mapkit-android-demo#155]
В случае нахождения на экране или вообще в RecyclerView нескольких (n > 1) вьюхолдеров с MapView вьюха начинает фризить весь список, на ней вылезают артефакты в виде черных полос или просто черных изображений. yandex:movable="true" и setNoninteractive(true) не помогают.

При этом MapView нормально отрисовывается и работает без лагов с том случае, если в RecyclerView находится ровно один (n = 1) ViewHolder с MapView.

**Comment by afborodin** [comment]
Samsung A7 2018
MapKit 3.3.1

**Comment by eberkovich** [comment]
Сможете сделать минимальный пример?

**Comment by afborodin** [comment]
Да, прикреплю как сделаю
