### ISSUE TITLE
Изменение геометрии PolylineMapObject в зависимости от геопозиции

### ISSUE THREAD

**Issue by tih05** [yandex/mapkit-android-demo#157]
Пытаюсь реализовать ведение по маршруту как в Яндекс Навигаторе. Я получаю маршрут и рисую его на карте посредством addPolyline(). При движении по маршруту делаю проекцию текущего местоположения на маршрут. Подскажите, пожалуйста, каким образом возможно реализовать удаление/скрытие пройденного пути на PolylineMapObject?

**Comment by eberkovich** [comment]
Для отрисовки маршрута как в Навигаторе лучше использовать 
[ColoredPolylineMapObject ](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/ColoredPolylineMapObject-docpage/) у него есть метод hide,  с помощью которого можно быстро скрывать часть маршрута, кроме того можно добавлять стрелки маневров с помощью addArrow.

Кроме того, для упрощения создания ColoredPolylineMapObject по маршруту можно использовать 
[RouteHelper](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-directions/ref/com/yandex/mapkit/directions/driving/RouteHelper-docpage/). Кроме того, использование RouteHelper заметно ускоряет создание ColoredPolylineMapObject по маршруту за счет уменьшения java - cpp взаимодействия.

**Comment by Privatik** [comment]
@eberkovich Нет ли у вас примера как отрисовать ColoredPolylineMapObject, я два дня сидел, и так у меня ничего и не вышло
