### ISSUE TITLE
Как выбрать определнный маркер?

### ISSUE THREAD

**Issue by AlexDukachev** [yandex/mapkit-android-demo#160]
Как-то можно выбрать определенный маркер из тех что были добавлены ранее, чтобы изменить например иконку?

**Comment by eberkovich** [comment]
- К объекту можно привязать произвольные данные с помощью метода [setUserData](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObject-docpage/#method_detail__method_setUserData___NullableObject), для того, чтобы его можно было идентифицировать.

- Для обхода MapObjectCollection нужно воспользоваться методом [traverse](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObjectCollection-docpage/#method_detail__method_traverse___NonNullMapObjectVisitor).

**Comment by AlexDukachev** [comment]
как в примере можно это? не совсем понятно.
нужно всю колекцию прогонять чтобы найти определенную или как?

в моем случае на карту заранее проставляется n количество маркеров. и выводится список объектов, вот по нажатию на один из item в recyclerview необходимо не только отцентровать на заранее проставленный маркер, но и изменить ему иконку

**Comment by eberkovich** [comment]
>нужно всю колекцию прогонять чтобы найти определенную или как?
Да, конечно traverse обходит всю коллекцию.

**Comment by AlexDukachev** [comment]
Пример дать можете?!

**Comment by gc986** [comment]
Как выбрать маркер в кластере? 
До перехода к кластерам всё было норм, но как перешли на кластеры, то точки перестали возвращаться с помощью map.mapObjects.traverse.
mapkit 4.0 lite

**Comment by EugeneAsti** [comment]
Как восстановить ссылки к расставленным (через метод addPlacemark(point)) меткам после поворота экрана?

По примеру смог поставить маркеры на карту через метод addPlacemark(point). Затем через метод mapObject.remove(mark) могу удалять эти метки. 
После этого поворачиваю экран и все метки исчезают. 
Придумал сохранять координаты проставленных меток, и после поворота экрана восстанавливаю их в цикле через метод addPlacemark(point) и все вроде стало красиво, но, теперь, повторно нанесенные метки не удаляются. Как будто они на разных слоях и при попытке их удалить, ничего не происходит. Прочитал тут про некий метод mapObject.travers, но ему нужен MapObjectVisitor, хз, где его брать. Создал объект: 
private val mapVisitor = object : MapObjectVisitor {
        override fun onPlacemarkVisited(p0: PlacemarkMapObject) {
            print("onPlacemarkVisited----------------")
            myViewModel.removeMarkFromArray(p0)
        }
...
}
и передал его в mapObject.travers, но этот метод не вызывается: onPlacemarkVisited равно как и любой другой метод MapObjectVisitor.
Пожалуйста, помогите. :)
