### ISSUE TITLE
Вопрос: появление placemarkMapObject на карте

### ISSUE THREAD

**Issue by agent10** [yandex/mapkit-android-demo#161]
У меня не все плейсмарки сразу видны на экране + я использую кластеринг.
При этом картинки для плейсмарков грузятся из сети.
Как следить за тем, что плейсмарк появляется или пропадает с экрана чтобы подгружать только то, что видно?

**Comment by eberkovich** [comment]
Для этого нужно воспользоваться [CameraListener](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/CameraListener-docpage/), установив его с помощью [Map.addCameraListener.](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_addCameraListener___NonNullCameraListener)

На всякий случай, в Mapkit есть встроенная поддержка кластеризации, вот [пример](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/ClusteringActivity.java).

**Comment by agent10** [comment]
Да я пользовался встроенной поддержкой. И всё равно не понял как получить нужную инфу из CameraListener.
Я имел ввиду методы как в гугловой карте типа:
onBeforeClusterItemRendered
onBeforeClusterRendered
onClusterRendered
onClusterItemRendered

**Comment by eberkovich** [comment]
Таких методов нет, есть только: ClusterListener.onClusterAdded.

По поводу CameraListener, получив нотификацию: onCameraPositionChanged, можно позвать map.getVisibleRegion() и дальше самостоятельно определить видимость объектов.
