### ISSUE TITLE
- К объекту можно привязать произвольные данные с помощью метода [setUserData](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObject-docpage/#method_detail__method_setUserData___NullableObject), для того, чтобы его можно было идентифицировать.

### ISSUE THREAD

**Issue by AlexDukachev** [yandex/mapkit-android-demo#162]
- К объекту можно привязать произвольные данные с помощью метода [setUserData](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObject-docpage/#method_detail__method_setUserData___NullableObject), для того, чтобы его можно было идентифицировать.

- Для обхода MapObjectCollection нужно воспользоваться методом [traverse](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObjectCollection-docpage/#method_detail__method_traverse___NonNullMapObjectVisitor).

как в примере можно это? не совсем понятно.
нужно всю колекцию прогонять чтобы найти определенную или как?

в моем случае на карту заранее проставляется n количество маркеров. и выводится список объектов, вот по нажатию на один из item в recyclerview необходимо не только отцентровать на заранее проставленный маркер, но и изменить ему иконку

_Originally posted by @eberkovich in https://github.com/yandex/mapkit-android-demo/issues/160#issuecomment-591090667_

**Comment by eberkovich** [comment]
Дублирует https://github.com/yandex/mapkit-android-demo/issues/160.
