### ISSUE TITLE
Очистка кеша TileProvider

### ISSUE THREAD

**Issue by AlexShilkin** [yandex/mapkit-android-demo#163]
Здравствуйте. 

Есть кейс: 
на карте отображается geojson с помощью TileProvider,
необходимо отобразить новый geojson, при это чтобы данные от старого geojson не отображались на карте.

При изменении версии layer.invalidate(newVersion) данные не очищаются.
Подскажите пожалуйста, как это сделать?

**Comment by eberkovich** [comment]
Здравствуйте, в этом случае тайлы и не должны сбрасываться. 
После изменения версии,  через invalidate мапкит перезапросит тайлы у TileProvider и если тот отдаст тайлы с новой версией, отрисует их.

**Comment by AlexShilkin** [comment]
А есть ли возможность удалять не отрисовывать тайлы со старой версией?

**Comment by eberkovich** [comment]
Да, для этого нужно позвать Layer.clear().
