### ISSUE TITLE
Remove placemark error, JNI global references in Android 4.1 - 4.3

### ISSUE THREAD

**Issue by ghost** [yandex/mapkit-android-demo#164]
Не получается удалить Placemark с коллекции перепробовал несколько способов:
 - clusteredCollection.getParent().remove(placemarkMapObject);
 - placemarkMapObject.getParent().remove(placemarkMapObject);
 - map.getMap().getMapObjects().remove(placemarkMapObject);
 - map.getMapWindow().getMap().getMapObjects().remove(placemarkMapObject).

Placemark при создании заранее сохраняю в коллекцию.

Я реализовал создание Placemarks только в видимой области пользователя, а при выходе Placemark за пределы видимости я хочу удалять или если есть способ очищать Placemark от данных таких как (ImageProvider, UserData, TapListener) буду рад узнать про это. Данная реализация будет распространяться для Android 4.1 - 4.3.

Причина по которой я прибегнул к данной реализации это ошибка связанная с JNI global references на Android 4.1 - 4.3 при попытке добавить свыше 300 Placemarks, что касается выше Android 4.3 то там все работает корректно.

Еще раз повторю вопросы:
 1) Я хочу удалить Placemark но у меня возникает ошибка, как мне правильно это сделать или с чем эта ошибка может быть связана?
     - Как я понял из ошибки она возникает при попытке получить родителя или нет ?

2) Если можно очистить Placemark, то пожалуйста дайте мне об этом знать.
     - Если в случае с TapListener я его могу удалить, и с UserData я могу присвоить null, то вот как быть с ImageProvider? Да и вообще этот способ не блистает лучшим качеством поэтому я надеюсь есть более альтернативное решение.

3) Если можно исправить ошибку связанную с JNI буду рад выслушать.

P.S.
MapKit 3.4.0.
Все воспроизводиться в UI потоке.
Использую эмуляторы в Android Studio.
ImageProvider я храню в отдельном классе и они не пересоздаются, также поступаю и с IconStyle. 

Заранее спасибо!!!

**Ошибка добавления множества Placemarks:**

<---------------------------------------------->
W/dalvikvm: JNI global reference table (0xb9caee30) dump:
      Last 10 entries (of 2001):
         2000: 0x9472c458 java.lang.ref.WeakReference
         1999: 0x93f61de0 by.bps.sbol.fragment.yandex_map.-$$Lambda$MapTabFragment$hb83p0Lx2NQS9L6fKQusdXKDzk0
         1998: 0x9472c338 com.yandex.mapkit.map.internal.MapObjectBinding$2
         1997: 0x940a4100 by.bps.sbol.data.bankobj.BankObject
         1996: 0x9472c188 java.lang.ref.WeakReference
         1995: 0x946e9c10 com.yandex.runtime.image.ImageProvider$3
         1994: 0x9472c278 com.yandex.mapkit.map.internal.PlacemarkMapObjectBinding
         1993: 0x940b6ff0 by.bps.sbol.data.bankobj.BankObject
         1992: 0x9472be68 java.lang.ref.WeakReference
         1991: 0x946e9c10 com.yandex.runtime.image.ImageProvider$3

/...
E/dalvikvm: Excessive JNI global references (2001)
    VM aborting
<---------------------------------------------->

**Ошибка возникающая при удалении:**

<---------------------------------------------->
 Caused by: java.lang.RuntimeException: Native object's weak_ptr for N6yandex4maps6mapkit3map9MapObjectE has expired
    Exception stack trace (top 7 entries):
      # 0: 1621304  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
      # 1: 1638971  libcom.yandex.runtime.so 
      # 2: 1638385  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS2_8SeverityE
      # 3: 1747940  libcom.yandex.mapkit.so 
      # 4: 6313563  libcom.yandex.mapkit.so 
      # 5: 6407875  libcom.yandex.mapkit.so Java_com_yandex_mapkit_map_internal_MapObjectBinding_getParent__
      # 6: 109216  libdvm.so dvmPlatformInvoke
    
        at com.yandex.mapkit.map.internal.MapObjectBinding.getParent(Native Method)
        at by.bps.sbol.fragment.yandex_map.ClustersLayer.removePlacemark(ClustersLayer.java:228)
        at by.bps.sbol.fragment.yandex_map.ClustersLayer$1.onNext(ClustersLayer.java:292)
        at by.bps.sbol.fragment.yandex_map.ClustersLayer$1.onNext(ClustersLayer.java:253)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        	... 9 more
<---------------------------------------------->

**Comment by eberkovich** [comment]
Плейсмарками владеет карта, в приложении сохраняются слабые ссылки. Указанная Вами ошибка говорит о том, объект уже был удален, видимо приложение каким-то образом удаляет один и тот же объект дважды.

**Comment by GH-John** [comment]
Можно ли очищать Placemark от данных, сделать его пустым?

**Comment by GH-John** [comment]
Как удалить ImageProvider у созданного Placemark?

**Comment by GH-John** [comment]
Я перепроверил место где происходит удаление, приложение заходит туда все один раз и все равно ошибка

java.lang.RuntimeException: Native object's weak_ptr for N6yandex4maps6mapkit3map9MapObjectE has expired
Exception stack trace (top 9 entries):
  # 0: 1621304  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
  # 1: 1638971  libcom.yandex.runtime.so 
  # 2: 1638385  libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS2_8SeverityE
  # 3: 1747940  libcom.yandex.mapkit.so 
  # 4: 6313563  libcom.yandex.mapkit.so 
  # 5: 6654197  libcom.yandex.mapkit.so 
  # 6: 6645658  libcom.yandex.mapkit.so 
  # 7: 6644777  libcom.yandex.mapkit.so Java_com_yandex_mapkit_map_internal_MapObjectCollectionBinding_remove__Lcom_yandex_mapkit_map_MapObject_2
  # 8: 109216  libdvm.so dvmPlatformInvoke

**Comment by eberkovich** [comment]
Возможно, где-то зовётся clear у коллекции?

**Comment by GH-John** [comment]
Нет не вызывается, может все таки есть способ очистить Placemark? Тогда и удалять мне его не придется.

**Comment by GH-John** [comment]
Я хочу очищать те Placemarks которые уже вышли за видимый регион пользователя, чтобы не происходил JNI global references, может все таки можно как то их очистить чтобы они просто стали пустыми? Не было привязанных к ним слушателей, данных пользователя и иконки.

**Comment by eberkovich** [comment]
Такого способа нет, сможете сделать минимальный пример с удалением?

**Comment by GH-John** [comment]
@Override
    public void onCameraPositionChanged(@NonNull Map map, @NonNull CameraPosition cameraPosition, @NonNull CameraUpdateSource cameraUpdateSource, boolean b) {
        if (isLowVersionSdk && b)
            updatePlacemarks(map.getVisibleRegion(), cameraPosition.getZoom());
    }

@SuppressLint("CheckResult")
    private void updatePlacemarks(VisibleRegion visibleRegion, float currentZoom) {
        toplat = visibleRegion.getTopLeft().getLatitude();
        bottomlat = visibleRegion.getBottomLeft().getLatitude();

        leftLon = visibleRegion.getBottomLeft().getLongitude();
        rightLon = visibleRegion.getBottomRight().getLongitude();

        Observable.fromIterable(collection)
                .map(mapPlacemark -> mapPlacemark)
                .subscribeOn(AndroidSchedulers.mainThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<MapPlacemark>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(MapPlacemark mapPlacemark) {
                        try {
                            if (mapPlacemark.getLatitude() != 0 && mapPlacemark.getLongitude() != 0) {
                                if (isInputToDiapasonLatitudes(toplat, bottomlat, mapPlacemark.getLatitude())
                                        && isInputToDiapasonLongitudes(leftLon, rightLon, mapPlacemark.getLongitude())) {

                                    Timber.tag("<- Start ->").d("");

                                    Timber.tag("CURRENT_ZOOM").d(String.valueOf(currentZoom));

                                    Timber.tag("LATITUDE_TOP/BOTTOM").d(toplat + " >= " + mapPlacemark.getLatitude() + " >=" + bottomlat);
                                    Timber.tag("LONGITUDE_LEFT/RIGHT").d(leftLon + " <= " + mapPlacemark.getLongitude() + " <=" + rightLon);

                                    Timber.tag("<- End ->").d("");

                                    Timber.tag("NEXT").d("------------------");

                                    if (currentZoom >= 14f && !includedInUserVisibility.contains(mapPlacemark)) {

                                        setPlacemarkData(mapPlacemark);
                                        includedInUserVisibility.add(mapPlacemark);

                                        countCreatedPlacemarks++;

                                        if (onCreatePlacemarkCallBack != null)
                                            onCreatePlacemarkCallBack.onCreated(mapPlacemark.getPlacemark());
                                    }

                                    counter++;
                                } else if (includedInUserVisibility.contains(mapPlacemark)) {
                                    removePlacemark(mapPlacemark.getPlacemark());

                                    includedInUserVisibility.remove(mapPlacemark);

                                    countCreatedPlacemarks--;
                                }
                            }
                        } catch (NullPointerException | IllegalArgumentException e) {
                            Timber.tag("onNext").d(e);
                        }
                    }

                    @Override
                    public void onError(Throwable e) {
                        Timber.e(e);
                    }

                    @Override
                    public void onComplete() {
                        Timber.tag("COUNT_CREATED_MARKERS").d(String.valueOf(countCreatedPlacemarks));
                        Timber.tag("COMPLETE").d("---------" + counter + "---------");
                        counter = 0;
                    }
                });
    }

public void removePlacemark(PlacemarkMapObject placemarkMapObject) {
        try {
            if (placemarkMapObject != null) {

                clusteredCollection.getParent().remove(placemarkMapObject);
            }
        } catch (RuntimeException e) {
            Timber.e(e);
        }
    }

**Comment by GH-John** [comment]
Метки создаются и отрабатывают как надо, только не удаляются.

**Comment by GH-John** [comment]
Какой вызов метода удаления Placemark с ClusteredCollection будет правильным?

**Comment by GH-John** [comment]
Я пробовал эти:
 - clusteredCollection.getParent().remove(placemarkMapObject);
 - placemarkMapObject.getParent().remove(placemarkMapObject);
 - map.getMap().getMapObjects().remove(placemarkMapObject);
 - map.getMapWindow().getMap().getMapObjects().remove(placemarkMapObject).

Какой самый верный?

**Comment by GH-John** [comment]
@eberkovich ?

**Comment by eberkovich** [comment]
В данный момент ClusterizedPlacemarkCollection не поддерживает удаление отдельных объектов, можно только сбросить все целиком с помощью clear.
Постараемся исправить в следующем релизе.

**Comment by GH-John** [comment]
Было здорово если бы был еще поиск в ClusterizedPlacemarkCollection по самому Placemark, и к примеру в большинстве случаев не нужно удалять Placemark вместо этого можно было бы  просто очистить нужный Placemark.

**Comment by eberkovich** [comment]
Все же переоткрою, до того момента пока не  добавим remove.

**Comment by GH-John** [comment]
Можно узнать что нового в версии MapKit 3.5.0? А то в доках ничего нет.

**Comment by eberkovich** [comment]
На днях опубликуем список изменений.

**Comment by Guryanov** [comment]
@eberkovich @YandexMapKit  так а что в итоге ? clusteredCollection.remove(placemarkMapObject) не работает.
