### ISSUE TITLE
Уведомление о кластеризации маркера

### ISSUE THREAD

**Issue by valya1** [yandex/mapkit-android-demo#171]
Мне необходимо убирать кастомное информационное окно над маркером как только он сворачивается в кластер.
Похоже что onClusterAdded вызывается только при первом появлении кластера на карте, и мне это не подходит.
Пробовал вешать MapObjectCollectionListener на объекты карты, но тоже не сработало. 
Есть ли какой-нибудь способ получить уведомление о кластеризации маркера?

**Comment by eberkovich** [comment]
Такого способа нет и пока нет планов его добавлять.
