### ISSUE TITLE
Как удалить с карты polyline

### ISSUE THREAD

**Issue by alexdarh** [yandex/mapkit-android-demo#172]
Собственно сабж. На карту выводится polyline из точек маршрута. При попытке построить новый, старый не удаляется. mapObjects.Clear() не работает. Ничего не очищает, но и ошибку не выдает. как быть?

**Comment by eberkovich** [comment]
Не могу воспроизвести такую проблему.

Не может быть такого, что Вы зовете clear у коллекции не являющейся предком Polyline или же добавление Polyline происходит после вызова clear?
Если это не так приложите пожалуйста минимальный пример.

**Comment by NomadicWarrior** [comment]
iOS mapObject.clear() удаляет все данные из карты а мне надо только удалит polylines. как быть?

**Comment by eberkovich** [comment]
>iOS mapObject.clear() удаляет все данные из карты а мне надо только удалит polylines. как быть

нужно удалить каждый polyline в отдельности через MapObjectCollection.remove(polylineMapObject).

**Comment by calibrator33** [comment]
Я тоже делаю коллекцию, добавляю в нее полилинии. Для этого создал функцию, в которой:

            // Добавил к карте слой с объектами
            let mapObjects = mapView.mapWindow.map.mapObjects
            
            // Создадал коллекцию объектов
            let polylinesCollection = mapObjects.add()
            
            // Строю полилинию из массива точек полилинии
            let polyline = polylinesCollection.addPolyline(with: YMKPolyline(points: polylinePoints))

Если надо, удаляею только полилинии (коллекцию полилиний). При этом остальные объекты не удаляются, что хорошо:

            polylinesCollection.clear()
