### ISSUE TITLE
Как можно из MapKit достать координаты

### ISSUE THREAD

**Issue by burtaevoleg** [yandex/mapkit-android-demo#173]
Я определяю свое местоположение и мне нужно как-то сохранить его. Подскажите, пожалуйста, как можно достать координаты из своего местоположения. 
Для нахождения местоположения использую:

UserLocationLayer userLocationLayer;
userLocationLayer=mapKit.createUserLocationLayer(mapView.getMapWindow());

**Comment by YandexMapKit** [comment]
Посмотрите в сторону класса [Location](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/location/package-summary.html).
