### ISSUE TITLE
Crash wnen click on logo/Падение при нажатии на логотип

### ISSUE THREAD

**Issue by alexkashapov** [yandex/mapkit-android-demo#174]
Условия: приложение работает из защищенной области Samsung KNOX под управлением Android Enterprise.  Версия ОС: Android 10. В защищенной области находится Google Play Market, но из него нет доступа к обычному списку приложений. То есть установить или даже открыть из него страничку приложения Яндекс Карт или Навигатора нельзя.
Во время работы с картой может произойти случайное нажатие на логотип. Подозреваю, что на нем висит клик листенер с интентом либо на приложение яндекс карт(или навигатора), либо в Google Play, чтобы его можно было скачать. Но в защищенной области это невозможно. Поэтому происходит падение.

**Comment by alexkashapov** [comment]
Добавлю комментарий - браузера в защищенной области тоже нет. То есть интент в него тоже не пройдет.

**Comment by TheMrButcher** [comment]
Пофикшено в MapKit 4.0.
