### ISSUE TITLE
Получить координаты перекрестков

### ISSUE THREAD

**Issue by OlFil** [yandex/mapkit-android-demo#178]
Здравствуйте. Можно ли как-то получить список перекрестков и их связей друг с другом?

**Comment by elricbk** [comment]
Можно получить информацию про отдельный перекрёсток, например, с помощью запроса "перекресток льва толстого и комсомольского проспекта". Но получить информацию про все перекрёстки нельзя. Поиск в MapKit в принципе не умеет работать в режиме "про все", неважно про какие объекты.
