### ISSUE TITLE
Проверить наличие объекта в коллекции

### ISSUE THREAD

**Issue by Go0dluck** [yandex/mapkit-android-demo#179]
Добавляю addPlacemark на карту и в цикле при изменении определенных условий нужно делать remove определенного Placemark но когда в цикле попадаю на удаление объекта крашиться и падает исключение из которого я понимаю что объект уже удален и удалить опять его не возможно, как проверить есть ли данный объект в коллекции прежде чем делать remove ?

**Comment by SWRHARD** [comment]
тоже интересно, up

**Comment by eaniconer** [comment]
@Go0dluck , @SWRHARD а можете показать код, на котором воспроизводится эта проблема?

**Comment by SWRHARD** [comment]
> @Go0dluck , @SWRHARD а можете показать код, на котором воспроизводится эта проблема?

Меня интересует в принципе как проверить наличие какого-то объекта в коллекции, просто циклом? у меня есть объекты на карте и при нажатии на объект, он должен менять свою иконку, то есть мне надо найти этот объект в коллекции и задать новую иконку

**Comment by Go0dluck** [comment]
> @Go0dluck , @SWRHARD а можете показать код, на котором воспроизводится эта проблема?

у меня есть два маркера один статичный и есть всегда второй динамичный и может удаляться и добавляться и мне надо проверять есть именно этот маркер в коллекции или нет

**Comment by eberkovich** [comment]
Не удалять дважды один и тот же объект - ответственность приложения. 
Корректного способа узнать у мапкита не является ли объект удаленным - нет.
