### ISSUE TITLE
Как построить маршрут по введённым адресам(from - to)

### ISSUE THREAD

**Issue by aniabogatova** [yandex/mapkit-android-demo#182]
Я пытаюсь сделать приложение в котором после ввода адресов откуда-куда будет строится маршрут на карте. Кто знает, как это можно сделать? (Приложение должно выглядеть примерно так: в первом при входе окне пользователь указывает адреса откуда-куда, после нажатия на кнопку в следующей активности (у меня это tabbed activity, поэтому в одном из его окон) выводится карта с построенным маршрутом)
Помогите пожалуйста 🙏

**Comment by aniabogatova** [comment]
Если это невозможно в таком формате, который я описала, то это не принципиально, мне просто нужно чтобы было построение маршрута по введенному адресу)

**Comment by dimmitriy** [comment]
DrivingActivity в помощь, есть в коде текущего репозитория

**Comment by aniabogatova** [comment]
Это я знаю, но как сделать это через получение координат мест, адрес которых будет вводить пользователь

> DrivingActivity в помощь, есть в коде текущего репозитория

**Comment by elricbk** [comment]
Координаты для построения маршрута можно получить через поиск адреса. На каждый адрес делаем поиск, получаем точки и уже их передаём в маршрутизатор.

**Comment by aniabogatova** [comment]
> Координаты для построения маршрута можно получить через поиск адреса. На каждый адрес делаем поиск, получаем точки и уже их передаём в маршрутизатор.

А у вас нет такого примера, а то я совсем не понимаю как это реализовывать(я просто ещё новичок в Android) 🙏

**Comment by elricbk** [comment]
Про поиск с примерами есть [статья на Хабре](https://habr.com/ru/company/yandex/blog/428564/). Ну и можно SuggestActivity.java и SearchActivity.java посмотреть.

**Comment by aniabogatova** [comment]
> Про поиск с примерами есть [статья на Хабре](https://habr.com/ru/company/yandex/blog/428564/). Ну и можно SuggestActivity.java и SearchActivity.java посмотреть.

Но ведь ответ поиска это response, как мне оттуда координаты вытащить?

**Comment by elricbk** [comment]
У меня сейчас под рукой нет Android Studio, поэтому вот пример на Swift, на Kotlin переписывается аналогично:

```swift
func extractPoint(response: YMKSearchResponse) -> YMKPoint? {
    return response.collection.children
        .compactMap { $0.obj }
        .first?
        .geometry
        .compactMap { $0.point }
        .first
}
```

Что здесь происходит:
* находим первый элемент в ответе, внутри которого есть `YMKGeoObject`: `.compactMap{ $0.obj }.first`
* берём у этого объекта список геометрий
* и находим первую геометрию, в которой есть точка `.compactMap{ $0.point }.first`

В общем случае, точки может и не быть (возвращается опциональный тип), потому что не для любого адреса геокодер может найти правильную точку. Поэтому перед построением маршрута нужно проверять, что точка извлечь получилось.

**Comment by aniabogatova** [comment]
> У меня сейчас под рукой нет Android Studio, поэтому вот пример на Swift, на Kotlin переписывается аналогично (только вместо `compactMap` будет `mapNotNull`):
> 
> ```swift
> func extractPoint(response: YMKSearchResponse) -> YMKPoint? {
>     return response.collection.children
>         .compactMap { $0.obj }
>         .first?
>         .geometry
>         .compactMap { $0.point }
>         .first
> }
> ```
> 
> Что здесь происходит:
> 
> * находим первый элемент в ответе, внутри которого есть `YMKGeoObject`: `.compactMap{ $0.obj }.first`
> * берём у этого объекта список геометрий
> * и находим первую геометрию, в которой есть точка `.compactMap{ $0.point }.first`
> 
> В общем случае, точки может и не быть (возвращается опциональный тип), потому что не для любого адреса геокодер может найти точку. Поэтому перед построением маршрута нужно проверять, что точки извлечь получилось.

Спасибо, буду пробовать сделать)

**Comment by mrmaga1** [comment]
Здравствуйте, у меня выдает ошибку на VehicleOptions. Нигде не указано что надо импортировать чтоб она заработала.
