### ISSUE TITLE
Определить зум карты для нормального отображения совокупности точек или полученному маршруту

### ISSUE THREAD

**Issue by dimmitriy** [yandex/mapkit-android-demo#183]
Я пытаюсь понять как вычислять хотя бы примерный зум карты когда у нас есть:
1)совокупность точек с координатами для отображения на карте
2)полученный маршрут вождения

Прорще говоря, можно ли как то задать карте какие координаты должна захватывать карта в верхнем левом и нижнем правом углах?

**Comment by eberkovich** [comment]
Для этого есть метод [Map.cameraPosition](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_cameraPosition___NonNullBoundingBox)
