### ISSUE TITLE
Как правильно удалять/изменять placemarks на карте

### ISSUE THREAD

**Issue by SWRHARD** [yandex/mapkit-android-demo#184]
Есть метод добавления placemarks на карту:

```
private MapObjectCollection mapObjects;

//метод вызывается в конструкторе
private void init() {
 mapObjects = getMap().getMapObjects().addCollection();
}

  private void createPoints(List<MapMarker> mapMarkers) {
        for (int i = 0; i < mapMarkers.size(); ++i) {
            MapMarker mapMarker = mapMarkers.get(i);
            GeoPoint geoPoint = mapMarker.getGeoPoint();
            ImageProvider imageProvider = ImageProvider.fromBitmap(
                    getBitmapFromVectorDrawable(mapMarker.getDrawable()));
            PlacemarkMapObject placemarkMapObject = mapObjects.addPlacemark(new Point(geoPoint.getLatitude(),
                    geoPoint.getLongitude()), imageProvider);
            placemarkMapObject.setUserData(mapMarker.getId());
            placemarkMapObject.addTapListener(this);
        }
    }
```

Мне нужно при нажатии на placemark изменять ее иконку, при этом одновременно выделенным может быть только один объект.

```
private MapObject selectedObject = null;

    @Override
    public boolean onMapObjectTap(@NonNull MapObject mapObject, @NonNull Point point) {
            selectedObject = mapObject;
            return true;
    }
```
Как из уже существующей коллекции вытаскивать определенный объект и изменять у него иконку?

**Comment by eberkovich** [comment]
Если нет возможности запомнить текущий выделенный элемент, то обойти коллекцию можно с помощью метода [MapObjectCollection.traverse](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObjectCollection-docpage/#method_detail__method_traverse___NonNullMapObjectVisitor).

Так же хочу заметить, что если в коллекции маркеров могут быть объекты с одинаковыми иконками, то создавать для каждого объекта свой ImageProvider не эффективно, как с точки зрения потребления памяти, так и с точки зрения производительности.
Важно использовать один и тот же экземпляр ImageProvider для одной и той же иконки.

**Comment by SWRHARD** [comment]
а как мне иконку менять, если я запомню выделенный элемент через метод onMapObjectTap? Ведь там MapObject, а иконка меняется у PlacemarkMapObject

**Comment by eberkovich** [comment]
PlacemarkMapObject наследуется от MapObject, нужно воспользоваться приведением типов.

**Comment by SWRHARD** [comment]
все понял, спасиба
