### ISSUE TITLE
Перекрытие polyline и placeMark при отрисовке

### ISSUE THREAD

**Issue by dimmitriy** [yandex/mapkit-android-demo#185]
PolylineMapObject polyline = mapObjects.addPolyline(new Polyline(polylinePoints));
            if (tripStart != null && tripStop != null) {
                mapObjects.addPlacemark(tripStart, ImageProvider.fromBitmap(bitmapStart));
                mapObjects.addPlacemark(tripStop, ImageProvider.fromBitmap(bitmapStop));
            }
polyline.setStrokeWidth(2);
При этом если картинка placeMark содержит прозрачную область внутри, становится виден polyline под ней. можно ли как то решить проблему стыковки polyline и placeMark?
 
![Screenshot_1](https://user-images.githubusercontent.com/9336436/82638447-95ce7700-9c0f-11ea-95ea-3a1116d0cd66.png)

**Comment by eberkovich** [comment]
Такой возможности нет.
