### ISSUE TITLE
как сделать обьект mapView максимально легким?

### ISSUE THREAD

**Issue by dimmitriy** [yandex/mapkit-android-demo#186]
Задача состоит отображать в списке много объектов mapView с прорисованными polyline. Вопрос как ее сделать максимально легким, кроме использования mMapView.getMap().setLiteModeEnabled(true)?

**Comment by eberkovich** [comment]
setLiteModeEnabled - не предназначен для уменьшения потребления памяти и приводит к появлению артефактов. Кроме того не является публичным:)

Для уменьшения расхода памяти можно отключить 3d модели (вместо них будут рисоваться экструдированные полигоны) с помощью метода [setModelsEnabled](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_setModelsEnabled__boolean).
