### ISSUE TITLE
Placemark меняет местоположение при установки новой иконки

### ISSUE THREAD

**Issue by SWRHARD** [yandex/mapkit-android-demo#187]
Заметил такую проблему, при нажатии на placemark, я меняю иконку посредством метода **setIcon** и placemark как бы смещается чуть вниз, то есть не остается в той же точке, что и был

```
(mapObject as PlacemarkMapObject).setIcon(ImageProvider.fromBitmap(getBitmapFromVectorDrawable(
                    resources.getDrawable(R.drawable.ic_pin_selected, null))), IconStyle().setAnchor(PointF(0.5f, 1.0f)))
```
В чем может быть проблема?

**Comment by SWRHARD** [comment]
сейчас проверил на нормальном девайсе, а не на эмуляторе, иконка изменяется и сползает вниз, при этом старая иконка остается, то есть не стирается, а на эмуляторе такого нету

**Comment by eberkovich** [comment]
Картинка перемещается из-за того, что Вы изменяете ее якорь с помощью метода setAnchor, кроме того она может визуально перемещаться  из-за того, что размер новой картинки, включая ее прозрачную область, не такой как у старой.
Что касается, того, что остается обе иконки, видимо, в этом месте находится два PlacemarkMapObject.

**Comment by SWRHARD** [comment]
ну якорь я ставлю такой-же, как и в самом начале при добавлении placemarket'a
