### ISSUE TITLE
Пропадают метки

### ISSUE THREAD

**Issue by baunty3000** [yandex/mapkit-android-demo#188]
Добрый день!
yandexmap 3.5.0 + tablayout + viewPager2(Лежит в LinearLayout)
Есть 2 вкладки на tablayout. Карта и список.
При инициализации на карте отображены метки. Все они хранятся в переменной + лисенеры.
Если перейти на вторую вкладку и затем переключиться назад на карту, метки пропадают.
При это у фрагмента карты срабатывает OnPause(), OnResume()

Если после инициализации нажать на несколько меток, делаю setIcon, после переключиться на другую вкладку(MapFragment = OnPause()) и вернуть на карту(MapFragment = OnResume()), пропадают метки которые не были нажаты.
Как это пофиксить?

**Comment by eberkovich** [comment]
Здравствуйте,

Тут могут быть две причины:

- Фрагмент, а вместе с ним MapView, пересоздается, но добавляет на карту, не все метки, которые были на ней до этого.
- Используется реализация ImageProvider, которая при повторном обращении отдает неверную/пустую картинку.

**Comment by baunty3000** [comment]
> Здравствуйте,
> 
> Тут могут быть две причины:
> 
> * Фрагмент, а вместе с ним MapView, пересоздается, но добавляет на карту, не все метки, которые были на ней до этого.
> * Используется реализация ImageProvider, которая при повторном обращении отдает неверную/пустую картинку.

1. Внешне карта перерисовывается каждый раз когда я перехожу на нее с другого Tab, может в этом причина? При этом, если я преешел с карты на другой Tab, фрагмент карты выполняет ЖЦ - onResume() -> onPause(). При переходе с другого Tab на карту, ЖЦ фрагмента карты - onPause() -> onResume()
2. Реализация ImageProvider, да и вообще вся инициализация производится в onStart(). Все иконки хранятся в полях. 
Инициализацию placeMarks, так же делал в onStart().

В силу оперативности пока, что пришлось каждый раз при переходе из onPause() -> onResume() добавлять метки на карту(старые чистить). Но это не лучшее решение. Хотелось бы понимать какие есть варианты.

Заранее спасибо!
