### ISSUE TITLE
MapObjectVisitor JNI exception

### ISSUE THREAD

**Issue by v-grishechko** [yandex/mapkit-android-demo#189]
Hello.

I've tried to use `MapObjectVisitor` to change dynamically `PlaceMarkObject` location and icons for performance reasons (clear and set new placemarks causes freezes). We dynamically loading geopoints during zoom and camera position changes. Also, we use clusterization (`ClusterizedPlacemarkCollection`). But this code causes exception in native code:
```kotlin
 val clusterCollection = mapView.map.mapObjects.addClusterizedPlacemarkCollection(this)
 clusterCollection.addEmptyPlacemark(Point(0.0, 0.0))
 mapView.map.mapObjects.traverse(EmptyTraverse())
```
```
JNI DETECTED ERROR IN APPLICATION: bad arguments passed to boolean 
com.example.EmptyTraverse
.onCollectionVisitStart(com.yandex.mapkit.map.MapObjectCollection) (see above for details)
```

(EmptyTravers implements MapObjectVisitor and do nothing)

But this code not causes crash:
```kotlin
  mapView.map.mapObjects.addEmptyPlacemark(Point(0.0, 0.0))
  mapView.map.mapObjects.traverse(EmptyTraverse())
```

I think it's bug. Could you suggest something to solve this issue or solve our task in another way? Thanks in advance.

**Comment by eberkovich** [comment]
Hello,

Yes, this is a bug and it will be fixed in the next release and method ClusterizedPlacemarkCollection.traverse() will be added.
Unfortunately, at this time it is impossible to traverse ClusterizedPlacemarkCollection, that is why it does not have method traverse by itself.

**Comment by v-grishechko** [comment]
When is going to be a new release?

**Comment by eberkovich** [comment]
I can't  answer for sure, but I think it will in June.

**Comment by TikhonOsipov** [comment]
JNI DETECTED ERROR IN APPLICATION: bad arguments passed to boolean com.yamarket.yamarket.screens.main.map.MapFragment$mapObjectVisitor$1.onCollectionVisitStart(com.yandex.mapkit.map.MapObjectCollection) (see above for details)  from void com.yandex.mapkit.map.internal.ClusterizedPlacemarkCollectionBinding.traverse(com.yandex.mapkit.map.MapObjectVisitor)

error still exists when calling traverse() on ClusterizedPlacemarkCollection object

**Comment by TikhonOsipov** [comment]
JNI DETECTED ERROR IN APPLICATION: bad arguments passed to boolean onCollectionVisitStart(com.yandex.mapkit.map.MapObjectCollection) (see above for details) from void com.yandex.mapkit.map.internal.ClusterizedPlacemarkCollectionBinding.traverse(com.yandex.mapkit.map.MapObjectVisitor)

**Comment by eberkovich** [comment]
It is fixed in mapkit 4.0, please try this version.

**Comment by TikhonOsipov** [comment]
I got this error on 4.0.0-lite (and 12 days ago I used 4.0.0-lite too). do you have any default map object visitors for clusterized collections?

**Comment by TikhonOsipov** [comment]
What happens:
ClusterizedPlacemarkCollectionBinding is passed to MapObjectVisitor$onCollectionVisitStart(MapObjectCollection).
ClusterizedPlacemarkCollectionBinding is an implementation of ClusterizedPlacemarkCollection, and it implements MapObject; MapObjectCollection implements MapObject too.

There is unable to cast ClusterizedPlacemarkCollection to MapObjectCollection because the invocation of MapObjectVisitor$onCollectionVisitStart is performed from the library core.

**Comment by TikhonOsipov** [comment]
MapObjectVisitor also contains these two methods:
fun onClusterizedCollectionVisitStart(p0: ClusterizedPlacemarkCollection): Boolean
fun onCollectionVisitStart(p0: MapObjectCollection): Boolean

ClusterizedPlacemarkCollection should be passed into onClusterizedCollectionVisitStart(), but is passed to onCollectionVisitStart()
