### ISSUE TITLE
addTapListener doesn't work

### ISSUE THREAD

**Issue by PeterStaranchuk** [yandex/mapkit-android-demo#19]
Try to add tap behaviour for placemark but this callback is never triggered.

for (nodeIndex in 0 until routeNodes.size) {
            val (node, r) = getDrawableForNode(routeNodes, nodeIndex) //TODO refactore

            val mark = mvMap.map.mapObjects.addPlacemark(Point(node.latitude, node.longitude), ImageProvider.fromBitmap(r))
            mark.addTapListener { p0, p1 ->
                if(p0 != null) {
                    val node = p0.userData as RouteNode
                    Toast.makeText(applicationContext, node.getDescription(), Toast.LENGTH_LONG).show()
                    true
                } else {
                    false
                }
            }

            mark.userData = node
            mark.opacity = 0.8f
        }

**Comment by eberkovich** [comment]
Listener objects that report the result of repeated operations or the state of an object must be explicitly stored in memory.

https://tech.yandex.com/mapkit/doc/3.x/concepts/android/quickstart-docpage/
