### ISSUE TITLE
Disable reveal cluster animation

### ISSUE THREAD

**Issue by v-grishechko** [yandex/mapkit-android-demo#190]
Hello.

When I am loading new points and add in ```ClusterizedPlacemarkCollection```  cluster appears with reveal animation, but how to turn it off? I often change ```ClusterizedPlacemarkCollection``` by reloading placemarks and that causes constant animation (it looks very annoying).

**Comment by eberkovich** [comment]
Hello, 
It is not supported.

**Comment by v-grishechko** [comment]
I've solved this. Created 2 clusterized collections and swap them when the animation is done. Ugly hack, but working.

**Comment by JorikFat** [comment]
@v-grishechko i need exaple too
