### ISSUE TITLE
Вызов MapKitFactory.initialize() не влияет на работу карты

### ISSUE THREAD

**Issue by kryanod** [yandex/mapkit-android-demo#192]
В [документации](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/quickstart-docpage/) говорится, что в Activity.onCreate надо вызывать MapKitFactory.initialize(). 

Но. Если этого не сделать, ничего не меняется: карта всё так же нормально грузится, onStart/onStop у MapView и MapKit вызываются всё так же быстро.

Собственно, вопрос: почему MapKitFactory.initialize() осязаемо ничего не делает? Версия 3.5.0

**Comment by eberkovich** [comment]
Видимо, MapKitFactory.initialize() зовется еще откуда-то.
Без этого вызова не произойдет загрузка нативной библиотеки, содержащей всю функциональность мапкита, не выставится api key и не произойдет ряд других инициализаций.
