### ISSUE TITLE
Logo padding

### ISSUE THREAD

**Issue by nickilanjelo** [yandex/mapkit-android-demo#193]
How can I set padding for Yandex logo on a map? Is there any analogue for Google Maps's method 'setPadding'?

**Comment by archiecrown** [comment]
You can use method `mapView.map.logo.setAlignment()`

**Comment by nickilanjelo** [comment]
> You can use method `mapView.map.logo.setAlignment()` 

I think this method only aligns logo on left or right side, but cannot set padding from the bottom of the screen. Is that true?
