### ISSUE TITLE
Зависает requestRoutes при использовании корутин

### ISSUE THREAD

**Issue by alexkazancew** [yandex/mapkit-android-demo#194]
Всем привет. 
При запросе маршрутов иногда листеенер сробатывает и возвращает результат, а иногда ничего не возрващет, даже ошибку. 
```kotlin
        withContext(Dispatchers.Main) {
            suspendCoroutine<List<DrivingRoute>> {
                drivingRouter.requestRoutes(points, options, object : DrivingSession.DrivingRouteListener {
                    override fun onDrivingRoutesError(p0: Error) {
                        it.resumeWithException(DirectionException("Can`t build route"))
                    }

                    override fun onDrivingRoutes(routes: MutableList<DrivingRoute>) {
                        it.resumeWith(routes)
                    }
                })
            }
        }
```
Это баг или я делаю что-то не так?

**Comment by elricbk** [comment]
Как минимум, `requestRoutes` возвращает сессию, которую нужно сохранять. Если сессию не сохранить, то в момент её уничтожения запрос отменится. Соответственно, если сборщик мусора дойдёт до возвращённой сессии раньше, чем вернётся какой-то ответ, то будут как раз симптомы вида "ничего не возрващет, даже ошибку".
