### ISSUE TITLE
Placemark Animation ?

### ISSUE THREAD

**Issue by cmbaykal** [yandex/mapkit-android-demo#196]
Hi. Can we animate PlaceMarkMapObject when we change the PlaceMarkMapObject icon ? For example if I have a bigger icon to set when changing be like scaling.

**Comment by eberkovich** [comment]
Hi, 

You can use method [IconStyle.setScale](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/IconStyle-docpage/#method_detail__method_setScale___NullableFloat).

Something like this: 

```
//change icon with scale corresponding to old icon size: 
placemark.setIcon(newImageProvide, new IconStyle().setScale(startScale), callback);

// and then (after the callback is called) animate scale:
placemark.setIconStyle(new IconStyle().setScale(startScale + epsilon));
```
