### ISSUE TITLE
App crashing on Samsung S8 

### ISSUE THREAD

**Issue by PeterStaranchuk** [yandex/mapkit-android-demo#20]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/m1traid.mwc/app_lib/libgnustl_shared.so" is 32-bit instead of 64-bit

**Comment by IUdalov** [comment]
It's clearly the same issue https://github.com/yandex/mapkit-android-demo/issues/4. But which version of gradle wrapper do you use?

**Comment by PeterStaranchuk** [comment]
update: the bug was in my side. I forgot to remove 2.5. version of MapKit.

**Comment by PeterStaranchuk** [comment]
thanks for fast response
