### ISSUE TITLE
Как удалить полигон с карты

### ISSUE THREAD

**Issue by omfg74** [yandex/mapkit-android-demo#200]
Полигоны добавляются через mapView.map.mapObjects.addPolygon(polygon), но удалить через  mapView.map.mapObjects.remove(polygon as MapObject) невозможно, т.к не возможно приведение типов. 
Возможно есть еще какое-то решение?

**Comment by eberkovich** [comment]
Для того чтобы удалить мап объект, нужно передать его в метода remove.

Вот так:

```
polygonMO = mapObjects.addPolygon(polygon);
mapObjects.remove(polygonMO);
```

polygon  - это, просто, геометрия по которой нужно построить объект, удалить объект по геометрии нельзя.
