### ISSUE TITLE
Error inflating class com.yandex.mapkit.mapview.MapView

### ISSUE THREAD

**Issue by StrelnikovEugene** [yandex/mapkit-android-demo#205]
Приветствую.
Не хочет работать при попыке добавить в проект с++ библиотеку.

Error inflating class com.yandex.mapkit.mapview.MapView

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.1"

    defaultConfig {
        applicationId "com.example.testmaps"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
    }
}

repositories {
    maven {
        url "http://maven.google.com/"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.navigation:navigation-fragment:2.1.0'
    implementation 'androidx.navigation:navigation-ui:2.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.yandex.android:mapkit:3.5.0'
    implementation 'com.yandex.android:search:3.5.0'


    implementation project(path: ':dmtxmanagerandroid')
    implementation project(path: ':dmtxmngrandroid-debug')

    implementation project(':opencv')


}
```

> 2020-08-10 17:00:55.090 16614-16614/com.example.testmaps E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.testmaps, PID: 16614
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testmaps/com.example.testmaps.MainActivity}: android.view.InflateException: Binary XML file line #9 in com.example.testmaps:layout/activity_main: Binary XML file line #9 in com.example.testmaps:layout/activity_main: Error inflating class com.yandex.mapkit.mapview.MapView
> ...
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>      Caused by: android.view.InflateException: Binary XML file line #9 in com.example.testmaps:layout/activity_main: Binary XML file line #9 in com.example.testmaps:layout/activity_main: Error inflating class com.yandex.mapkit.mapview.MapView
>      Caused by: android.view.InflateException: Binary XML file line #9 in com.example.testmaps:layout/activity_main: Error inflating class com.yandex.mapkit.mapview.MapView
>      Caused by: java.lang.reflect.InvocationTargetException
> ...
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
>      Caused by: java.lang.RuntimeException: Native object for N6yandex4maps7runtime4view12PlatformViewE is of wrong smart pointer type!
>     Exception stack trace (top 20 entries):
> 2020-08-10 17:00:55.091 16614-16614/com.example.testmaps E/AndroidRuntime:   # 0: 1666360  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9backtrace9BacktraceC1Ev
>       # 1: 1694653  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.runtime.so 
>       # 2: 1694067  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.runtime.so _ZN6yandex4maps7runtime9ExceptionC2ERKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEENS2_8SeverityE
>       # 3: 1894980  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.mapkit.so 
>       # 4: 7921307  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.mapkit.so 
>       # 5: 7921068  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.mapkit.so 
>       # 6: 7920910  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.mapkit.so 
>       # 7: 7905349  /data/app/~~69TdfTnUprLiqmN8K-i7tA==/com.example.testmaps-XEUhSwU00yUoIvSlrpyE1Q==/base.apk!/lib/x86/libcom.yandex.mapkit.so Java_com_yandex_mapkit_internal_MapKitBinding_createMapWindow__Lcom_yandex_runtime_view_PlatformGLView_2
>       # 8: 1319219  /apex/com.android.art/lib/libart.so 
>       # 9: 1292579  /apex/com.android.art/lib/libart.so 
>       #10: 1901442  /apex/com.android.art/lib/libart.so _ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc
>       #11: 3695570  /apex/com.android.art/lib/libart.so _ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE
>       #12: 3647247  /apex/com.android.art/lib/libart.so _ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE
>       #13: 8007318  /apex/com.android.art/lib/libart.so MterpInvokeInterface
>       #14: 1268130  /apex/com.android.art/lib/libart.so 
>       #15: 8012367  /apex/com.android.art/lib/libart.so MterpInvokeDirect
>       #16: 1267874  /apex/com.android.art/lib/libart.so 
>       #17: 8012367  /apex/com.android.art/lib/libart.so MterpInvokeDirect
>       #18: 1267874  /apex/com.android.art/lib/libart.so 
>       #19: 3602387  /apex/com.android.art/lib/libart.so 
>     
>         at com.yandex.mapkit.internal.MapKitBinding.createMapWindow(Native Method)
>         at com.yandex.mapkit.mapview.MapView.init(MapView.java:59)
>         at com.yandex.mapkit.mapview.MapView.<init>(MapView.java:54)
>         at com.yandex.mapkit.mapview.MapView.<init>(MapView.java:44)
>         	... 28 more
> 
>

**Comment by dmz9** [comment]
аналогичные симптомы были на одном из проектов.
обновил студию с 3.6 до 4.0, обновился градл, и сборка пожаловалась ошибкой что старый крашлитик сдк от fabric умрёт, и надо его поменять на новый файрбейз крашлитик.

пока его настраивал столкнулся с ошибкой дубликатов классов из пакета com.google.android.gms
свежий фб крашлитик начинается от 17.0.0+ а мапкит опирается все еще на древние сдк версий 11.6.2 и в итоге ничего не собирается.

попытался вырезать старый com.google.android.gms целиком из билда через 

```groovy
api ("com.yandex.android:mapkit:$yandex_maps_version") {
        exclude group: 'com.google.android.gms'
}
```

билд стал собираться (build apk), и мог закачиваться на устройство, но в рантайме карты падают именно с такой ошибкой как в посте, откуда то из нативной библиотеки.

если не вырезать com.google.android.gms то build apk не собирается из за ошибки с дубликатами, однако на устройство всетаки приложение ставится из студии и карта там нормально работает.

в конце концов сделал уточнение такое:
```groovy
api ("com.yandex.android:mapkit:$yandex_maps_version") {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
}
```
на первый взгляд всё работает - и билдится и карты не падают в рантайме, т.е. "дымный тест" проходит.
как в дальнейшем себя поведет в использовании - непонятно (

**Comment by imosmanyilmaz** [comment]
You need to set Api key and initialize before the "setContentView"
  
MapKitFactory.setApiKey(MAPKIT_API_KEY);
MapKitFactory.initialize(this);
setContentView(R.layout.activity_maps);
