### ISSUE TITLE
Возможно ли изменить позицию логотипа

### ISSUE THREAD

**Issue by kostyanchikoff** [yandex/mapkit-android-demo#208]
Проблема в том что у нас полуоткрытый BottomSheetBehevior без возможности закрыть, тем самым он перекрывает логотип карты, как поменять позиция с нижнего угла в верхний?

**Comment by Bamboo-KuSu** [comment]
Попробуй примерно так `mapView.map.logo.setAlignment(Alignment(HorizontalAlignment.RIGHT, VerticalAlignment.TOP))`

**Comment by kostyanchikoff** [comment]
> Попробуй примерно так `mapView.map.logo.setAlignment(Alignment(HorizontalAlignment.RIGHT, VerticalAlignment.TOP))`

Спасибо! Сразу еще вопрос) можно ли абсолютные значение задавать?

**Comment by darkeneez** [comment]
К сожалению нет

**Comment by svshishkina** [comment]
@kostyanchikoff удалось как-то решить этот вопрос? У нас такая же ситуация с BottomSheet. Наверх перенести не можем, так как карта под статус баром.
