### ISSUE TITLE
Как реализовать простую карту показывающая один балун на адресе  по координату

### ISSUE THREAD

**Issue by SamQypshak** [yandex/mapkit-android-demo#210]
Добрый день

Не смог найти простой пример как реализовать простую карту показывающая один балун на адресе  по координату.
Если не будет сложно отправьте пример когда с пояснением

**Comment by eaniconer** [comment]
Добрый день.

Не совсем понял, что это значит "показывающая один балун на адресе по координату". 

Но если известны координаты, то можно получить `MapObjectCollection` у карты с помощью метода [`getMapObjects`](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_getMapObjects), а потом добавить в эту коллекцию плейсмарку c помощью [`addPlacemark`](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/MapObjectCollection-docpage/#method_detail__method_addPlacemark___NonNullPoint___NonNullImageProvider)
