### ISSUE TITLE
Градиентная полилиния по координатам

### ISSUE THREAD

**Issue by mfperminov** [yandex/mapkit-android-demo#212]
Возможно ли как-то решить задачу средствами фреймворка: имеется набор точек, каждой из которых соотвествует цвет. Необходимо построить полилинию с градиентным переходом цвета от точки к точке, градиент на всю длину отрезка линии.
Использую mapkit версии 3.4.0

**Comment by eberkovich** [comment]
Для этого нужно воспользоваться [ColoredPolylineMapObject](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/ColoredPolylineMapObject-docpage/).
Он как раз позволяет рисовать разноцветную линию с градиентом.
