### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by brlz0r** [yandex/mapkit-android-demo#217]
This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.core:core:1.3.1, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.fragment:fragment:1.1.0, androidx.appcompat:appcompat:1.2.0, androidx.constraintlayout:constraintlayout-solver:2.0.1, androidx.customview:customview:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.activity:activity:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.0.0, androidx.annotation:annotation:1.1.0, androidx.constraintlayout:constraintlayout:2.0.1, androidx.appcompat:appcompat-resources:1.2.0, androidx.lifecycle:lifecycle-common:2.1.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.1.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.1.0, androidx.lifecycle:lifecycle-runtime:2.1.0, androidx.vectordrawable:vectordrawable:1.1.0
Affected Modules: mapkit-android-demo 
Такая проблема

**Comment by maxglu** [comment]
У меня точно такая-же проблема. Что, впрочем, не удивительно.
@brlz0r у ребят из Яндекса все .properties файлы в гит-игнор добавлены, соответсвенно файла конфигурации для проекта тоже нет.  
Просто положите в корень проекта файл с именем gradle.properties и строками
`android.useAndroidX=true 
android.enableJetifier=true`

И все должно заработать.
