### ISSUE TITLE
AssertionError with gradle 6.7 and classpath gradle 4.1

### ISSUE THREAD

**Issue by qavan** [yandex/mapkit-android-demo#219]
Got `java.lang.AssertionError: setApiKey() should be called before initialize()!`

but my initializing:

```
override fun onPreCreate() {
        super.onPreCreate()
        MapKitFactory.setApiKey(mapApiKey)
        MapKitFactory.initialize(this)
}
```

???

```
classpath 'com.android.tools.build:gradle:4.1.0'
```

```
            mapkit                  : "com.yandex.android:mapkit:3.5.0",
            directions              : "com.yandex.android:directions:3.5.0",
```

```classpath 'com.android.tools.build:gradle:4.0.2``` solves problem
Also in project used 17.2.2 version of crashlytics(+ndk)

**Comment by imosmanyilmaz** [comment]
Set your api key in your singleton Application class 


public class MyApplication extends Application {
    private static MyApplication mInstance;
    final String MAPKIT_API_KEY = "";
    @Override
    public void onCreate() {
        super.onCreate();
        mInstance = this;
        MapKitFactory.setApiKey(MAPKIT_API_KEY);
  
    }
    public static synchronized MyApplication getInstance() {
        return mInstance;
    }


}

**Comment by serzhan76** [comment]
Спасибо мне помогло

**Comment by ma3x-rus** [comment]
подскажите пожалуйста куда вставлять этот код и сам API ключ от яндекса? всё перепробовал, падает приложение при попытке обновить изменения

**Comment by YandexMapKit** [comment]
Подробная инструкция по инициализации карты есть в [документации](https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html). Посмотрите, пожалуйста.

**Comment by suhrobbek01** [comment]
> Set your api key in your singleton Application class
> 
> public class MyApplication extends Application { private static MyApplication mInstance; final String MAPKIT_API_KEY = ""; @OverRide public void onCreate() { super.onCreate(); mInstance = this; MapKitFactory.setApiKey(MAPKIT_API_KEY); } public static synchronized MyApplication getInstance() { return mInstance; }
> 
> }

Спасибо, мне тоже помогло

**Comment by suhrobbek01** [comment]
Спасибо, мне тоже помогло
