### ISSUE TITLE
Кратковременное исчезновение маркера местоположения после onStart 

### ISSUE THREAD

**Issue by Foxek** [yandex/mapkit-android-demo#220]
Всем привет.

Маркер местоположения пользователя исчезает на некоторое время после сворачивания/разворачивания приложения (см. прикрепленное видео). Помимо этого проскакивает кейс, когда при разворачивании приложения маркер виден и только через какой-то промежуток времени он исчезает, после чего снова появляется.

Попробовал несколько разных примеров, в том числе и ваш базовый пример. Прикрепленное видео записано на [этом примере](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/UserLocationActivity.java)

Выглядит подобное поведение не очень. Насколько это адекватное поведение и можно ли это как-то исправить?

![yandex marker bug](https://user-images.githubusercontent.com/44055463/97972830-2f609e00-1dd6-11eb-83ef-b2fc7ccbb4b6.gif)

**Comment by Shlyankin** [comment]
Такая же проблема. Постоянно то появляется, то исчезает этот маркер. Код аналогичен. Проще самостоятельно проставлять этот маркер, по-моему.
