### ISSUE TITLE
setApiKey() should be called before initialize()!

### ISSUE THREAD

**Issue by AdislanSaidov** [yandex/mapkit-android-demo#221]
Инициализирую таким образом
`
override fun onCreate(savedInstanceState: Bundle?) {
        MapKitFactory.setApiKey("my api key")
        super.onCreate(savedInstanceState)
        MapKitFactory.initialize(this)
...
}
`
Крашится на эмуляторах Pixel API 30 и Pixel C API 29.
Совет добавить 
`
defaultConfig {
   ndk {
            abiFilters("armeabi-v7a", "x86")
        }
}
` не помог

**Comment by qavan** [comment]
Откат градла не пробовал #219?

**Comment by vitalyleon** [comment]
Попробуй вынести `MapKitFactory.setApiKey("my api key")` в твой `Application`

**Comment by AdislanSaidov** [comment]
> Откат градла не пробовал #219?

Помогло, спасибо!

**Comment by ikucharov** [comment]
Not working MapKitInitializer.initialize reopen activity and offline  mode? how to fixed it

**Comment by RusArtm** [comment]
It is really strange there is no way to check if the MapKit was already initialized.
Checking instance causes error.

**Comment by Soliardi-Chyngyz** [comment]
> Попробуй вынести `MapKitFactory.setApiKey("my api key")` в `Application`

pls demonstrate full code
