### ISSUE TITLE
onObjectTap получить информацию

### ISSUE THREAD

**Issue by brlz0r** [yandex/mapkit-android-demo#222]
С помощью onObjectTap получаю GeoObject, и как получить иконку GeoObject на которую нажал юзер и информацию о GeoObject (Типа супермаркет или фастфуд).

**Comment by eberkovich** [comment]
Возможности получить иконку нет.

Тип объекта можно узнать с помощью тегов, теги приходят в классе [GeoObjectTags](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/GeoObjectTags.html/):

```
GeoObjectTags geoObjectTags = geoObjectTapEvent.getGeoObject().
    getMetadataContainer().getItem(GeoObjectTags.class);
if (geoObjectTags != null) {
    //test tags 
}
```

супермаркеты помечены тегом: "shopping".
фастфуд, кафе и рестораны тегом: "food_and_drink".

**Comment by brlz0r** [comment]
Только почему то, если я делаю geoObjectTags.getTags().get(1), то при выборе простых мест с фастфудом например всё ок, а выборе например муниципальных объектов, приложение вылитает

**Comment by eberkovich** [comment]
Возможно в списке возвращаемом getTags() недостаточно элементов?
