### ISSUE TITLE
как найти дистанцию между объектами? 

### ISSUE THREAD

**Issue by Anemona19** [yandex/mapkit-android-demo#224]
Делаю навигационное приложение, не могу найти как узнать дистанцию/расстояние между объектами. Есть ли вообще такая функция?

**Comment by Mikhail57** [comment]
В Android-фреймворке есть функциz нахождения расстояния между объектами по гаверсинусу (haversine) — расстояние «по-прямой». Если необходимо получить маршрут по дорогам, то нужно приобрести полную версию MapKit и воспользоваться пакетом `com.yandex.mapkit.directions`
