### ISSUE TITLE
mapkit построение маршрута на  андроиде

### ISSUE THREAD

**Issue by islamasylbekov** [yandex/mapkit-android-demo#225]
У меня есть карта от yandex на мобилке. Я построил маршрут но когда обьект движется маршрут тоже должен двигаться. Я не мог сделать это. Делал через Timer() чтобы он каждый 10 секунд отправил запрос с новыми данными но это не работает. И пробовал привязать карту на UserLocation тоже не получилось. Есть ли среди вас кто работал с Yandex Mapkit на андроиде. С докментацией все плохо и информации очень мало.
Можете предлагать любой вариант.
И еше один вопрос в  мапките есть функционал который работает когда userLokation меняет место.

**Comment by YandexMapKit** [comment]
Отслеживание объекта в реальном времени требует приобретения [коммерческой лицензии](https://yandex.ru/dev/maps/mapkit/doc/intro/concepts/enterprise.html?from=mapkit#enterprise__tariffs). 
Это указано в [условиях использования Mapkit](https://yandex.ru/dev/maps/mapkit/doc/intro/concepts/conditions.html).
