### ISSUE TITLE
Add user guides for main features

### ISSUE THREAD

**Issue by Mikhail57** [yandex/mapkit-android-demo#226]
When I started using Yandex.MapKit on Android I faced a problem: lack of user guides for developers on the main features of the library. The quick start guide is very limited. May you add some guides (with tips-and-tricks, pls) for:
- Adding markers
- Clustering (with an explanation of magic numbers in the `clusterPlacemarks` with screenshots)
- Zooming (programmatically)
- User Location handling without maps displaying
- User Location Layer customiztion
- MapView in the Fragment
- MapView camera position restoration

This will speed up developers and help them.

Google Maps Android SDK has great user guides available on the https://developers.google.com/maps/documentation/android-sdk/ with localization for foreign developers and well-formed tutorials for beginners covering starter topics

**Comment by YandexMapKit** [comment]
Unfortunately, our service does not offer this feature at the moment. I'll forward your request to the developers. They'll review it and, if possible, implement it in future versions of the service. 

Thank you for helping us improve our service!

**Comment by YandexMapKit** [comment]
We have updated the documentation and demo application for most of the questions you requested. Please take a look!
