### ISSUE TITLE
how to clear drawn placemarks and routes from the map.

### ISSUE THREAD

**Issue by farrukht** [yandex/mapkit-android-demo#227]
I have a map in y app where I need to show the route to destination A from to destination B . and the car/person that is moving on this route. on first load i am using mapobject.addplacemark(). it is working fine. after some second I want to update the person's location so I load the new coordinate and now I want to remove the route and placemark that was placed before. I tried to use mapobject.clear() it says it removes all map objects. but after this function, i can no longer add new objects. it is showing error as follows

Native object's weak_ptr for N6yandex4maps6mapkit3map9MapObjectE has expired

can anybody help with this error?

**Comment by TheMrButcher** [comment]
It seems that you are using dead map objects which you removed using mapobject.clear(). clear() destroys all map objects in collection, so any references to these objects in your app are dead and must not be used.
