### ISSUE TITLE
Выделение региона на карте

### ISSUE THREAD

**Issue by mitskovets** [yandex/mapkit-android-demo#229]
Есть ли метод, позволяющий выделить область на карте или регион, например Москва или область. Как это делается в веб. 
![map](https://user-images.githubusercontent.com/6792881/104167844-1a277180-540e-11eb-9b77-a66c705fa35f.jpg)
Спасибо.

**Comment by elricbk** [comment]
Здесь есть две подзадачи:

* получить откуда-то геометрию нужной области
* добавить эту геометрию на карту

Вторая задача решается с помощью `PolygonMapObject`. Первую можно решать по-разному. Можно, например, так:

* в нужной точке нужно сделать обратный поиск с опциями, где будет `SearchType.GEO` и `setGeometry`
* в списке результатов нужно выбрать результат с нужным `Address.Component.Kind` (для Москвы и области это будут `LOCALITY` или `PROVINCE`)
* для выбранного результата найти в списке геометрий все геометрии, в которых есть полигон
