### ISSUE TITLE
Polyline objects aren't shown

### ISSUE THREAD

**Issue by rzhaxibayev** [yandex/mapkit-android-demo#23]
I use class Polyline to draw lines on a map.
The problem is that lines are shown on map only if I put
- dontobfuscate in proguard-rules.pro.

Tried to add these lines in proguard file, but didn't help:
-keep class com.yandex.mapkit.** { *; }
-dontwarn com.yandex.mapkit.**

**Comment by IUdalov** [comment]
Hi Rauan!
MapKit has this rules embedded in .aar. And pro guard should automatically inherit them.
You probably have broken build scripts.
