### ISSUE TITLE
Слушатель координат

### ISSUE THREAD

**Issue by lenchikspirdonchik** [yandex/mapkit-android-demo#230]
Добрый день.  Хотел бы добавить слушателя на карту - пользователь нажимает на карту, слушатель считывает координаты. В сети гуляет много примеров, но чет они все старые и не рабочие( 
помогите пожалуйста?)
Также. может кто подскажет - как сделать подсказку, которая появляется по нажатию на метку?  в гугловской карте все просто, hint добавляешь и все))

**Comment by eberkovich** [comment]
Добрый день,

- Для получения координат нужно: повесить обработчик нажатия на карту с помощью: [Map.addInputListener](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/Map.html#_35), в методе onMapTap придут географические координаты точки нажатия.

- Для добавления подсказки нужно повесить обработчик нажатия на PlacemarkMapObject с помощью: [MapObject.addTapListener](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObject.html#_14) и в реализации совершить необходимые действия: изменить иконку или задать платформенную view в качестве содержимого PlacemarkMapObject или показать платформенную view средствами android sdk. Примеры работы с мап объектами можно посмотреть [здесь](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java).

Так же пожалуйста обратите внимание на эту [рекомендацию](https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html#quickstart__work).
