### ISSUE TITLE
Работа с Masstransit Router

### ISSUE THREAD

**Issue by shakhzodbek-i** [yandex/mapkit-android-demo#231]
Как можно нарисовать путь одной определенной транспортной линии? Если ли возможность запросить целую транспортную линию в виде Geometry/Segment/Polyline? К примеру, в web версии API есть возможность запросить всю линию целиком и отрисовать.

Заранее спасибо за ответ!

**Comment by shakhzodbek-i** [comment]
Я так понял разрабы забили на Issues и довольно давно перестали отвечать на вопросы..

**Comment by YandexMapKit** [comment]
На карту можно добавлять полилинии - у [MapObjectCollection](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/MapObjectCollection.html) есть метод [addPolyline](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/MapObjectCollection.html#addPolyline-com.yandex.mapkit.geometry.Polyline-). MapObjectCollection можно получить из [Map.getMapObjects](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/Map.html#getMapObjects--).
