### ISSUE TITLE
Шаблон маркера 

### ISSUE THREAD

**Issue by Je-Hunter** [yandex/mapkit-android-demo#232]
Добрый день.
Подскажите возможно ли на андроиде в mapkit добавлять маркеры по шаблону как в JavaScript API

![изображение](https://user-images.githubusercontent.com/18631863/105824747-96aa7a80-5fe0-11eb-832b-51c5370da0e8.png)

**Comment by TheMrButcher** [comment]
Можно через CompositeIcon добавить несколько картинок. Либо через setView отрендерить небольшую вьюху в качестве иконки.

**Comment by ng-designs** [comment]
> Можно через CompositeIcon добавить несколько картинок. Либо через setView отрендерить небольшую вьюху в качестве иконки.

а можно пример?

**Comment by YandexMapKit** [comment]
С описанием метода **CompositeIcon** можете ознакомиться в этом разделе [документации](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/CompositeIcon.html?lang=ru). По **setView** подробнее можно прочитать в [справке](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/PlacemarkMapObject.html?lang=ru).
