### ISSUE TITLE
Как показывать info window

### ISSUE THREAD

**Issue by public8oid** [yandex/mapkit-android-demo#233]
Добрый день.
Существует ли в мап ките возможность показывать info window? И можно ли анимировать его? 
Можно ли добиться такого поведения, как на скриншоте?
![photo_2021-01-28_15-00-39](https://user-images.githubusercontent.com/78144329/106121663-9db8c080-6179-11eb-932a-cfed7edac462.jpg)

**Comment by eberkovich** [comment]
Здравствуйте,
Можно с помощью ViewProvider.
Вот [пример](https://github.com/yandex/mapkit-android-demo/blob/dcfa1d62171f51dbb7e076c623177091ff4551ef/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L195).
Нужно иметь ввиду,  что PlacemarkMapObject использует snapshot view, по этому анимации придется реализовывать вручную: так же как в примере.
