### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by v-grishechko** [yandex/mapkit-android-demo#234]
Hi. 
We experience a crash on some devices due to absent corresponding .so library.
**Full logs**:

>  Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load maps-mobile, reason: lib/armeabi/libmaps-mobile.so
       at com.yandex.runtime.Runtime.loadLibrary(Runtime.java:123)
       at com.yandex.runtime.Runtime.init(Runtime.java:96)
       at com.yandex.runtime.Runtime.init(Runtime.java:103)
       at com.yandex.mapkit.MapKitFactory.initialize(MapKitFactory.java:25)
       at com.yandex.mapkit.search.SearchFactory.initialize(SearchFactory.java:12)
       at com.example.app.initializer.ProcessDependentInitializer.setUpYandexMapKit(ProcessDependentInitializer.java:125)
       at com.example.app.initializer.ProcessDependentInitializer.initializeProcessDependentComponents(ProcessDependentInitializer.java:65)
       at com.example.app.initializer.ProcessDependentInitializer.initialize(ProcessDependentInitializer.java:50)
       at com.example.app.MApplication.onCreate(MApplication.java:67)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4980)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1562)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:692)
       
**Libs versions**:
```groovy  
mapkit          : "com.yandex.android:maps.mobile:4.0.0-full",
search          : "com.yandex.android:search:3.5.0",
oauth           : "com.yandex.android:authsdk:2.0.0"
 ```
 
 **Firebase crash statistics of devices**:

<img src="https://user-images.githubusercontent.com/5684695/107387521-f5eeab80-6b05-11eb-85de-3fd496d1c340.png" width=300/>

How we can fix it or just wait future library update?

**Comment by v-grishechko** [comment]
@eberkovich 
Hi. Any response?)

**Comment by v-grishechko** [comment]
@eberkovich 
Soft reminder, some users can't start our app. Maybe I need to add more info about the crash?

**Comment by TheMrButcher** [comment]
lib/armeabi/libmaps-mobile.so is a armv7 (32-bit version) of library. Did you include this arch and corresponding version of lib in your app?

**Comment by TheMrButcher** [comment]
Galaxy A5 is an armv7 device.

**Comment by v-grishechko** [comment]
@TheMrButcher  We deploy the bundle on google play. But if build debug apk, there no .so library by this path (**lib/armeabi/libmaps-mobile.so**):
![image](https://user-images.githubusercontent.com/5684695/108967162-3155b200-7690-11eb-89c2-550f1103ae45.png)

Also, we don't have some special configuration for splitting and filtering ABI in Gradle configs

**Comment by v-grishechko** [comment]
@TheMrButcher Hi. Some updates about this bug? )

**Comment by TheMrButcher** [comment]
"we don't have some special configuration for splitting and filtering ABI in Gradle configs" May be that is the problem. Please can you manually specify these 4 archs in abiFilters?

**Comment by v-grishechko** [comment]
@TheMrButcher 
I've analyzed apk, which user with problematic device receives from google play and there found this library:
![image](https://user-images.githubusercontent.com/5684695/110778525-84745b00-8273-11eb-8f7c-169e3ea9d421.png)

It means that the user already have the correct ABI lib, but despite this crash happens. I can send a list of devices on which the crash occurs. May be it can help reproduce this crash.

**Comment by TheMrButcher** [comment]
AFAIK armeabi and armeabi-v7a are not the same. We do not compile MapKit for armeabi, only for armeabi-v7a. I think that on some devices ReLinker tries to load armeabi version because abi filters are not specified and all archs are allowed.

**Comment by v-grishechko** [comment]
@TheMrButcher And how to solve this issue? Can you compile armeabi version?

**Comment by bigman212** [comment]
I've encountered this issue too. 
Most crashes on:
- Android 7, Android 8
- ONEPLUS A5000, SAMSUNG A5, SAMSUNG A3, HUAWEI Y3III

We create bundles for Google Play, and APKs for AppGallery.
Version com.yandex.android:maps.mobile:4.0.0-lite

Any updates on the issue? @TheMrButcher

**Comment by beibuttukibayev** [comment]
We have the same issue for 4.0.0-full most commonly on Huawei and Samsung devices (Android 7, 8, 9)
Any updates on the issue? @TheMrButcher

**Comment by vkatzyn** [comment]
Seeing this crash in our app using 4.1.0-full version
Here's a list of devices and their OS versions that got this crash in the recent couple of months, hope that's useful
<img width="389" alt="image" src="https://user-images.githubusercontent.com/8245028/205893956-449bf224-6da8-4fd5-bc7a-37d9dd3b7b80.png">

**Comment by PStrelchenko** [comment]
Also seeing this crash in our app using `com.yandex.android:maps.mobile:4.2.1-lite`.

We use `App Bundle` for our app distribution. Our setup for it in convention plugin is:

```kotlin
import com.android.build.gradle.BaseExtension

@Suppress("UnstableApiUsage")  
fun BaseAppModuleExtension.setupAppBundle() {  
    bundle {  
        language {  
            enableSplit = true  
        }  
        density {  
            enableSplit = true  
        }  
        abi {  
            enableSplit = true  
        }  
    }
}
```

Don't sure why (we are kinda a desperate people about this crash 😔) but we add also the following block into `defaultConfig`:

```kotlin
import com.android.build.gradle.internal.dsl.BaseAppModuleExtension

@Suppress("UnstableApiUsage")  
fun BaseAppModuleExtension.setupSupportedAbi() {  
    defaultConfig {  
		ndk {  
			abiFilters.addAll(  
				listOf(  
					"arm64-v8a",  
					"armeabi-v7a",  
					"x86",  
					"x86_64"  
				)  
			)  
		}  
	} 
}
```

Anyway, we have a lot of crashes among our users, with different devices and different ABI. Hope this information help:

<table>
	<thead>
		<th>Model</th>
		<th>OS version</th>
		<th>Supported ABI</th>
	</thead>
	<tbody>
		<tr>
			<td>Aosp On IA Emulator</td>
			<td>7.0</td>
			<td>x86, armeabi-v7a, armeabi</td>
		</tr>
		<tr>
			<td>Nexus 5X</td>
			<td>8.1.0</td>
			<td>x86</td>
		</tr>
		<tr>
			<td>Nexus 5X</td>
			<td>6.0.1</td>
			<td>armeabi-v7a, armeabi, x86</td>
		</tr>
		<tr>
			<td>真我 GT NEO 3</td>
			<td>13</td>
			<td>arm64-v8a, armeabi-v7a, armeabi</td>
		</tr>
		<tr>
			<td>Redmi Note 9S</td>
			<td>12</td>
			<td>arm64-v8a, armeabi-v7a, armeabi</td>
		</tr>
		<tr>
			<td>Poco F3</td>
			<td>13</td>
			<td>arm64-v8a, armeabi-v7a, armeabi</td>
		</tr>
		<tr>
			<td>V2061</td>
			<td>12</td>
			<td>arm64-v8a, armeabi-v7a, armeabi</td>
		</tr>
	</tbody>
</table>

How do we get supported ABI list:

```kotlin
import android.os.Build
import android.content.Context

@Suppress("DEPRECATION")  
fun Context.getSupportedAbis(): Array<String> {  
    return when {  
        Build.SUPPORTED_ABIS.isNotEmpty() -> Build.SUPPORTED_ABIS  
        Build.CPU_ABI2.isNotEmpty() -> arrayOf(Build.CPU_ABI, Build.CPU_ABI2)  
        else -> arrayOf(Build.CPU_ABI)  
    }  
}
```

Also some information without ABI info (we did not think to collect this information from the beggining):

- Affected models:
	- Samsungs
		- Galaxy J6+
		- Galaxy S22
		- Galaxy A51
		- Galaxy A8+(2018)
		- Galaxy S20 Ultra 5G
		- Galaxy M12
		- Galaxy A53 5G
		- Galaxy M31s
	- Xiaomi
		- Redmi 9T
		- Redmi 7
		- Redmi 9A
		- Redmi Note 10S
		- Redmi Note 10 Pro
		- Redmi 10 2022
		- Poco X3 Pro
		- Redmi Note 9S
	- Honor
		- Honor 50
		- Honor X8
		- Honor 50 Lite
		- Honor 70
		- Honor X8a
	- Oppo
		- Realme C35
		- RMX3231
		- Realme 9
		- Realme 10
		- Realme 6Pro
		- Realme XT
- Affected OS versions:
	- Android 6 --> Android 13 (all supported versions of our app)
- Devices states: foreground 99%

Hope this could help you anyhow. 

May be you have some assumptions, where should we dig more information about this crash, how to fix it?

**Comment by ilyastoletov** [comment]
There is still same issue on `com.yandex.android:maps.mobile:4.4.0-lite`

Devices affected:
- Oppo Realme RMX3771
- OnePlus 8 PRO

Tried different solutions, but none of them helped.

**Comment by YandexMapKit** [comment]
If you can, send us a minimal compiled example, that demonstrates the situation. It can be uploaded on [GitHub](https://github.com/), attached to mail as an archive, or uploaded to [Yandex Disk](https://disk.yandex.com/) and sent to us via link.

We will try to find a solution.

**Comment by Arkuda** [comment]
Hi all, same problem, affects android 13 and 14. Using aab.  Lib ver - 4.0.0-full
Devices: 

- Samsung Galaxy S21 5G
- Samsung Galaxy A54 5G
- Poco X5 
- Xiaomi Redmi 12 5G

**Comment by YandexMapKit** [comment]
We still need a minimal example of the application code, which we can assemble to reproduce the situation in our environment.

**Comment by HrayrHovsepyan** [comment]
same issue from me com.yandex.android:maps.mobile:4.4.0-lite

Devices affected: Xiaomi 11T android14

**Comment by YandexMapKit** [comment]
Здравствуйте, @Kratos1013!

Нам очень поможет свежий пример проекта, который позволит наглядно воспроизвести ошибку. Пожалуйста, оформите его и загрузите на любой удобный файлообменник. В том числе можно загрузить проект в GitHub и прислать на него ссылку.

**Comment by YandexMapKit** [comment]
Мы не можем воспроизвести и отловить описанную проблему без минимального примера кода, на котором такую ошибку с достаточной степенью стабильности можно было бы получить. Пожалуйста, соберите подобный пример и выложите его проектом на [GitHub](https://github.com/) или ссылкой на архив в [Яндекс Диске](https://disk.yandex.ru/) или ином хранилище.

**Comment by romankulykov** [comment]
Ошибка при загрузке нативной библиотеки на Android 15 (API 35)

Описание проблемы:
При попытке инициализации Yandex Maps SDK на устройстве с Android 15 (API 35) возникает ошибка загрузки нативной библиотеки. Эта проблема воспроизводится как в существующем проекте, так и в новом чистом проекте.

Сообщение об ошибке:
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~4NMPv6xgUj1ehLsaZbtDLg==/dev.roman.testyandexmapapp-5IA02AuBIbY54AQm9XM7cQ==/base.apk!/lib/arm64-v8a/libmaps-mobile.so" (new hash type from the future?)

Шаги для воспроизведения:
1. Создать новый проект Android
2. Добавить зависимость Yandex Maps SDK (версия 4.8.0-lite)
3. Инициализировать MapKit в коде
4. Запустить приложение на устройстве или эмуляторе с Android 15 (API 35)

Ожидаемое поведение:
SDK должен успешно инициализироваться без ошибок.

Фактическое поведение:
Приложение крашится с ошибкой UnsatisfiedLinkError при попытке загрузить нативную библиотеку.

Дополнительная информация:
- Версия Yandex Maps SDK: 4.8.0-lite
- Версия Android: 15 (API 35)
- Устройство: Эмулятор Android (Resizable Experimental API 35)

Характеристики эмулятора:
- Имя: Resizable (Experimental) API 35
- AvdId: Resizable_Experimental_API_35
- Производитель: Generic
- Имя устройства: resizable
- Разрешение экрана: 1080x2400
- Плотность экрана: 420 dpi
- RAM: 2048 MB
- CPU: 4 ядра
- GPU: включен, режим auto
- Архитектура: arm64-v8a
- Версия API: 35
- Тип системного образа: Google APIs (16 KB Page Size) (ЭТО ВАЖНО!!!)

Прошу рассмотреть этот вопрос и предоставить решение или обходной путь для использования SDK на Android 15.

Ссылка на проект: https://github.com/romankulykov/TestYandexMapApp/tree/main

@YandexMapKit Please take a look ASAP. Thanks!

**Comment by YandexMapKit** [comment]
Сейчас MapKit не поддерживает 16 КБ страницы.
Мы рассмотрим возможность добавления такой поддержки в будущих версиях. Каких-либо сроков такой доработки пока назвать не сможем.

**Comment by georrge1994** [comment]
Правильно, проблема на "нашей стороне". На вашей ей метрики и закрытые таски.
