### ISSUE TITLE
Использование MultiPolygon

### ISSUE THREAD

**Issue by ilya842** [yandex/mapkit-android-demo#235]
Здравствуйте! Не совсем понял как добавлять [MultiPolygon](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/geometry/MultiPolygon.html) на карту, созданный вручную. В объекте [MapObjectCollection](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObjectCollection.html) отсутствует метод для добавления MultiPolygon. В демо версии тоже не нашел примеров его использования. 

Вопрос: как правильно выводить вручную созданный MultiPolygon и есть вообще сейчас такая возможность?

**Comment by eberkovich** [comment]
Здравствуйте, 

Каждый Polygon входящий в MultiPolygon нужно добавить как отдельный PolygonMapObject с помощью [MapObjectCollection.addPolygon()](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObjectCollection.html#_18)
