### ISSUE TITLE
Анимация клстеризации пинов на карте 

### ISSUE THREAD

**Issue by donik** [yandex/mapkit-android-demo#236]
collection.clusterPlacemarks(withClusterRadius: 60, minZoom: 15)

при добавлении новых точек обновляя кластеризацию пины начинают появляться с анимацией даже если они уже есть внутри кластера. Есть ли возможность отключить анимацию появления?

**Comment by DemaFay** [comment]
Привет. У меня такая же проблема. Не удалось решить?

**Comment by donik** [comment]
Я написал в поддержку, служба отвечает разрабы нет 🤣

Чт, 4 марта 2021 г. в 16:52, DemaDayz <notifications@github.com>:

**Comment by donik** [comment]
Можешь написать мне в телегу буду в курсе держать @donik102

Чт, 4 марта 2021 г. в 17:01, Don Karleone <donik102@gmail.com>:

**Comment by cream-cheeze** [comment]
Невозможно кластерами пользоваться - всё моргает как новогодняя ёлка!

**Comment by cream-cheeze** [comment]
Вон [такой же issue ](https://github.com/yandex/mapkit-android-demo/issues/190) аж с 2020 года висит...

**Comment by donik** [comment]
> Привет. У меня такая же проблема. Не удалось решить?

я решил проблему костылём 

 fun updateItems(newItems: List<ChargingStation>) {
        val newCollection =
            this.mapView.mapWindow.map.mapObjects.addClusterizedPlacemarkCollection(this)

        for (item in newItems) {
            val marker = newCollection.addPlacemark(
                Point(
                    item.location.getLocation().latitude,
                    item.location.getLocation().longitude
                ),
                ImageProvider.fromBitmap(
                    if (item.type == "info") {
                        infoIconMarker?.toBitmap()
                    } else {
                        iconMarker?.toBitmap()
                    }
                ),
                IconStyle(
                    PointF(0.5f, 0.5f),
                    RotationType.ROTATE,
                    1.0f,
                    true,
                    true,
                    1.0f,
                    null
                )
            )
            marker.userData = item
            marker.addTapListener(this)
        }

        newCollection.clusterPlacemarks(40.0, 12)
        newCollection.setVisible(false, Animation(Animation.Type.LINEAR, 0.0f), null)

        val weakSelf by weak(this)
        UIKit.post({
            val strongSelf = weakSelf ?: return@post
            try {
                strongSelf.mapView.mapWindow.map.mapObjects.remove(strongSelf.collection)
            } catch (_: Exception) {
            }

            strongSelf.collection = newCollection
            newCollection.setVisible(true, Animation(Animation.Type.LINEAR, 0.0f), null)
        }, 300)
    }

создал новую коллекцию, добавил на карту и после тайм-аута отобразиил

в айосе все аналогично

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.


2021-11-16 18:18:25, donik <devnull@yandex.ru>:
>> Привет. У меня такая же проблема. Не удалось решить?
> 
> я решил проблему костылём 
> 
> ```
>  fun updateItems(newItems: List<ChargingStation>) {
>         val newCollection =
>             this.mapView.mapWindow.map.mapObjects.addClusterizedPlacemarkCollection(this)
> 
>         for (item in newItems) {
>             val marker = newCollection.addPlacemark(
>                 Point(
>                     item.location.getLocation().latitude,
>                     item.location.getLocation().longitude
>                 ),
>                 ImageProvider.fromBitmap(
>                     if (item.type == "info") {
>                         infoIconMarker?.toBitmap()
>                     } else {
>                         iconMarker?.toBitmap()
>                     }
>                 ),
>                 IconStyle(
>                     PointF(0.5f, 0.5f),
>                     RotationType.ROTATE,
>                     1.0f,
>                     true,
>                     true,
>                     1.0f,
>                     null
>                 )
>             )
>             marker.userData = item
>             marker.addTapListener(this)
>         }
> 
>         newCollection.clusterPlacemarks(40.0, 12)
>         newCollection.setVisible(false, Animation(Animation.Type.LINEAR, 0.0f), null)
> 
>         val weakSelf by weak(this)
>         UIKit.post({
>             val strongSelf = weakSelf ?: return@post
>             try {
>                 strongSelf.mapView.mapWindow.map.mapObjects.remove(strongSelf.collection)
>             } catch (_: Exception) {
>             }
> 
>             strongSelf.collection = newCollection
>             newCollection.setVisible(true, Animation(Animation.Type.LINEAR, 0.0f), null)
>         }, 300)
>     }
> ```
> 
> создал новую коллекцию, добавил на карту и после тайм-аута отобразиил
> 
> в айосе все аналогично

**Comment by YandexMapKit** [comment]
Текущая реализация кластеризации объектов в MapKit SDK в ближайших релизах будет помечена как deprecated и больше не будет поддерживаться и разрабатываться. Мы планируем реализовать новый подход для сценария кластеризации. Пожалуйста, следите за обновлениями нашей библиотеки.

**Comment by rendivy** [comment]
Привет! Прошло достаточно много времени. Подскажите, получилось решить проблему?
