### ISSUE TITLE
Нажатие на карту, не могу найти в документации

### ISSUE THREAD

**Issue by invweb** [yandex/mapkit-android-demo#237]
Здравствуйте. Хочу чтобы вы мне объяснили: почему нету в документации самого базового "как нажать на карты". Нужно обрабатывать нажатие на карту, но в документации и в примерах описание "как это сделать" не нашел. Можете мне "показать" где найти данную информацию. Спасибо.

**Comment by eberkovich** [comment]
Здравствуйте,

Вот примеры обработки нажатий на объекты в слоях карты и на пользовательские объекты:

https://github.com/yandex/mapkit-android-demo/blob/dcfa1d62171f51dbb7e076c623177091ff4551ef/src/main/java/com/yandex/mapkitdemo/SelectionActivity.java#L56

https://github.com/yandex/mapkit-android-demo/blob/dcfa1d62171f51dbb7e076c623177091ff4551ef/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L192

**Comment by yargeel** [comment]
Как реализовать обработку нажатия на карту в "пустом" пространстве без объектов?
Сценарий — как, например, в приложении Яндекс карт: тап на объект даёт попап с информацией об объекте, тап на произвольный участок карты (в т.ч. без объектов) этот попап скрывает.

**Comment by eberkovich** [comment]
Нужно установить [InputListener](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/Map.html#_35).

**Comment by JerzyXD** [comment]
> Нужно установить [InputListener](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/Map.html#_35) для обработки нажатий на область карты и [TapListener](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/Map.html#_43) для обработки нажатий на объекты на карте.
> Вот [пример](https://github.com/yandex/mapkit-android-demo/blob/dcfa1d62171f51dbb7e076c623177091ff4551ef/src/main/java/com/yandex/mapkitdemo/SelectionActivity.java#L57).
Здравствуйте, к сожалению оба этих слушателя могут просто не отработать по непонятной причине после 3-4 нажатий подряд

**Comment by invweb** [comment]
Уже пару лет использую OSM

**Comment by invweb** [comment]
> Приведите, пожалуйста, пример для SWIFT iOS InputListener и TapListener

Поиск в помощь: https://mail.ru/search?text=SWIFT%20iOS%20InputListener%20%D0%B8%20TapListener&mstatid=490000&type=web&q=SWIFT%2BiOS%2BInputListener%2B%D0%B8%2BTapListener&fr=atom&fr2=query&gp=490000&target=form&frm=homescreen&serp_path=%2Fsearch%2Ftouch%2F
