### ISSUE TITLE
DrivingRoute получение детализации маршрута как в Masstransit

### ISSUE THREAD

**Issue by mitskovets** [yandex/mapkit-android-demo#239]
Добрый день, есть ли метод получения детализации маршрута, проезда на авто (прямо, направо, налево), как при построении маршрута проезда общественным транспортом.
Спасибо.

**Comment by YandexMapKit** [comment]
Посмотрите метод [getDirectionSigns](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/directions/driving/DrivingRoute.html#getDirectionSigns--) в интерфейсе [DrivingRoute](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/directions/driving/DrivingRoute.html#_2)
