### ISSUE TITLE
BoundingBox with pointList

### ISSUE THREAD

**Issue by xandr08** [yandex/mapkit-android-demo#240]
```
var boundingBox = BoundingBox(Point(p1.latitude, p1.longitude), Point(p2.latitude, p2.longitude)) // getting BoundingBox between two points
var cameraPosition = mapView!!.map.cameraPosition(boundingBox) // getting cameraPosition
cameraPosition = CameraPosition(cameraPosition.target, cameraPosition.zoom - 0.8f, cameraPosition.azimuth, cameraPosition.tilt) // Zoom 80%
mapView!!.map.move(cameraPosition, Animation(Animation.Type.SMOOTH, 0f), null) // move camera
```

А подскажите как быть в случае если у меня не 2 point-а а больше и нужно их все отобразить на экране с отступами (left/right paddings)?

В google картах использовал LatLngBounds.Builder() и добавлял все нужные для отображения точки include(LatLng())

Спасибо)

**Comment by eberkovich** [comment]
- BoundingBox по набору точек можно построить либо самостоятельно, либо используя [BoundingBoxHelper](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/geometry/BoundingBoxHelper.html).
- для задания отступов нужно задать [focusRect](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapWindow.html#_10), тогда метод [Map.getCameraPosition(bbox)](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/Map.html#_6) вернет такую позицию камеры, чтобы bbox вписался в заданный focusRect.

**Comment by xandr08** [comment]
@eberkovich 
Не совсем понял как можно реализовать к примеру для 10 Point-ов... используя BoundingBoxHelper.
Можете привести пример? Спасибо)

**Comment by eberkovich** [comment]
Можно написать что-то вроде:
```
BoundingBox bbox = BoundingBoxHelper.getBounds(p0);
bbox = BoundingBoxHelper.getBounds(bbox, p1);
//...
bbox = BoundingBoxHelper.getBounds(bbox, p9);
```
