### ISSUE TITLE
Как сделать чтобы значок пользователя не покрывал placemark? 

### ISSUE THREAD

**Issue by DOSEEARE** [yandex/mapkit-android-demo#241]
![image](https://user-images.githubusercontent.com/46872285/110112134-85247180-7ddb-11eb-8a71-c32cfdda456b.png)

**Comment by TheMrButcher** [comment]
Значок пользователя - это его location? А что за вторая placemark'а? Это MapObject?

**Comment by eberkovich** [comment]
дублирует https://github.com/yandex/mapkit-android-demo/issues/242
