### ISSUE TITLE
User Anchor elevation

### ISSUE THREAD

**Issue by DOSEEARE** [yandex/mapkit-android-demo#242]
![image](https://user-images.githubusercontent.com/46872285/110112134-85247180-7ddb-11eb-8a71-c32cfdda456b.png)
Как сделать чтобы значок пользователя находился в низу placemark по уровню ?

**Comment by eberkovich** [comment]
Самое простое - это создать отдельный слой мапобъектов после создания UserLocationLayer, тогда все объекты этого слоя будут рисоваться поверх объектов из слоя UserLocation.

```
userLocationLayer = mapKit.createUserLocationLayer(mapView.getMapWindow());
topMapObjects = mapView.getMap().addMapObjectLayer("top-mapobjects");

//...
topPlacemark = topMapObjects.addPlacemark(...);
```

**Comment by DOSEEARE** [comment]
Спасибо большое
