### ISSUE TITLE
балуны и хинты на котлине

### ISSUE THREAD

**Issue by repkuc** [yandex/mapkit-android-demo#245]
Как сделать балуны и хинты на котлине 
и использовать стандартные иконки для меток?

**Comment by eberkovich** [comment]
Для этого нужно воспользоваться классом [PlacemarkMapObject](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/PlacemarkMapObject.html), вот [пример](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java) работы с ним.
Пример на java, но на котлин точно так же.
