### ISSUE TITLE
How to animate a marker on a map? (как сделать анимацию маркера на карте ?) 

### ISSUE THREAD

**Issue by Kooo9058** [yandex/mapkit-android-demo#248]
At this point, the AnimatedImageProvider is used to animate the marker, but even in the demo project, the animation does not play. How to make an animated marker on the map? 

```Java
@Override
        public void onMapLongTap(@NonNull Map map, @NonNull Point point) {
            AnimatedImageProvider provider =
                    AnimatedImageProvider.fromAsset(getApplicationContext(), "animation.png");
            IconStyle iconStyle = new IconStyle().setScale(4.f);
            mapObjects.addPlacemark(point, provider, iconStyle);
        }
```

**Comment by eaniconer** [comment]
It can be done like this:

```Java 
PlacemarkMapObject placemark = mapObjects.addPlacemark(point, provider, iconStyle);
placemark.useAnimation().play();
```

**Comment by eaniconer** [comment]
The animation example in demo project seems broken because used png is not animated (not apng). Fixed in this PR: https://github.com/yandex/mapkit-android-demo/pull/249 . In addition, a new example with placemark animation has been added.

**Comment by Kooo9058** [comment]
Thank you for your help.
Everything works, the label is animated.
