### ISSUE TITLE
Zoom to bounds

### ISSUE THREAD

**Issue by kota1921** [yandex/mapkit-android-demo#25]
Hi, how can i use zoom to bounds in this library?

**Comment by eberkovich** [comment]
Hi, you need to use Map.cameraPosition method (https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_cameraPosition__BoundingBox) and then pass obtained position to Map.move method.

**Comment by sucksd** [comment]
Hello!
```kotlin
var boundingBox = BoundingBox(Point(p1.latitude, p1.longitude), Point(p2.latitude, p2.longitude)) // getting BoundingBox between two points
var cameraPosition = mapView!!.map.cameraPosition(boundingBox) // getting cameraPosition
cameraPosition = CameraPosition(cameraPosition.target, cameraPosition.zoom - 0.8f, cameraPosition.azimuth, cameraPosition.tilt) // Zoom 80%
mapView!!.map.move(cameraPosition, Animation(Animation.Type.SMOOTH, 0f), null)
```

**Comment by georrge1994** [comment]
Логичное решение, но как быть, если точек N-ое колво? Я определяю границы, расчитываю центр, а вот с zoom у меня проблемы... Есть ли идеи?

**Comment by xandr08** [comment]
А подскажите как быть в случае если у меня не 2 point-а а больше и нужно их все отобразить на экране с отступами (left/right paddings)?

В google картах использовал LatLngBounds.Builder() и добавлял все нужные для отображения точки include(LatLng())

Спасибо)

**Comment by CoffeSweetMilk** [comment]
> Hello!
> 
> ```kotlin
> var boundingBox = BoundingBox(Point(p1.latitude, p1.longitude), Point(p2.latitude, p2.longitude)) // getting BoundingBox between two points
> var cameraPosition = mapView!!.map.cameraPosition(boundingBox) // getting cameraPosition
> cameraPosition = CameraPosition(cameraPosition.target, cameraPosition.zoom - 0.8f, cameraPosition.azimuth, cameraPosition.tilt) // Zoom 80%
> mapView!!.map.move(cameraPosition, Animation(Animation.Type.SMOOTH, 0f), null) // move camera
> ```

Ok, but how can i get polyline bounds ?

**Comment by eberkovich** [comment]
You can use BoundingBoxHelper.getBounds(Polyline geometry).

**Comment by AlexSuvorov2k** [comment]
CameraPosition cameraPosition(@NonNull BoundingBox var1); is deprecated.
