### ISSUE TITLE
Is there callback destruction of a cluster on the map ? (Существует ли обратный вызов при уничтожении кластера с карты)

### ISSUE THREAD

**Issue by Kooo9058** [yandex/mapkit-android-demo#251]
Прошу совет!
При уничтожении кластера с карты, очень бы хотелось включать анимацию у маркеров, но дело в том, что на уничтожение кластера у яндекса нет соответствующего колбека. То есть, когда кластер разрушается, мы не можем запустить анимацию снова. Протокол YMKClusterListener содержит только метод onClusterAdded(with cluster: YMKCluster), который вызывается только при создании кластера.
Есть ли какое либо решение ?

**Comment by YandexMapKit** [comment]
Подписки на удаление кластера действительно нет. Но ClusterizedMapObjectCollection поддерживает дефолтные анимации при появлении и исчезновении кластеров.
