### ISSUE TITLE
Расчет расстояний

### ISSUE THREAD

**Issue by anton165** [yandex/mapkit-android-demo#252]
Добрый день. Нигде не нашел рассчет расстояния между двумя точками силами библиотеки. 
Может все таки есть какое то решение, не хотелось бы ручками прописывать математику

**Comment by eaniconer** [comment]
Добрый день! Для расчета расстояния можно воспользоваться [android.location](https://developer.android.com/reference/android/location/Location#distanceTo(android.location.Location))

**Comment by eaniconer** [comment]
@anton165 Библиотека тоже умеет находить расстояние с помощью функции distance из  [класса Geo](https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/android/mapkit/ref/com/yandex/mapkit/geometry/Geo.html). Функция рассчитывает расстояние в метрах, используя формулу http://en.wikipedia.org/wiki/Haversine_formula
