### ISSUE TITLE
Векторный рисунок

### ISSUE THREAD

**Issue by anton165** [yandex/mapkit-android-demo#253]
Добрый день!

Не работает ImageProvider.fromResource с векторными рисунками. С PNG все работает нормально. Есть ли какой нибудь ещё способ вывести векторный рисунок, взятый из ресурсов?

**Comment by eberkovich** [comment]
Добрый день ImageProvider не поддерживает векторные ресурсы, единственное, что можно сделать это сконвертировать векторную картинку в Bitmap средствами android sdk и позвать [ImageProvider.fromBitmap()](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L224), либо можно выставить любую android view в качестве содержимого PlacemarkMapObject с помощью [PlacemarkMapObject.setView()](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L224), вот [пример](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L224).
