### ISSUE TITLE
Проблема с MapView

### ISSUE THREAD

**Issue by brlz0r** [yandex/mapkit-android-demo#254]
Здраствуйте. есть BottomSheetDialog, в нем NestedScrollView, при прокрутки вниз карта уходит за пределы BottomSheetDialog, все View пропадают, кроме MapView
![123](https://user-images.githubusercontent.com/68200737/121176176-965e9d80-c864-11eb-9589-cc11eafa1422.png)

**Comment by eberkovich** [comment]
Здравствуйте, 
Попробуйте пожалуйста выставить yandex:movable="true" для MapView.

**Comment by maxLozhechnikov** [comment]
Подскажите как правильно выставить данный атрибут в xml? Где взять namespace yandex?

**Comment by AlexSuvorov2k** [comment]
> namespace yandex

<?xml version="1.0" encoding="utf-8"?>
<com.yandex.mapkit.mapview.MapView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:yandex="http://schemas.android.com/apk/res-auto"
    android:id="@+id/mapView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    yandex:movable="true" />
