### ISSUE TITLE
После обновления на 4.0.0 - full карта падает в runtime

### ISSUE THREAD

**Issue by Flyqy** [yandex/mapkit-android-demo#257]
Происходит при непонятных условиях и непонятно в какую стороны двигаться. На карте кастомные маркеры, но до обновления таких проблем не было

pid: 0, tid: 0 >>> project <<<
backtrace:
  #00  pc 000000000004f064  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 00000000006ba460  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==/*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000006ba2c8  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==/*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000030ec8  /apex/com.android.runtime/bin/linker64 (__dl__Z18do_dl_iterate_phdrPFiP12dl_phdr_infomPvES1_+260)
  #00  pc 00000000000304bc  /apex/com.android.runtime/bin/linker64 (__loader_dl_iterate_phdr+48)
  #00  pc 00000000000010a0  /apex/com.android.runtime/lib64/bionic/libdl.so (dl_iterate_phdr+8)
  #00  pc 00000000006b7f30  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000006b7db0  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000006b72b0  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000) (_Unwind_Backtrace+96)
  #00  pc 000000000022d5e8  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000) (yandex::maps::runtime::backtrace::Backtrace::Backtrace()+52)
  #00  pc 00000000002333c0  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000233210  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000) (yandex::maps::runtime::Exception::Exception(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, yandex::maps::runtime::Exception::Severity)+80)
  #00  pc 00000000002271e8  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000302910  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000302008  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002bf378  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002bf188  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 000000000030a218  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002be0dc  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002be0b8  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002bd2e0  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002d1a20  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002d1840  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002d1784  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000002ff478  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000300ccc  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 0000000000300d0c  /data/app/~~4ZPZv0K5MP4L4DZvtwZg-w==*==/base.apk!lib/arm64-v8a/libcom.yandex.runtime.so (offset 0x1ad1000)
  #00  pc 00000000000b6374  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 0000000000050fa4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by eberkovich** [comment]
Этот стек от какой-то старой версии, приложите пожалуйста стек от версии 4.0.0.
