### ISSUE TITLE
LongTapListener для MapObjects

### ISSUE THREAD

**Issue by xBlackCat** [yandex/mapkit-android-demo#259]
Добавьте пожалуйста возможность устанавливать обработчик длительного нажатия на пины.

**Comment by YandexMapKit** [comment]
Сейчас в сервисе, к сожалению, такой функции нет. Но я передам разработчикам ваше пожелание, они рассмотрят его и, возможно, реализуют в будущих версиях сервиса. 
Вы можете узнавать об обновлениях сервиса в нашем [клубе разработчиков](https://www.yandex.ru/blog/mapsapi). 

Спасибо, что помогаете делать сервис лучше!
