### ISSUE TITLE
what is OID ?  

### ISSUE THREAD

**Issue by usmanovrustam** [yandex/mapkit-android-demo#260]
I wanted to launch by parsing the URL. and this was done successfully. but something interests me. What does it mean when there is a similar query on the Yandex link `oid = 123213425321451`

<span style="color: red;">for example :</span>
`yandexmaps://maps.yandex.ru/?ll=69.325004,41.273548&mode=routes&rtext=41.324292,69.288802~41.271802,69.276534&rtt=auto&ruri=ymapsbm1://org?oid=32091843849~ymapsbm1://org?oid=101329059990&z=12.22`

**Comment by elricbk** [comment]
This is a part of the organization's URI: `ymapsbm1://org?oid=32091843849`. URI is an opaque string used to identify geoobject. For example when obtained from search or suggest results it could be used in `SearchManager.resolveURI` method.
