### ISSUE TITLE
Как выбрать маркер на карте где была применена кластеризация

### ISSUE THREAD

**Issue by gc986** [yandex/mapkit-android-demo#261]
Сделал сначала без кластеризации, всё ок работает, но как только я стал работать с кластеризацией, traverse перестал возаращать PlacemarkMapObject. Раньше этот код работал а теперь нет

```
fun MapView.traversePlacemarks(action: (PlacemarkMapObject) -> Unit) {
    map.mapObjects.traverse(object : MapObjectVisitor {
        override fun onClusterizedCollectionVisitStart(p0: ClusterizedPlacemarkCollection) = false
        override fun onClusterizedCollectionVisitEnd(p0: ClusterizedPlacemarkCollection) {}
        override fun onPolygonVisited(p0: PolygonMapObject) {}
        override fun onCircleVisited(p0: CircleMapObject) {}
        override fun onPolylineVisited(p0: PolylineMapObject) {}
        override fun onColoredPolylineVisited(p0: ColoredPolylineMapObject) {}
        override fun onPlacemarkVisited(p0: PlacemarkMapObject) {
            action(p0)
        }
        override fun onCollectionVisitEnd(p0: MapObjectCollection) {}
        override fun onCollectionVisitStart(p0: MapObjectCollection): Boolean {
            // allows recursive search on nested collections
            return true
        }
    })
}
```

Как мне получить PlacemarkMapObject при работе с кластеризацией?
MapKit 4.0 Lite

**Comment by gc986** [comment]
Вообщем я вышел из этой ситуации со следующим решением: просто после создания каждой точки я сохраняю ссылку на неё в отдельном списке и затем если мне нужно чтото сделать с конкретной точкой (например перерисовать для неё изображение), я просто ищу нужный объект в этом списке :)

**Comment by ivan8m8** [comment]
> Вообщем я вышел из этой ситуации со следующим решением: просто после создания каждой точки я сохраняю ссылку на неё в отдельном списке и затем если мне нужно чтото сделать с конкретной точкой (например перерисовать для неё изображение), я просто ищу нужный объект в этом списке :)

Такой подход будет работать только до тех пор, пока в списке меньше 51200 меток.
