### ISSUE TITLE
libmaps-mobile.so size

### ISSUE THREAD

**Issue by margarita-v** [yandex/mapkit-android-demo#262]
Hello, I have just encountered an issue: after increasing minSdkVersion to 23 for this demo without any other changes APK size becomes bigger a lot.

The first screen shows the result of analysis of the clean demo project with no changes at all:
![Снимок экрана от 2021-08-30 16-42-05](https://user-images.githubusercontent.com/22121595/131349112-b08df65a-1a6e-4bf8-8e0c-f63237dfaed8.png)

The second screen shows the result of analysis of the demo project with minSdkVersion = 23:
![Снимок экрана от 2021-08-30 16-40-12](https://user-images.githubusercontent.com/22121595/131349189-10940dbd-88c1-41f1-af46-a8a7da4e0bd0.png)

I have the same issue for the real project. The issue is reproducing for debug and qa APK, but the size of app bundle (aab) is not affected.

**Comment by veldyasov** [comment]
I have the same problem. minSdkVersion = 21. How is it possible to fix it?

**Comment by 0x76ADF1** [comment]
And I have the same problem. I found that the library under x86_64 has a size of about 50mb. How to reduce the size of this library?

**Comment by akbako** [comment]
Добрый день, у меня такая же проблема. Если остаться на версий SDK,  то размер скомпилированный библиотеки 15.2 мегабайт, а если подниму выше 21 SDK. То, размер скомпилированный библиотеки увеличиться до 56 мегабайт

**Comment by xBlackCat** [comment]
это связано с изменением упаковки apk файлов с версии 23: https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/dsl/JniLibsPackagingOptions#uselegacypackaging

Чтобы включить сжимание библиотек, можно использовать следующую опцию в build.gradle:
```
android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
}

```

Хотя сами размеры .so файлов удручают. Жаль, что sdk использует мало java кода, чтобы сократить размер приложения, которое использует эту библиотеку. Если оставить в нативном коде минимум логики, то это может уменьшить размер библиотеки

**Comment by YandexMapKit** [comment]
Для текущего релиза какого то способа уменьшить размер нет, но мы активно работаем над уменьшением размера и в ближайшие 1-2 релиза он должен ощутимо уменьшиться. Также в mapkit-demo используется full версия библиотеки. Стоит попробовать mapkit-lite, он весит меньше.

There is no way to reduce the size for the current release, but we are actively working on reducing the size and in the next 1–2 releases it should significantly decrease. Mapkit-demo also uses the full version of the library. It's worth trying mapkit-lite, it weighs less.
