### ISSUE TITLE
Вопрос по высоте PolygonMapObject. 

### ISSUE THREAD

**Issue by adeldolgov** [yandex/mapkit-android-demo#263]
Здравствуйте! Такая проблема: имеется полигон, когда близко приближаешь карту здания приобретают 3D вид и становятся видны сквозь полигон. Можно ли как-то заставить полигон находиться всегда поверх зданий?

**Comment by eberkovich** [comment]
Здравствуйте, для изменения порядка отрисовки можно воспользоваться механизмом подслоев: нужно расположить подслой мапобъектов поверх подслоя 3d объектов, вот тут есть как раз такой [пример](https://github.com/yandex/mapkit-android-demo/blob/c380e56a88093fd94cee2e127f98fffaddcc272c/src/main/java/com/yandex/mapkitdemo/MapSublayersActivity.java#L111).
