### ISSUE TITLE
Region и OfflineCacheManager

### ISSUE THREAD

**Issue by JumpyWizardEni** [yandex/mapkit-android-demo#264]
Кейс: хочу предзагрузить часть карты (например, при нажатии на кнопку загрузить несколько регионов Москвы). 

Проблема: документация не описывает, что такое класс Region и как его использовать. Что такое id региона? Как класс соотносится с теми областями, которые порционно загружаются при перемещении камеры по карте?

Мои ожидания:
1) Регион описывает отдельную единицу загрузки (чанк, прямоугольная область на карте со зданиями, которая прогружается по мере перемещения камеры). 
2) OfflineCacheManager предоставляет доступ к загруженным регионам, по мере прогрузки добавляет в список новые регионы, а занимаемая память увеличивается.

Какие эксперименты с OfflineCacheManager были проведены и их результаты:

1) При удалении данных размер сохраненных данных OfflineCacheManager падает до какого-то значения (условно 20000), при начале работы повышается до другого стабильного значения (у меня около 28000), а потом не изменяется, даже если пройтись по случайным регионам (погулять по Америке, Африке, etc.)  
2) На любом этапе количество сохраненных регионов равно 0 (даже если повесить RegionListUpdatesListener).
3) В список regions нельзя добавлять регионы извне, т.е. это все таки некий внутренний класс, с которым сам менеджер должен работать, но по какой-то причине не хочет.
4) RegionListUpdatesListener.onListUpdated() вызывается только при первой инициализации карты, при прогрузке новых регионов не вызывается.

В общем, хотелось бы некоторых разъяснений по работе классов и решении данной задачи.

**Comment by elricbk** [comment]
В такой постановке MapKit решить задачу не позволяет. Чтобы понять, что позволяет делать `OfflineCacheManager` можно посмотреть на загрузку оффлайн-карт в мобильных Яндекс.Картах или Навигаторе.

**Comment by vladtopchu** [comment]
> В такой постановке MapKit решить задачу не позволяет. Чтобы понять, что позволяет делать `OfflineCacheManager` можно посмотреть на загрузку оффлайн-карт в мобильных Яндекс.Картах или Навигаторе.

Добрый день
Могли бы вы подробнее объяснить из-за каких ограничений MapKit не позволяет решить задачу и что делать людям, которые облазали всю документацию яндекса в поисках ответа на данный вопрос?
