### ISSUE TITLE
Проблема перестроения маршрута

### ISSUE THREAD

**Issue by NikTsy** [yandex/mapkit-android-demo#265]
Хотим использовать в проекте коммерческую версию sdk для ведения пользователя по маршруту 
1.  есть ли в sdk метод, позволяющий определить следует ли юзер по первоначальному маршруту или нужно строить новый маршрут?
2. есть ли в sdk метод, позволяющий получить сколько юзер проехал в километрах по маршруту?

**Comment by YandexMapKit** [comment]
Возможности [MapKit](https://yandex.ru/dev/mapkit/doc/3.x/concepts/about-docpage/?from=mapkit) аналогичны таковым в наших приложениях Яндекс.Карты и Яндекс.Навигатор, в которых эти маршруты строятся без каких-либо проблем.

Так что да, возможность ведения юзера по маршруту есть.
Для реализации такого приложения вам понадобится коммерческий ключ Mapkit. Условия бесплатного использования запрещают ведение по маршруту в качестве навигатора.
