### ISSUE TITLE
get closes address by point

### ISSUE THREAD

**Issue by ferr311** [yandex/mapkit-android-demo#266]
как получить адрес ближайшего дома к Point ?
Код выглядит вот так:
private val defaultSearchOptions = SearchOptions().apply { searchTypes = GEO.value }

    override suspend fun getGeoObjectByPoint(point: Point, zoom: Int): GeoObject? = suspendCoroutine {
        geocodeSearchSession = searchManager.submit(
            point,
            zoom,
            defaultSearchOptions,
            addSearchListener(
                { response ->
                    it.resume(response.collection.children.firstOrNull()?.obj)
                }, { throwable ->
                    it.resumeWithException(throwable)
                })
        )
    }

**Comment by elricbk** [comment]
Добрый день. MapKit такой возможности не предоставляет.

**Comment by ferr311** [comment]
> Добрый день. MapKit такой возможности не предоставляет.

@elricbk , а подскажите что можно сделать?
 Вот в данном случае (на скриншоте) должен получить Красная площадь 3
![image](https://user-images.githubusercontent.com/58221607/133559301-38693e4f-4710-475c-bcde-9a3035c45838.png)

**Comment by elricbk** [comment]
Если примерно понятно, на какое расстояние пин может промахиваться, то можно сделать дополнительные запросы в разные стороны (плюс/минус дельта по широте и долготе). Если непонятно, и нужно просто находить ближайший дом, то с помощью MapKit API это сделать не получится.
