### ISSUE TITLE
Метод input() на значении "Ижевск", в onSuggestResponse(), возвращает пустой список.

### ISSUE THREAD

**Issue by alimasanov** [yandex/mapkit-android-demo#267]
Используемая версия mapKit - 3.3.1, search - 3.3.1
Есть метод для поиска:

fun find(input: String) {
val searchManager = SearchFactory.getInstance().createSearchManager(SearchManagerType.COMBINED)
val searchOptions = SearchOptions().setSearchTypes(SearchType.GEO.value).setResultPageSize(100)
val boundingBox = BoundingBox(Point(36.052184, -5.655396),Point(65.998784, -171.748572))
searchManager.suggest(input, boundingBox, searchOptions, getSuggestListener())
}

fun getSuggestListener() = object : SearchManager.SuggestListener {
override fun onSuggestResponse(suggestions: List<SuggestItem>) { ...handling response... }
override fun onSuggestError(error: Error) { ...handling error... }
}

Метод input() отрабатывает корректно, в onSuggestResponse() приходят результаты поиска, но если передать в метод input() город Ижевск, то результат поиска - пустой. Город Ижевск не находится. Если в setSearchTypes() передать SearchType.NONE.value вместо SearchType.GEO.value, то в результате поиска отобразится нужный мне город. 

Проблема заключается в том, что searchType должен быть именно GEO.

Обновление версии sdk не помогло.

**Comment by elricbk** [comment]
Что можно посмотреть:

* `searchManager` и `listener` нужно сделать полями класса. В частности, время жизни `searchManager` заканчивается вот здесь:
  ```
  searchManager.suggest(input, boundingBox, searchOptions, getSuggestListener())
  }
  ```
  и если за ним придёт сборщик мусора, то ответа саджеста не будет.
* Попробовать использовать другой `boundingBox`. Например, прямо над Ижевском. Остаётся проблема?

**Comment by alimasanov** [comment]
> * Попробовать использовать другой `boundingBox`. Например, прямо над Ижевском. Остаётся проблема?

При уменьшении bounding box до размеров Ижевска в результатах поиска появился нужный город. Этот вариант помог. Но я решил покопать дальше и обнаружил, если широта северо-восточной точки отрицательная (напр. -179.999988), то в результатах поиска Ижевска нет, если же широта этой точки положительная (179.9999988), то в результатах поиска появляется необходимый мне город
