### ISSUE TITLE
Не отрисовывается ColoredPolylineMapObject

### ISSUE THREAD

**Issue by Privatik** [yandex/mapkit-android-demo#268]
Из документации не ясно что вообще нужно сделать, что он показался

```
fun MapObjectCollection.createArrowPolyLine1(
    context: Context,
    points: List<Point>,
    strokeWidth: Float = 2f,
    outlineWidth: Float = 9f,
    color: Int = R.color.white_dark,
    outlineColor: Int = R.color.blue,
    zIndex: Float = 30f
) = this.addColoredPolyline(Polyline(points)).also {
    it.strokeWidth = strokeWidth
    it.outlineColor = context.color(outlineColor)
    it.outlineWidth = outlineWidth
}
```

Пробовал ещё передавать такие параметры
```kotlin
 it.setPaletteColor(0,context.color(color))
        it.select(
            context.color(color),
            Subpolyline(
                PolylinePosition(0, 0.0),
                PolylinePosition(0, 1.0)
            )
        )
```

**Comment by eberkovich** [comment]
ColoredPolyline устроен так:  у каждого сегмента есть цвет, цвет - это индекс в палитре.
В Вашем примере палитра настроена, но цвета сегментам не назначены.
Нужно еще позвать [setColors](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/ColoredPolylineMapObject.html#_25).

Метод select тут использовать не нужно, он нужен для другого: чтобы выделить часть линии определенным цветом.

**Comment by Privatik** [comment]
Вы закрыли тему, но это не решает проблему

как только не передаю и так и так и по два элемента получаю одну и ту же ошибку 
```
  it.setColors(listOf(color))
```

`it.setColors(listOf(context.color(color)))`

` java.lang.RuntimeException: colors does not correspond geometry`

**Comment by eberkovich** [comment]
> java.lang.RuntimeException: colors does not correspond geometry
Означает, что количество цветов не соответсвует количеству сегментов в линии.
Должно быть так: количество цветов = количество сегментов = количество точек - 1.

**Comment by Privatik** [comment]
То есть если у нас 20 точек, то мы должны передать лист размером 19, в котором элементы будут 0?

**Comment by eberkovich** [comment]
если все сегменты нужно раскрасить одинаково - нулевым цветом из палитры, то да.

**Comment by Privatik** [comment]
Понятно, спасибо
