### ISSUE TITLE
Формула worldToScreen

### ISSUE THREAD

**Issue by Hellomik2002** [yandex/mapkit-android-demo#272]
можно ло увидить его реализацию ?
Дело в том что я пишу на Flutter  и общаюсь с нативным кодом через мосты они работают быстро
Но в любом случае когда у тебя много обьектов ты с этим ниче сделать не сможешь в любом случае надо у себя я должен писть не через мосты а оптимизоровать 
так вот Я слежу по тому как камера меняется и обновляю мои обьекты
Все работает хорошо пока у меня 20 обьектов чем больше тем сложнее ясно кнч почему
Но если я уберу мосты и буду находить ScreenPoint сам то было бы проще ТАк вот можно ли увидить формулу ну или где найти ресурс где я смогу найти его через CameraPosition

**Comment by eberkovich** [comment]
Формула worldToScreen зависит от настроек камеры в мапкит, которые могут быть изменены в любой момент, по этому не стоит пытаться повторить его логику в приложении.
- Опишите пожалуйста задачу конкретнее, для чего требуется при каждом изменении позиции много раз звать worldToScreen?
- Почему вы считаете, что именно вызовы worldToScreen приводят к проблемам с производительностью?
