### ISSUE TITLE
LocationManager.onLocationUpdated никогда не вызывается

### ISSUE THREAD

**Issue by yargeel** [yandex/mapkit-android-demo#276]
Использую, например, такой код в onCreateView:

val locationManager = MapKitFactory.getInstance().createLocationManager()
        locationManager.requestSingleUpdate(object : LocationListener {
            override fun onLocationStatusUpdated(p0: LocationStatus) {
                Log.d("~~~", "onLocationStatusUpdated")
            }
            override fun onLocationUpdated(p0: Location) {
                Log.d("~~~", "onLocationUpdated")
            }
        })

onLocationUpdated и onLocationStatusUpdated никогда не вызываются, приложению разрешения выданы.
Как правильно использовать LocationManager?

**Comment by eberkovich** [comment]
Mapkit хранит листнеры по слабым сслылкам, по этому их нужно [сохранять в приложении](https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html#quickstart__work).

**Comment by yargeel** [comment]
Увы, не помогло ((

Переменную объявил в экземпляре класса App:
public class App extends MultiDexApplication {
    public static LocationManager locationManager = null;
...

Инициализирую во фрагменте:
mapKit = MapKitFactory.getInstance()
App.locationManager = mapKit.createLocationManager()
App.locationManager?.requestSingleUpdate(object : LocationListener {
       override fun onLocationStatusUpdated(p0: LocationStatus) {
...

И никакой разницы — методы так же не вызываются.
Что делаю не так?

**Comment by eberkovich** [comment]
>Что делаю не так?

Нужно сохранить полем класса не LocationManager, а листнер - LocationListener.
Только сохранить нужно не в Application, а во фрагменте и не статическим полем.

**Comment by yargeel** [comment]
могли бы вы привести пример?
