### ISSUE TITLE
Как интегрировать Яндекс MapKit в проект на Android Studio?

### ISSUE THREAD

**Issue by Ivan16052012** [yandex/mapkit-android-demo#277]
**Пытаюсь интегрировать Яндекс.карту в приложение, создаваемое на Android Studio.Как указано в "Руководстве разработчика MapKit" Яндекс (https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html), получил от Яндекс ключ, создал проект в Android Studio, в build.gradle проекта внёс строки:**
repositories {
mavenCentral()
}
**в build.gradle приложения (модуля) записал:**

repositories {
maven {
url "[maven.google.com](http://maven.google.com/)"
}
}
**в раздел dependencies ЭТОГО файла (build.gradle )модуля внёс запись:**

implementation 'com.yandex.android:maps.mobile:4.0.0-lite'

**Запускаю синхронизацию - и мне выдаётся ошибка:**
_*Exception is^
org.Gradle.api.GradleScriptException: A problem occurred evaluating root project 'MyXY'.
aused by: org.gradle.api.InvalidUserCodeException: Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by build file 'build.gradle' at org.gradle.internal.management.DefaultDependencyResolutionManagement.repoMutationDisallowedOnProject(DefaultDependencyResolutionManagement.java:201)_

Похоже, информация в "Руководстве разработчика MapKit",  устарела.
Посоветуйте, пожалуйста, как получить доступ из проекта Android Studio к MapKit?

627d3beedda78951462696.png

**Comment by YandexMapKit** [comment]
Насколько вижу, ситуация скорее всего связана с настройками [settings.gradle](https://github.com/realm/realm-java/issues/7374) вашего проекта, а не с MapKit непосредственно. Попробуйте перенастроить проект для приоритетности репозиториев **build.gradle** и снова собрать проект.

Если не поможет, пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на GitHub или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.
