### ISSUE TITLE
Как добавить свой подслой?

### ISSUE THREAD

**Issue by ispite** [yandex/mapkit-android-demo#279]
Здравствуйте, как добавить свой sublayer и добавить на него например polygon, а на другой sublayer placemark?
В примере
```java
Integer mapObjectPlacemarkSublayerIndex =
                sublayerManager.findFirstOf(LayerIds.getBuildingsLayerId(), SublayerFeatureType.PLACEMARKS);
```
А как сделать тоже самое для polygon?
```java
        Integer mapObjectPolygonSublayerIndex =
                sublayerManager.findFirstOf(LayerIds.???, SublayerFeatureType.???);
```

MapSublayersActivity работает не корректно.
![изображение](https://user-images.githubusercontent.com/6071329/168985619-90187068-724d-4a1a-a82b-e8bca43449c9.png)

**Comment by CoffeSweetMilk** [comment]
![image](https://user-images.githubusercontent.com/100825181/181486690-086b89f5-c985-4a9e-8a0a-502bf7ac1ed5.png)

**Comment by eberkovich** [comment]
Здравствуйте,
При вызове Map.addMapObjectLayer() саблееры создаются автоматически, поэтому создавать их отдельно не нужно.
Для добавления полигона нужно позвать MapObjectCollection.addPolygon(), для добавления placemark -  MapObjectCollection.addPlacemark(). Они автоматически попадут в нужные саблееры: SublayerFeatureType.Ground и SublayerFeatureType.PlacemarksAndLabels соотвественно.
