### ISSUE TITLE
4.1.0 Не работает метод PolylineMapObject.getParent

### ISSUE THREAD

**Issue by DCrow** [yandex/mapkit-android-demo#281]
Добрый день!

При вызове метода `getParent` экземпляра `PolylineMapObject` выдается следующая ошибка
```
 java.lang.NoSuchMethodError: No interface method getParent()Lcom/yandex/mapkit/map/MapObjectCollection; in class Lcom/yandex/mapkit/map/PolylineMapObject; or its super classes (declaration of 'com.yandex.mapkit.map.PolylineMapObject'
```

Причем если аналогично на iOS вызвать метод `YMKPolylineMapObject.parent`, он выполняется и ошибку не выдает.
Какое поведение считать верным?

**Comment by imseleznev-yandex** [comment]
[getParent](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObject.html#getParent--) теперь возвращает не MapObjectCollection, а [BaseMapObjectCollection](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/BaseMapObjectCollection.html). Это базовый класс для обычной и класстеризованной коллекции, который поддерживает основные операции коллекций: traverse, remove, clear, addListner.
На iOS поведение аналогично.

**Comment by DCrow** [comment]
Ясно, значит теперь с новым классом работать.

Спасибо за разъяснения.
