### ISSUE TITLE
Why did it stop working addTapListener?

### ISSUE THREAD

**Issue by Ewrei** [yandex/mapkit-android-demo#283]
```
  val clusterizedCollection = mapView.map.mapObjects.addClusterizedPlacemarkCollection(this)
 
  clusterizedCollection.addTapListener { p0, p1 ->
                items.findDepartment(p1)?.let {
                    context?.showDialog(it.address)
                }
                true
            }

 clusterizedCollection.addPlacemarks(points, imageProvider, IconStyle())
 clusterizedCollection.clusterPlacemarks(60.0, 15)
```

Why did it work a year ago, but it doesn't work today?
Never called addTapListener((

How to get a click on Placemark?

**Comment by Ewrei** [comment]
Why Does It Work?
 `  clusterizedCollection.addTapListener(this)`
   
   
   Is it not?
  ```
clusterizedCollection.addTapListener { map, point ->
            true
}
```

**Comment by eberkovich** [comment]
mapkit stores listeners by weak reference, that is why they should be stored by application.
https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html#quickstart__work
