### ISSUE TITLE
Как создать простое Navigation Activity?

### ISSUE THREAD

**Issue by romanmahachkala05** [yandex/mapkit-android-demo#284]
К сожалению "справочник" и демо версия не содержат информации о том, как создать активити с навигацией, поэтому прошу помощи тут
Может, я пропустил какой то источник, где находятся инструкции по работе с MapKit?

**Comment by YandexMapKit** [comment]
Если ваш вопрос актуален, то пошаговая инструкция находится в [этом разделе документации](https://yandex.ru/dev/maps/mapkit/doc/android-quickstart/concepts/android/quickstart.html#quickstart__setup). 

Если что-то не выйдет, отправьте, пожалуйста, минимальный пример вашего кода.
