### ISSUE TITLE
Не работает атрибут filter в стилях geojson layer

### ISSUE THREAD

**Issue by andrei-shevelev** [yandex/mapkit-android-demo#285]
Версия библиотеки mapkit 4.1.0-full

В данном примере описан файл стилей для Geojson
https://github.com/yandex/mapkit-android-demo/blob/master/src/main/res/raw/geo_json_style_example.json 
В нем к одному из подслоев применяется блок фильтрации
`
"filter": [
        "any",
        [
          "==",
          "layer",
          "textured-polygon"
        ]
      ]
`
Есть ощущение что данный атрибут никакого влияния не оказывает при отрисовке geojson слоя, можете проверить пожалуйста?

**Comment by YandexMapKit** [comment]
Мы не поддерживаем [устаревшие версии](https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/versions.html#versions__versions), в таких случаях рекомендуем обновить библиотеку до последней версии и попытаться воспроизвести ситуацию.
