### ISSUE TITLE
Как использовать PlacemarkMapObject setText

### ISSUE THREAD

**Issue by AI-Kusu** [yandex/mapkit-android-demo#286]
Здравствуйте, мне нужно подписать метки на карте, в документации нашёл setText, но у меня текст не появляется

`       mapObjects = mapView.getMap().getMapObjects();

        PlacemarkMapObject placemarkMapObject = mapObjects.addPlacemark(new Point(45,45));

        TextStyle textStyle = new TextStyle();

        textStyle.setColor(Integer.parseInt("000000",16));
        textStyle.setOutlineColor(5);
        textStyle.setSize(1000);
        textStyle.setOffsetFromIcon(true);
        textStyle.setPlacement(TextStyle.Placement.CENTER);

        placemarkMapObject.setText("texgdsfnhf;jklbfjsfdbhjbjksfgjk");

        ImageProvider newImageProvider = ImageProvider.fromResource(this,R.drawable.event);

        placemarkMapObject.setIcon(newImageProvider, new IconStyle());`

**Comment by teshca** [comment]
Попробуй указать размер текста поменьше чем 1000, например 8

**Comment by eberkovich** [comment]
Здравствуйте, кроме того указанные цвета являются полностью прозрачными.
Можно просто не указывать цвета и размер, тогда возьмутся дефолтные значения.
/**
   * Text font size in units.
   * default: 8
   */

/**
   * Text color. default: black
   */

/**
  * Outline color. default: white
*/
