### ISSUE TITLE
Store addTapListener in memory

### ISSUE THREAD

**Issue by prosyanoy** [yandex/mapkit-android-demo#287]
I am quite new in Android, so I am sorry if this question is stupid.
Here https://github.com/yandex/mapkit-android-demo/issues/19 eberkovich mentioned that to use multiple listener objects on the map, you need to store them in memory. But how can we do that actually? Can someone provide a code sample, because I didn't encountered that before. Should it be cache memory or some other type of memory?

**Comment by YandexMapKit** [comment]
An example can be found in the [mapkit-demo](https://github.com/yandex/mapkit-android-demo/blob/5df878ad9e00b06b0854832ccd234588d14dda3e/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L142).
