### ISSUE TITLE
В приложении используется версия SDK, которая нарушает правила

### ISSUE THREAD

**Issue by Sequentor** [yandex/mapkit-android-demo#288]
Доброго времени суток! С недавних пор при попытке выпустить рабочую версию приложения получаем ошибку вот с таким содержанием. В приложении нет метрики, есть только com.yandex.android:maps.mobile:4.1.0-lite
![176468893-2bfbec8c-c103-49bb-b68e-bc71d5ac4bc8](https://user-images.githubusercontent.com/62901058/176632021-5626356e-4e74-4360-89dc-bae580f969cd.png)

**Comment by sashok2k** [comment]
Такая же проблема, решение не удаётся найти длительное время уже

**Comment by YandexMapKit** [comment]
**mobmetricalib** не используется в **com.yandex.android:maps.mobile:4.1.0-lite** https://mvnrepository.com/artifact/com.yandex.android/maps.mobile/4.1.0-lite

Причина такого сообщения может быть в других модулях и зависимостях.
