### ISSUE TITLE
Анимация нажатия на пин в кластере

### ISSUE THREAD

**Issue by alexch84** [yandex/mapkit-android-demo#290]
Приветствую! Есть ли возможность как-то анимировать нажатие на пин в onMapObjectTap?

**Comment by YandexMapKit** [comment]
Да, для нажатия на CLuster, нужно использовать ClusterTapListener, на отдельный пин - MapObjectTapListener. Анимации у нас не поддерживаются, но вы можете реализовать их вручную. На всякий случай, у нас поддерживаются анимированные иконки, через PlacemarkAnimation.
