### ISSUE TITLE
Как обратиться к метке на карте?

### ISSUE THREAD

**Issue by TERMINATOR-16** [yandex/mapkit-android-demo#291]
Не знаю как метке добавить в процедуру OnClick. Как её можно индицировать чтобы можно было на них накинуть обработчик? В документации не могу ничего найти подобного. Заранее спасибо!

**Comment by alexch84** [comment]
Смотрите в сторону onMapObjectTap

**Comment by eberkovich** [comment]
Не уверен, что понял вопрос. Но вот [пример](https://github.com/yandex/mapkit-android-demo/blob/e2035a2645dd61117a77ec69bda3be4cbee36440/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L195) обработки нажатий на мап объект.
