### ISSUE TITLE
Ошибка TileProvider

### ISSUE THREAD

**Issue by TERMINATOR-16** [yandex/mapkit-android-demo#293]
E/yandex.maps: yandex::maps::mapkit::tiles::TileLoaderImpl::load: Root must contain 'layers' child
E/yandex.maps: 
E/yandex.maps: Couldn't load tile [geo_json_layer, [7214, 2766, 13]]: Root must contain 'layers' child

Кто нибудь знает что за ошибки?

**Comment by teshca** [comment]
неверный формат geojson тайла, в корне должен быть элемент "layers"
https://raw.githubusercontent.com/yandex/mapkit-android-demo/master/src/main/res/raw/geo_json_example_template.json
