### ISSUE TITLE
TileProvider из примера

### ISSUE THREAD

**Issue by TERMINATOR-16** [yandex/mapkit-android-demo#295]
Подскажите пожалуйста как переделать TileProvider из примера чтобы он читал установленные координаты и ставил метку
`
    private TileProvider createTileProvider() throws IOException
    {
        final String jsonTemplate = getJsonResource("geo_json_example_template");

        return new TileProvider() {
            @NonNull
            @Override
            public RawTile load(@NonNull TileId tileId, @NonNull Version version, @NonNull String etag) {
                int tileSize = 1 << (MAX_ZOOM - tileId.getZ());

                int left = tileId.getX() * tileSize;
                int right = left + tileSize;
                int bottom = tileId.getY() * tileSize;
                int top = bottom + tileSize;

                Point leftBottom = projection.xyToWorld(new XYPoint(left, bottom), MAX_ZOOM);
                Point rightTop = projection.xyToWorld(new XYPoint(right, top), MAX_ZOOM);

                double tileLeft = leftBottom.getLongitude();
                double tileRight = rightTop.getLongitude();
                double tileBottom = leftBottom.getLatitude();
                double tileTop = rightTop.getLatitude();

                HashMap<String, Double> map = new HashMap<String, Double>();

                map.put("@POINT_X@", 0.7 * tileLeft   + 0.3 * tileRight);
                map.put("@POINT_Y@", 0.7 * tileBottom + 0.3 * tileTop);

                map.put("@LINE_X0@", 0.9 * tileLeft   + 0.1 * tileRight);
                map.put("@LINE_Y0@", 0.9 * tileBottom + 0.1 * tileTop);
                map.put("@LINE_X1@", 0.9 * tileLeft   + 0.1 * tileRight);
                map.put("@LINE_Y1@", 0.1 * tileBottom + 0.9 * tileTop);
                map.put("@LINE_X2@", 0.1 * tileLeft   + 0.9 * tileRight);
                map.put("@LINE_Y2@", 0.1 * tileBottom + 0.9 * tileTop);
                map.put("@LINE_X3@", 0.1 * tileLeft   + 0.9 * tileRight);
                map.put("@LINE_Y3@", 0.9 * tileBottom + 0.1 * tileTop);

                map.put("@POLYGON_X0@", 0.2 * tileLeft   + 0.8 * tileRight);
                map.put("@POLYGON_Y0@", 0.8 * tileBottom + 0.2 * tileTop);
                map.put("@POLYGON_X1@", 0.5 * tileLeft   + 0.5 * tileRight);
                map.put("@POLYGON_Y1@", 0.5 * tileBottom + 0.5 * tileTop);
                map.put("@POLYGON_X2@", 0.2 * tileLeft   + 0.8 * tileRight);
                map.put("@POLYGON_Y2@", 0.2 * tileBottom + 0.8 * tileTop);

                map.put("@TEXTURED_POLYGON_X0@", 0.8 * tileLeft   + 0.2 * tileRight);
                map.put("@TEXTURED_POLYGON_Y0@", 0.2 * tileBottom + 0.8 * tileTop);
                map.put("@TEXTURED_POLYGON_X1@", 0.2 * tileLeft   + 0.8 * tileRight);
                map.put("@TEXTURED_POLYGON_Y1@", 0.2 * tileBottom + 0.8 * tileTop);
                map.put("@TEXTURED_POLYGON_X2@", 0.5 * tileLeft   + 0.5 * tileRight);
                map.put("@TEXTURED_POLYGON_Y2@", 0.5 * tileBottom + 0.5 * tileTop);

                String json = jsonTemplate;
                for (Map.Entry<String, Double> entry : map.entrySet()) {
                    json = json.replace(entry.getKey(), String.valueOf(entry.getValue()));
                }

                return new RawTile(version, etag, RawTile.State.OK, json.getBytes());
            }
        };
`
json
`
{
  "layers": [
    {
      "type": "FeatureCollection",
      "name": "point",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [50.600749075996276,137.06115706051267]
          },
          "id": "Point"
        }
      ]
    }]
    }
`

**Comment by YandexMapKit** [comment]
Если объем данных небольшой. Например, не больше 500 меток, то проще воспользоваться **PlacemarkMapObject**. С примером вы можете [ознакомиться здесь](https://github.com/yandex/mapkit-android-demo/blob/5df878ad9e00b06b0854832ccd234588d14dda3e/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L133).

А если объем большой, тогда нужно **добавить geojson слой**. Вот [пример](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/GeoJsonActivity.java).
