### ISSUE TITLE
What is the model ?

### ISSUE THREAD

**Issue by CoffeSweetMilk** [yandex/mapkit-android-demo#296]
PlacemarkMapObject has method setModel(), what does it mean ?

**Comment by eberkovich** [comment]
It allows to put textured 3d model on the map.
Model should be in obj format. 

For example:
```
ImageProvider texture = ImageProvider.fromResource(this, textureId);
ModelStyle modelStyle = new ModelStyle(scale, ModelStyle.UnitType.NORMALIZED);
modelMapObject.setModel(ModelProvider.fromResource(this, objResId, texture), modelStyle, null);
```

Сoordinate axis should be as follows: x - to the right , z - to the up, y - from the plane.
