### ISSUE TITLE
4.2.0-lite crash: java.lang.NoSuchMethodError getLastKnownLocation

### ISSUE THREAD

**Issue by ProVir** [yandex/mapkit-android-demo#303]
Привет!

При обновлении до 4.2.0 или 4.2.1 появился краш при вызове метода `LocationManagerUtils.getLastKnownLocation()`.

```
java.lang.NoSuchMethodError: no non-static method "Lcom/yandex/mapkit/location/Location;.<init>(Lcom/yandex/mapkit/geometry/Point;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/String;JJ)V"
        at com.yandex.mapkit.location.LocationManagerUtils.getLastKnownLocation(Native Method)
```

В 4.1.0-lite все хорошо.

**Comment by PAS78** [comment]
Аналогично:

java.lang.RuntimeException: java.lang.NoSuchMethodError: no non-static method "Lcom/yandex/mapkit/location/Location;.<init>(Lcom/yandex/mapkit/geometry/Point;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/String;JJ)V"
                                                                                                    	com.yandex.runtime.internal.Scheduler.run(Native Method)
                                                                                                    	com.yandex.runtime.internal.Scheduler.handleMessage(Scheduler.java:34)
                                                                                                    	android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	android.os.Looper.loop(Looper.java:225)
                                                                                                    	android.app.ActivityThread.main(ActivityThread.java:7563)
                                                                                                    	java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by ChapaevAnton** [comment]
Аналогичная проблем....

**Comment by Chase-V** [comment]
Не нашли решение?

**Comment by CBBBrother** [comment]
В версии 4.2.2 пофиксили
