### ISSUE TITLE
Получить список Region'ов

### ISSUE THREAD

**Issue by vladtopchu** [yandex/mapkit-android-demo#304]
Добрый день
Пытаюсь разобраться с OfflineCacheManager путём эксперементов, т.к. документация не даёт информации об использовании функционала кэширования
Пытался вызывать OfflineCacheManager в различных местах и получить из него список region'ов, но безуспешно
Подскажите пожалуйста правильный путь получения region'ов для их последующего кэширования

**Comment by YandexMapKit** [comment]
Ваш кейс использования - платный.  Без платного ключа мы не предоставляем ни кэш, ни работу с картой в офлайн-режиме. Выходит, что и OfflineCacheManager работать не будет. О различиях платной и бесплатной версии можете прочитать в [документации](https://yandex.ru/dev/maps/mapkit/doc/intro/concepts/enterprise.html#enterprise__differences).

Чтобы продолжить пользоваться нашим сервисом, вам необходимо приобрести коммерческую лицензию.

#### Ниже инструкция по подключению:
1. Перейдите в [кабинет разработчика](http://developer.tech.yandex.ru/).
2. Подключите нужный продукт через кнопку **Подключить API**.
3. Нажмите кнопку **Новый ключ** и сгенерируйте API ключ, или выберите существующий.
4. Выберите подходящий тариф.
5. Пополните лицевой счет через кнопку **Пополнить**.
6. Выберете тип плательщика (юр. Лицо) и нажмите **Выбрать**.
7. Заполните реквизиты плательщика, сохраните данные и вернитесь в кабинет разработчика.
8. Снова нажмите на кнопку **Пополнить**, введите сумму счета и нажмите **ОК**.
9. На следующей странице сформируйте счет и оплатите его.
10. По тем же реквизитам и с тем же номером ЛС пополните баланс лицевого счёта сверх годового платежа, если вы планируете превышения лимита запросов.

Если у вас остались вопросы, я постараюсь ответить подробнее.
