### ISSUE TITLE
Discontinuing the SafetyNet Attestation API

### ISSUE THREAD

**Issue by xBlackCat** [yandex/mapkit-android-demo#306]
Google прекращает поддержку SafetyNet API, в связи с чем при загрузке приложения в PlayMarket появляется предупреждение. 
https://developer.android.com/training/safetynet/deprecation-timeline

Обновите, пожалуйста, зависимости в maps.mobile

**Comment by Dobrotin** [comment]
Как временное решение можно использовать:
configurations.all {
    exclude group: 'com.google.android.gms', module: 'play-services-safetynet'
}

**Comment by xBlackCat** [comment]
Это точно не поломает работу карт? Будет более чем печально, если приложение будет падать на картах

**Comment by xBlackCat** [comment]
в любом случае - это временное решение. Хочется официального отвязывания этой зависимости. Это гарантирует, что точно не поломаются карты.

**Comment by YandexMapKit** [comment]
Сейчас эту зависимость можно исключить:

implementation ('com.yandex.android:maps.mobile:4.2.2-full') {
    exclude group: 'com.google.android.gms', module: 'play-services-safetynet'
}

К следующему релизу постараемся поправить.

**Comment by appsoftgit** [comment]
Зависимость от SafetyNet API по прежнему присутствует в 'com.yandex.android:maps.mobile:4.3.1-lite'. Удалите ее пожалуйста и из lite пакета.
