### ISSUE TITLE
CameraPosition максимальное значение zoom?

### ISSUE THREAD

**Issue by ChapaevAnton** [yandex/mapkit-android-demo#308]
Здравствуйте.
Класс `CameraPosition` - эмпирическим путем удалось установить что максимальное значение параметра `zoom - 21.0F`, при больших значениях карта уже не приближается. Верно ли что 21.0F максимум? Но мне нужно еще ближе - в `MapWindow` - доступен метод  `setScaleFactor(float scaleFactor)` - увеличивая его можно приблизить объекты еще ближе - это решает проблему. На сколько это эффективный способ? И сохраняется ли реальный масштаб карты и размеры объектов на ней при изменении этого коэффициента?
Спасибо.

**Comment by YandexMapKit** [comment]
Действительно максимальный масштаб — 21 и больше приблизить карту не получится.
**setScaleFactor** - не приближает карту, хотя выглядит похоже, а просто растягивает картинку.
**setScaleFactor** - изменяет коэффициент соответствия device independent pixel и физического пикселя.
