### ISSUE TITLE
Yandex.logo

### ISSUE THREAD

**Issue by iFr0z** [yandex/mapkit-android-demo#31]
![image](https://user-images.githubusercontent.com/4560636/46366184-a9c50e00-c6a4-11e8-8f21-1b12b2a7bab2.png)
How to put the Yandex.logo to the left?

**Comment by ToleubekRauan** [comment]
mapView?.map?.apply {
            ...
            logo.setAlignment(Alignment(HorizontalAlignment.LEFT, VerticalAlignment.BOTTOM))

try this
