### ISSUE TITLE
Карта не прогружается до зума/мува карты

### ISSUE THREAD

**Issue by chernybro** [yandex/mapkit-android-demo#313]
Привет, есть проблема. Воспроизводится не стабильно.
Пробовал версии 4-0-0 и 4-2-2
Чаще воспроизводится при слабом интернете и очищенных данных приложения
Периодически, при открытии карты показывается просто сетка. Сама карта прогрузится если использовать жесты зума или мува карты.
Когда баг воспроизводится, в логкат яндекс выкидывает следующие варнинги
![telegram-cloud-photo-size-2-5229178552270831852-y](https://user-images.githubusercontent.com/68295319/206722210-a4127120-34a5-4ce9-bcb4-5f3c3c951bfc.jpg)

yandex::maps::mapkit::tiles::TileLoaderImpl::load: Couldn't load tile [vmap3, [1237, 641, 11]] because: Unexpected server response: Unknown HTTP status 429. Url: https://proxy.mob.maps.yandex.net:443/mapkit2/layers/2.x/vmap3/tiles?v=22.12.08-0-b221129102200&x=1237&y=641&z=11&zmax=11&zmin=11. Body :Limit exceeded.

Подскажите, пожалуйста в чем может быть причина?

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.

**Comment by titovtima** [comment]
В общем и целом та же проблема. Только зум/мув карты мне не помог, помогло просто переустанавливать много раз приложение (через Android Studio). Сначала отображались только квадратики. Потом после нескольких перезапусков стала загружаться карта мира целиком, но при приближении не становилась более детальной. Ещё после какого-то колоичества перезапусков прогрузилась нормально в одном месте (в СПб, куда наезжает камера), но в других местах так же только общие формы, загруженные при начальном зуме.
Проект-пример https://disk.yandex.ru/d/D6i2m9E6-70Cdw
Файл с логом запуска [launch_logcat.txt](https://github.com/yandex/mapkit-android-demo/files/10434541/launch_logcat.txt)

**Comment by Llavrov** [comment]
У меня такая же проблема с MapKit. На данный момент решение очень актуально - в какой-то момент начали грузится текстуры карты мира, но при  приближении более чем в 5 zoom карта переставала прогружаться и появлялась сетка. Причем данную ситуацию получилось вопсроизвести только на симуляторе iphone 13, а при переустановке приложения сетка вернулась обратно. На данный момент моему API_KEY более одного дня. Писал в поддержку, но пока ответили что нужно подождать.

Но я использую библиотеку для отображения карт в react native приложении https://www.npmjs.com/package/react-native-yamap. Причем уже списался с разработчиками, у которых не возникало проблем при подключении.

Склоняюсь к тому, что проблема с активацией ключа для mapKit...

**Comment by chernybro** [comment]
Мою проблему решили. Написал в поддержку и разобрались с ключом.

**Comment by titovtima** [comment]
Мне тоже ответили из поддержки, сказали что активировали ключ, теперь всё норм.

**Comment by Llavrov** [comment]
Да, у меня тоже все заработало, после того как написал в поддержку, токену на этот момент было около двух дней

**Comment by flachka** [comment]
Та же самая проблема, не прогружаются до конца карты, куда написать?

**Comment by titovtima** [comment]
https://yandex.ru/maps-api/support
