### ISSUE TITLE
Как можно добавить маркер на определённый адрес? 

### ISSUE THREAD

**Issue by Imfarrik** [yandex/mapkit-android-demo#316]
Добрый час! Мне приходит апишка с долготой и широтой, мне нужно отметить этот адрес. Как можно это реализовать?

**Comment by YandexMapKit** [comment]
Для отображения геообъектов можете использовать [Placemark](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/PlacemarkMapObject.html). Примеры можете просмотреть в [демо](https://github.com/yandex/mapkit-android-demo/tree/master/src/main/java/com/yandex/mapkitdemo).

Если это не подойдет под ваши задачи, пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.
