### ISSUE TITLE
Обертка для Jetpack Compose

### ISSUE THREAD

**Issue by naltynbekkz** [yandex/mapkit-android-demo#317]
хотелось узнать планируете ли вы написать обертку для Jetpack Compose как [Google maps](https://github.com/googlemaps/android-maps-compose)?

**Comment by RivayM** [comment]
+ тоже интересно

**Comment by YandexMapKit** [comment]
Планируется добавить обертку в течение года.

**Comment by siyovushdev** [comment]
> Планируется добавить обертку в течение года.

Еще не сделали?)

**Comment by otomir23** [comment]
Закрывают обычно после решения, а не обещания решения

**Comment by gifffert** [comment]
Хотелось бы больше новостей. Google maps не дает создать платежный аккаунт для России (

**Comment by tusxxx** [comment]
> Закрывают обычно после решения, а не обещания решения

.Согласен!
.Где compose?

**Comment by Firsto** [comment]
SAEM HERE, BRO

**Comment by Sub4ikGG** [comment]
Требуем обертку!!)))

**Comment by stakancheck** [comment]
SaMe

**Comment by CyberNut** [comment]
Ребята, 24-й год на дворе.
Очень нужна обёртка для Jetpack Compose!

**Comment by shiroxxsora** [comment]
Все еще нет?

**Comment by stakancheck** [comment]
Как я использовал в Compose Multiplatform, если будет полезно https://habr.com/ru/articles/788554/

**Comment by Kratos1013** [comment]
Вот один из примеров как я реализовал Yandex Mapkit в jetpack compose. 

`
@HiltAndroidApp
class Application: Application() {

    override fun onCreate() {
        super.onCreate()
        MapKitFactory.setApiKey("Yandex_Key")
    }
}
`

`

@Composable
fun LocationPicker(input: LocationPickerInput, output: LocationPickerOutput) {
    val context = LocalContext.current
    val mapView = remember {
        mutableStateOf<MapView?>(null)
    }

    Scaffold(Modifier.fillMaxSize()) { pd ->
        AndroidView(factory = { MapView(it) }, modifier = Modifier.fillMaxSize()) {
            mapView.value = it
        }
    }

    LaunchedEffect(key1 = "loadMapView") {
        snapshotFlow { mapView.value }.collect {
            it?.let {
                MapKitFactory.initialize(context)
                MapKitFactory.getInstance().onStart()
                it.onStart()
            }
        }
    }
}
`

Теперь у нас есть доступ к mapView

Это может и  не лучшее решение но работает как надо

<img width="760" alt="Screenshot 2024-06-21 at 14 39 32" src="https://github.com/yandex/mapkit-android-demo/assets/29680726/d08691d9-4d54-4a6e-aebe-004540575d99">

**Comment by N-Pu** [comment]
> Это может и не лучшее решение но работает как надо
> 
> <img alt="Screenshot 2024-06-21 at 14 39 32" width="760" src="https://private-user-images.githubusercontent.com/29680726/341750614-d08691d9-4d54-4a6e-aebe-004540575d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDkwNzMsIm5iZiI6MTcyNDA0ODc3MywicGF0aCI6Ii8yOTY4MDcyNi8zNDE3NTA2MTQtZDA4NjkxZDktNGQ1NC00YTZlLWFlYmUtMDA0NTQwNTc1ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA2MjYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OWQzMjNhNzEyMzA0ZjI1ODE4YzQwNzg2YTNmZWZlMWI2OTdhZDlkZTAzNGQzZDE4ZDYxOGRmMjI4YWI0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZj0Ip1hxUF0K-x5VFnWDAx-AZceio9Xpx3LDb7aHy8">

В моем случае на планшете именно выдает ошибку вот эту и приложение крашится.

```
 sp<> assignment detected data race
2024-08-18 23:17:32.604  4292-4788  ject.bookbridg          <pre-forked-com.project.bookbridge>  A  runtime.cc:655] Runtime aborting...
                                                                                                    runtime.cc:655] Dumping all threads without mutator lock held
                                                                                                    runtime.cc:655] All threads:
                                                                                                    runtime.cc:655] DALVIK THREADS (68):
                                                                                                    runtime.cc:655] "hwuiTask0" prio=6 tid=3 Runnable
                                                                                                    runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x139400a8 self=0xb400006f16a106f0
                                                                                                    runtime.cc:655]   | sysTid=4788 nice=-2 cgrp=default sched=0/0 handle=0x6d96fe8cc0
                                                                                                    runtime.cc:655]   | state=R schedstat=( 29854268 1928464 48 ) utm=0 stm=2 core=4 HZ=100
                                                                                                    runtime.cc:655]   | stack=0x6d96ef1000-0x6d96ef3000 stackSize=995KB
                                                                                                    runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:655]   native: #00 pc 000000000049ee3c  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
                                                                                                    runtime.cc:655]   native: #01 pc 00000000005ac6dc  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
                                                                                                    runtime.cc:655]   native: #02 pc 00000000005c9814  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
                                                                                                    runtime.cc:655]   native: #03 pc 00000000005c3754  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+528)
                                                                                                    runtime.cc:655]   native: #04 pc 00000000005c2920  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1920)
                                                                                                    runtime.cc:655]   native: #05 pc 000000000055d5a8  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1864)
                                                                                                    runtime.cc:655]   native: #06 pc 0000000000013978  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
                                                                                                    runtime.cc:655]   native: #07 pc 0000000000006e18  /system/lib64/liblog.so (__android_log_assert+336)
                                                                                                    runtime.cc:655]   native: #08 pc 0000000000014834  /system/lib64/libutils.so (android::sp_report_race()+28)
                                                                                                    runtime.cc:655]   native: #09 pc 00000000000c22f0  /system/lib64/libgui.so (android::SurfaceComposerClient::Transaction::deferTransactionUntil_legacy(android::sp<android::SurfaceControl> const&, android::sp<android::IBinder> const&, unsigned long)+200)
```

Без понятия что с этим делать, планшет конечно слабый, но на другом слабом телефоне работает нормально.
