### ISSUE TITLE
Как задать радиус поиска по Submit(string,point,searchOptions,listiner)

### ISSUE THREAD

**Issue by Joyuse** [yandex/mapkit-android-demo#318]
Задался вопросом, как задать радиус поиска от местоположения пользователя, есть список, 25 позиций, слушаю через onSearchResponse, возможно я не правильно использую поиск, потому что не все позиции приходят с ответа, и радиус где находятся метки, очень не большой.
Для наглядности вот кусочки кода
```
val searchOptions = SearchOptions().setSearchTypes(SearchType.BIZ.value).setResultPageSize(COUNT)
val searchManager =
            SearchFactory.getInstance().createSearchManager(SearchManagerType.ONLINE)
        searchSession = searchManager.submit(
            resources.getString(R.string.searchList),
            Geometry.fromPoint(
                searchPoint
            ),
            searchOptions,
            this
        )
```

Возможно я как-то не так использую поиск.
Заранее спасибо за ответ.

**Comment by YandexMapKit** [comment]
В вашем случае - это геокодинг. При поиске организаций возвращаются организации в доме, в который попала точка. При поиске топонимов возвращается стек топонимов. Поэтому в нём нет радиуса - потому что это не запрос в радиусе от точки, это запрос в самой точке.

Не очень понятно, зачем point в запросе с текстом? Такие запросы в Картах и Навигаторе не используются. Такой формат без указания радиуса выглядит некорректно. И по-хорошему, туда должен передаваться не point, а circle.

Чтобы как-то контролировать область поиска, можно делать поиск по bounding box с центром в нужной точке и нужной шириной граней. Если нужен именно круг - можно сделать bounding box с запасом и дополнительно отфильтровать результаты.

**потому что не все позиции приходят с ответа, и радиус где находятся метки, очень не большой.**
Собственно, это из-за того, что это геокодинг, а не поиск в области.

Также, указав bounding box можно получить другой побочный эффект - геопоиск, если ничего не будет найдено в этом bounding box, то может самовольно расшириться область поиска. Зависит от запроса. Так что нужно на всякий случай дополнительно фильтровать.

**Comment by Joyuse** [comment]
> В вашем случае - это геокодинг. При поиске организаций возвращаются организации в доме, в который попала точка. При поиске топонимов возвращается стек топонимов. Поэтому в нём нет радиуса - потому что это не запрос в радиусе от точки, это запрос в самой точке.
> 
> Не очень понятно, зачем point в запросе с текстом? Такие запросы в Картах и Навигаторе не используются. Такой формат без указания радиуса выглядит некорректно. И по-хорошему, туда должен передаваться не point, а circle.
> 
> Чтобы как-то контролировать область поиска, можно делать поиск по bounding box с центром в нужной точке и нужной шириной граней. Если нужен именно круг - можно сделать bounding box с запасом и дополнительно отфильтровать результаты.
> 
> **потому что не все позиции приходят с ответа, и радиус где находятся метки, очень не большой.** Собственно, это из-за того, что это геокодинг, а не поиск в области.
> 
> Также, указав bounding box можно получить другой побочный эффект - геопоиск, если ничего не будет найдено в этом bounding box, то может самовольно расшириться область поиска. Зависит от запроса. Так что нужно на всякий случай дополнительно фильтровать.

Да я поменял точку на VisibleRegion, по поводу Circle, получаю ошибку `supported geometry types: point, bounding box, polyline and polygon` 
Так же как я понял, что в зависимости от зума, будут разные ответы, т.е например, 
У яндекс карт можно взять map.cameraPosition.target и при зуме например 14 то ответ, будет один, а если зум 16 то ответ будет другой, это должно так работать? Документацию найти не могу что бы понять полностью как работает  submit.
И есть вопрос, через фильтры поиск тоже можно реализовать, но не могу найти статьи для работы с ними. Если есть какая-то статья которая объясняет работу фильтров.
Информацию о подробной работе методов submit и filter я найти не могу.

Пример кода того как это сейчас используется


```
 val searchOptions = SearchOptions().setSearchTypes(SearchType.BIZ.value).setResultPageSize(COUNT)
 val searchManager =
            SearchFactory.getInstance().createSearchManager(SearchManagerType.ONLINE)
        searchSession = searchManager.submit(
            "someText",
            VisibleRegionUtils.toPolygon(yandexMap.map.visibleRegion),
            searchOptions,
            this
        )
```
