### ISSUE TITLE
Проблема с отображением карты на Android 9 (может и на других версиях)

### ISSUE THREAD

**Issue by ztimms73** [yandex/mapkit-android-demo#319]
Работа карты проверялась на эмуляторах 9 и 13 Андроида, а так же на физических устройствах Pixel 5a с Android 13 и Xiaomi Mi5s с кастомным ROM на базе AOSP Android 9. На 13 версии карта отображается корректно, на 9 версии сабж не может прогрузиться. Ключ API один и тот же.
| Android 9 | Android 13 |
|-|-|
|![image](https://user-images.githubusercontent.com/61558546/214950836-fa6fdf37-a9a6-4b88-ac09-395561473715.png)|![image](https://user-images.githubusercontent.com/61558546/214950910-a60fd76f-6ba5-4816-bad4-fecbd3c3b17a.png)|

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.

**Comment by ztimms73** [comment]
https://disk.yandex.ru/d/60XvfYhfUzhq1g

Для отображения информации о маршруте с картой, перейдите по любому маршруту общественного транспорта из вкладки "Маршруты". Желательно выбрать город Полоцк, так как в базе данных прописаны координаты остановок общественного транспорта именно этого города.

**Comment by YandexMapKit** [comment]
В вашем собранном приложении не получилось обнаружить описанную проблему с картой. Соберите, пожалуйста, минимальный пример кода на котором данное поведение воспроизводится. А также, пришлите логи с устройства (logcat) в ситуации, когда карта не показывается.

Будем ждать вашего ответа!

**Comment by ztimms73** [comment]
Извиняюсь за долгий ответ, всё решилось удалением аттрибута `android:alpha`, без него теперь на старых версиях Android всё отлично работает.
