### ISSUE TITLE
Unresolved reference: strokeColor 

### ISSUE THREAD

**Issue by iFr0z** [yandex/mapkit-android-demo#321]
```
carPedestrianObject.addPolyline(routes[0].geometry).apply {
            strokeColor = getColor(it, R.color.colorDot) //подчеркивает красным
            outlineColor = getColor(it, R.color.colorWayOutline)
            outlineWidth = 10f
}
```
Как изменить цвет проложенного маршрута? `Outline` работает, а `stroke` подчеркивает красным после перехода на `implementation 'com.yandex.android:maps.mobile:4.2.2-full'`

**Comment by YandexMapKit** [comment]
Чтобы изменить цвет проложенного маршрута вам необходимо использовать сеттер **setStrokeColor**, **strokeColor** перестал быть свойством.
