### ISSUE TITLE
Есть ли у yandex_mapkit для Flutter инструменты работы с офлайн кэшэм?

### ISSUE THREAD

**Issue by ned0emo** [yandex/mapkit-android-demo#322]
Если конкретнее, то интересует возможность задать в коде некоторые области (по ID, координатам или что-то вроде), которые будут автоматически загружены в кэш даже без открытия и просмотра этих областей на карте

**Comment by YandexMapKit** [comment]
1. У нас есть модуль [Offline cache](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/offline_cache/package-summary.html), который позволяет скачивать отдельные регионы. Но он доступен только для платных клиентов.
2. MapKit распространяется только для java и obj-c. Flutter не является официальной платформой, так что тут мы ничего подсказать не сможем.
