### ISSUE TITLE
Неявный запрос геолокации

### ISSUE THREAD

**Issue by alammer** [yandex/mapkit-android-demo#323]
Версия maps.mobile:4.2.2-lite/full. Версии API - 23+

При запуске приложения mapkit-android-demo, выборе пункта Map и открытии экрана с картой в логах всегда проскакивает:

На устройствах с API23:

com.yandex.mapkitdemo E/com.yandex.runtime.sensors.internal.LastKnownLocation: failed to get last known location: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

На устройствах с API29+:

/com.yandex.mapkitdemo E/com.yandex.runtime.sensors.internal.LastKnownLocation: failed to get last known location: java.lang.SecurityException: uid 10149 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.

Внешне на работоспособности абсолютно никак не сказывается. Но по документации вообще непонятно как этот запрос связан с данным кодом:

`@Override
    protected void onCreate(Bundle savedInstanceState) {
        // Now MapView can be created.
        setContentView(R.layout.map);
        super.onCreate(savedInstanceState);
        mapView = findViewById(R.id.mapview);

        // And to show what can be done with it, we move the camera to the center of Saint Petersburg.
        mapView.getMap().move(
                new CameraPosition(TARGET_LOCATION, 10.0f, 0.0f, 0.0f),
                new Animation(Animation.Type.SMOOTH, 1),
                null);
    }

@Override
    protected void onStart() {
        // Activity onStart call must be passed to both MapView and MapKit instance.
        super.onStart();
        MapKitFactory.getInstance().onStart();
        mapView.onStart();
        mapView.getMap().getCameraPosition();
    }
`

Просто есть подозрение, что вчера в PlayMarket обновление завернули именно из-за анализа логов и особенно упоминаний ACCESS_FINE_LOCATION с gps на старых API. А по мануалам как-то неочевидно, что такой запрос под капотом по дефолту происходит при любом использовании библиотеки.

**Comment by YandexMapKit** [comment]
Спасибо за репорт, мы добавим в это место проверку наличия доступа к геолокации.
Запрос происходит в момент MapKitFactory.getInstance().onStart(); для обновления конфига библиотеки.

2023-03-01 7:37:23, alammer <devnull@yandex.ru>:
> Версия maps.mobile:4.2.2-lite/full. Версии API - 23+
> 
> При запуске приложения mapkit-android-demo, выборе пункта Map и открытии экрана с картой в логах всегда проскакивает:
> 
> На устройствах с API23:
> 
> com.yandex.mapkitdemo E/com.yandex.runtime.sensors.internal.LastKnownLocation: failed to get last known location: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
> 
> На устройствах с API29+:
> 
> /com.yandex.mapkitdemo E/com.yandex.runtime.sensors.internal.LastKnownLocation: failed to get last known location: java.lang.SecurityException: uid 10149 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
> 
> Внешне на работоспособности абсолютно никак не сказывается. Но по документации вообще непонятно как этот запрос связан с данным кодом:
> 
> `@Override
>     protected void onCreate(Bundle savedInstanceState) {
>         // Now MapView can be created.
>         setContentView(R.layout.map);
>         super.onCreate(savedInstanceState);
>         mapView = findViewById(R.id.mapview);
> 
>         // And to show what can be done with it, we move the camera to the center of Saint Petersburg.
>         mapView.getMap().move(
>                 new CameraPosition(TARGET_LOCATION, 10.0f, 0.0f, 0.0f),
>                 new Animation(Animation.Type.SMOOTH, 1),
>                 null);
>     }
> 
> @Override
>     protected void onStart() {
>         // Activity onStart call must be passed to both MapView and MapKit instance.
>         super.onStart();
>         MapKitFactory.getInstance().onStart();
>         mapView.onStart();
>         mapView.getMap().getCameraPosition();
>     }
> `
> 
> Просто есть подозрение, что вчера в PlayMarket обновление завернули именно из-за анализа логов и особенно упоминаний ACCESS_FINE_LOCATION с gps на старых API. А по мануалам как-то неочевидно, что такой запрос под капотом по дефолту происходит при любом использовании библиотеки.
> 
> 
> 
>
