### ISSUE TITLE
Ошибка при запросе на поиск com.yandex.runtime.network.internal.ForbiddenErrorBinding@d82ca3d

### ISSUE THREAD

**Issue by PetrGrebnev** [yandex/mapkit-android-demo#324]
При выполнения запрос на поиск по координатам или строкой, приходит ошибка ForbiddenErrorBinding.
В документации по этой ошибке написано "Вам не разрешен доступ к этому объекту".
Но если я меняю ключ от Api ошибка исчезает и запросы на поиск проходят успешно. 
По каким причинам может приходить данная ошибка? 
Фрагмент кода. 
![image](https://user-images.githubusercontent.com/95710980/222089819-a10c2c87-c979-4862-85d8-be5f1d8a793f.png)

**Comment by YandexMapKit** [comment]
Причина может быть в блокировке API-ключа или настроенном с вашей стороны ограничении по идентификаторам приложений. Проверить эту информацию вы можете в [Кабинете разработчика](https://developer.tech.yandex.ru/). Убедитесь также, что используемый ключ относится к сервису **MapKit – мобильный SDK**. Если не получится разобраться, напишите, пожалуйста, в поддержку через [форму](https://yandex.ru/dev/maps/mapkit/doc/feedback/concepts/feedback.html#form). Постараемся помочь.
