### ISSUE TITLE
Краш приложения

### ISSUE THREAD

**Issue by StalDenc** [yandex/mapkit-android-demo#327]
Добрый день. 
Версия библиотеки: 4.3.1-full
Устройства: 

realme RE58A5L1 sdk33
vivo V2205 (Y35) sdk 33
HONOR HWJSN-H sdk 31
Redmi begonia sdk 30
Xiaomi taoyao sdk 33

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 31422 >>> ru.x5.mfpnew <<<

backtrace:
  #00  pc 0x0000000000fea7a4  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #01  pc 0x00000000010197a4  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #02  pc 0x0000000001061d74  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #03  pc 0x0000000001201170  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #04  pc 0x0000000001201274  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #05  pc 0x0000000001201238  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #06  pc 0x00000000012821e8  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #07  pc 0x0000000001227e9c  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #08  pc 0x0000000000e6f140  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so
  #09  pc 0x0000000000e748fc  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/split_config.arm64_v8a.apk!libmaps-mobile.so (Java_com_yandex_runtime_view_internal_PlatformGLRenderer_renderImpl+88)
  #10  pc 0x00000000002e4584  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/oat/arm64/base.odex (art_jni_trampoline+116)
  #11  pc 0x00000000009c6b5c  /data/app/~~p0ddl7wTs76BHZIzki4gqg==/ru.x5.mfpnew-b6zaZ3u3Sqd1RKjm86wNfg==/oat/arm64/base.odex (com.yandex.runtime.view.internal.PlatformGLRenderer.onDrawFrame+92)
  #12  pc 0x0000000002020590  /memfd:jit-cache (android.opengl.GLSurfaceView$GLThread.guardedRun+9568)
  #13  pc 0x000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #14  pc 0x00000000004c3ed4  /system/framework/framework.jar (android.opengl.GLSurfaceView$GLThread.run+120)
  #15  pc 0x0000000000457b6c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556)
  #16  pc 0x0000000000484e54  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156)
  #17  pc 0x0000000000484b20  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+400)
  #18  pc 0x00000000005ce334  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1684)
  #19  pc 0x00000000000eb720  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #20  pc 0x000000000007e2d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by YandexMapKit** [comment]
Здравствуйте!

Вы привели стек, но не само сообщение об ошибке. Для диагностики нам потребуется более подробный лог. Пожалуйста, пришлите его нам. Постараемся вам помочь.

**Comment by DanKamilov** [comment]
> Здравствуйте!
> 
> Вы привели стек, но не само сообщение об ошибке. Для диагностики нам потребуется более подробный лог. Пожалуйста, пришлите его нам. Постараемся вам помочь.

Здравствуйте. Похожая ошибка вот выпадать начала.
<img width="1036" alt="ArzonApteka - Scheduler run - Firebase console 2023-04-18 13-44-13" src="https://user-images.githubusercontent.com/39025095/232723415-b761a5ce-eab8-478f-b4d3-4efa4e4c0287.png">

**Comment by StalDenc** [comment]
@YandexMapKit подскажите, что нужно конкретно? Сообщения об ошибках вот ->
[split_config.armeabi_v7a.apk!libmaps-mobile.so] Java_com_yandex_runtime_view_internal_PlatformGLRenderer_renderImpl

[split_config.arm64_v8a.apk!libmaps-mobile.so] Java_com_yandex_runtime_view_internal_PlatformGLRenderer_renderImpl
SIGSEGV

[split_config.armeabi_v7a.apk!libmaps-mobile.so] Java_com_yandex_runtime_view_internal_PlatformGLRenderer_renderImpl
SIGSEGV

[split_config.arm64_v8a.apk!libmaps-mobile.so] Java_com_yandex_runtime_view_internal_PlatformGLRenderer_renderImpl
SIGBUS

**Comment by YandexMapKit** [comment]
По приведённому стеку не получилось понять в чем проблема. Опишите, пожалуйста, сценарий воспроизведения или пришлите нам минимальный пример на котором можно воспроизвести данную ситуацию. Это поможет разобраться в вопросе.

**Comment by StalDenc** [comment]
@YandexMapKit в том то и проблема, в крашлитике куча крашей карт, а на физическом устройстве не воспроизводится. Может вам добавить больше логирования в библиотеку? Иначе как это расследовать?

**Comment by svsorokina** [comment]
@DanKamilov @StalDenc Подскажите, какое количество таких крашей у вас? Планируем тоже обновиться на 4.3.1, но из-за этих крашей обновление под вопросом.

**Comment by DanKamilov** [comment]
> @DanKamilov @StalDenc Подскажите, какое количество таких крашей у вас? Планируем тоже обновиться на 4.3.1, но из-за этих крашей обновление под вопросом.

Мы откатились на 4.2.2 вроде. Все работает нормально. 4.3.1 багнутый.

**Comment by YandexMapKit** [comment]
Хорошо, что сейчас получилось найти решение. Вам стоит дождаться следующего релиза и обновиться до него. Если проблема повториться, тогда сообщите нам об этом, будем ещё раз исследовать причину.
