### ISSUE TITLE
Вопрос по пункту 3 условий использования MapKit

### ISSUE THREAD

**Issue by ztimms73** [yandex/mapkit-android-demo#328]
Не нарушу ли я пункт 3 условий использования MapKit, если логотип Яндекса будет скрыт за градиентом (особенности дизайна приложения), но оставлю его в другом месте?

![image](https://user-images.githubusercontent.com/61558546/232319348-5800c174-5ab1-4b91-a6b0-f29e469e74c6.png)

**Comment by YandexMapKit** [comment]
Если вы разместите логотип в другом месте вашего приложения, то это не будет считаться нарушением правил использования библиотеки MapKit.
