### ISSUE TITLE
App crash on 4.3.1

### ISSUE THREAD

**Issue by DanKamilov** [yandex/mapkit-android-demo#329]
Добрый день. 4.3.1-lite. 

У части пользователей крашится с ошибкой 
<img width="1036" alt="ArzonApteka - Scheduler run - Firebase console 2023-04-18 13-44-13" src="https://user-images.githubusercontent.com/39025095/232723648-eb299e3a-864e-4023-bb60-5c724d460afb.png">

Что делать?

**Comment by DanKamilov** [comment]
стэк меняется у разных юзеров
<img width="981" alt="ArzonApteka - Scheduler run - Firebase console 2023-04-18 14-14-20" src="https://user-images.githubusercontent.com/39025095/232731652-b180dd35-9807-4a0a-bc16-61b842930205.png">
<img width="1011" alt="ArzonApteka - Scheduler run - Firebase console 2023-04-18 14-14-42" src="https://user-images.githubusercontent.com/39025095/232731685-1ca86a74-946c-4c17-b93d-3e37cbb8e5ab.png">

**Comment by DanKamilov** [comment]
@YandexMapKit @imseleznev-yandex @yandexmaps

**Comment by YandexMapKit** [comment]
Вышло обновление 4.4.0 с правками по данной ситуации. Посмотрите, пожалуйста.

Дайте знать, если вопрос не решится.
