### ISSUE TITLE
Краш при попытке обращения к маркеру. java.lang.RuntimeException: java.lang.RuntimeException: Native object's weak_ptr for N6yandex4maps6mapkit3map9MapObjectE has expired

### ISSUE THREAD

**Issue by PetrGrebnev** [yandex/mapkit-android-demo#330]

**Comment by PetrGrebnev** [comment]
При нажатии на установленный маркер, требуется поменять его вью.
В списке сохранённых маркеров, ищу маркер с той же userData, что бы вызвать и поменять его внешний вид.
Исключение выбрасывается на строчке это строчке val newSelectMarker = markerData.first { it.userData == mapObject.userData }. 
Данная ситуация происходит. после того как я выйду с карты назад, а потом снова вернусь на нее
`private var markerTapListener = MapObjectTapListener { mapObject, _ ->
        when (mapObject.userData) {
            is PickupPoint -> {
                val newSelectMarker = markerData.first { it.userData == mapObject.userData }
                selectMarker(newSelectMarker, false)
                lastSelectMarker = if (lastSelectMarker != null) {
                    selectMarker(lastSelectMarker, true)
                    newSelectMarker
                } else {
                    newSelectMarker
                }
                _placeTapLiveData.value = mapObject.userData as PickupPoint
            }
            is DataPoint -> {
                _dataPointLiveData.value = mapObject.userData as DataPoint
            }
            is Store -> {
                _shopTapLiceData.value = mapObject.userData as Store
            }
        }

        true
    }`

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.

**Comment by Louco11** [comment]
У меня такая же проблема! при изменения цвета полигона polygonMapObjects[index].fillColor = if (region.isCheck) CHECK_DISTRICT_MAP else UNCHECK_DISTRICT_MAP, при первом заходе все хорошо, при повторном краш (Native object's weak_ptr for N6yandex4maps6mapkit3map9MapObjectE has expired). использую карту в compouse через AndroidView(factory = {Ymap})
