### ISSUE TITLE
Android: Реализация элементов управления

### ISSUE THREAD

**Issue by DRMPN** [yandex/mapkit-android-demo#331]
Использую Android MapKit lite
Проблема: создать функционал для трех действий: 1) приблизить карту 2) отдалить карту 3) текущее местоположение
![image](https://github.com/yandex/mapkit-android-demo/assets/61294398/3ee97500-a3f0-4fdf-a416-c6629c1e716a)
Для 1) и 2) в API документации не могу найти как я могу получить доступ к изменению масштаба на карте. Подскажите, чем я могу воспользоваться чтобы получить доступ к полю и изменить его, уменьшить значение или увеличить?  

Правильно ли будет для 3) через LocationListener получить последнее местоположение и через MapView.getMap.move() переместить камеру?

**Comment by YandexMapKit** [comment]
Задать масштаб карты можно с помощью класса [CameraPosition](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/CameraPosition.html).

Для получения местоположения можно использовать [LocationManager](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/location/LocationManager.html?lang=ru) или [UserLocationLayer](https://yandex.ru/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/user_location/UserLocationLayer.html?lang=ru).
