### ISSUE TITLE
Повышение версии play-services-location до 21.0.0+ в яндекс картах

### ISSUE THREAD

**Issue by mozochek** [yandex/mapkit-android-demo#334]
Делаем приложение на flutter, столкнулись с крашем при открытии карты.
Краш происходил из-за того, что в проекте использовался flutter плагин [`yandex_mapkit 3.2.0`](https://pub.dev/packages/yandex_mapkit/versions/3.2.0)(последней версии на момент написания issue), который в свою очередь использует нативную библиотеку яндекс карт [`com.yandex.android:maps.mobile:4.2.2-full`](https://central.sonatype.com/artifact/com.yandex.android/maps.mobile/4.2.2-full), которая в свою очередь использует версию `play-services-location 20.0.0`.
В то же самое время к проекту были подключены другие flutter плагины, которые используют версию `play-services-location 21.0.0` и выше. Между 20 и 21 версиями есть [breaking changes](https://developers.google.com/android/guides/releases?hl=ru#october_13_2022), из-за которых при использовании функционала отображения геопозиции пользователя на карте и происходил краш.

<details>
<summary>Лог ошибки</summary>

![image](https://github.com/yandex/mapkit-android-demo/assets/50376680/bc22770b-e2f2-4ffd-8bc6-1d27cbb05785)
</details>

Сейчас самая последняя версия(на момент написания issue) [`com.yandex.android:maps.mobile:4.3.1-full`](https://central.sonatype.com/artifact/com.yandex.android/maps.mobile/4.3.1-full), в которой так же используются `play-services-location 20.0.0`. Соответственно хотелось бы получить обновление для яндекс карт, в котором была бы добавлена поддержка более высоких версий используемых зависимостей, чтобы они не были блокерами для разрабатываемых приложений.

**Comment by YandexMapKit** [comment]
Данная ситуация будет исправлена с выходом нового релиза 4.3.2. Ориентировочно, это должно произойти в течение одной-двух недель.

**Comment by Sergey1057** [comment]
на нативном приложении Андроид тоже падение при подключении свежей версии com.google.android.gms:play-services-location , не только на flutter

**Comment by mozochek** [comment]
> на нативном приложении Андроид тоже падение при подключении свежей версии com.google.android.gms:play-services-location , не только на flutter

Ну это понятно, просто свой пример привел

**Comment by YandexMapKit** [comment]
[Версия 4.3.2 уже доступна](https://yandex.ru/dev/mapkit/doc/ru/versions#versions). В ней мы повысили версию для play-services-location. Попробуйте обновиться и проверить работоспособность проектов. Если что-то будет не так — дайте знать!
