### ISSUE TITLE
Нет отрисовки карты. 

### ISSUE THREAD

**Issue by PetrGrebnev** [yandex/mapkit-android-demo#336]
Добрый день. Подскажите пожалуйста в чем может быть дело.
В один день перестала не редериться карта. Метки на карте отображаются, сама карта не отрисовалась.
![image](https://github.com/Unact/yandex_mapkit/assets/95710980/3b68d240-eb01-4589-b323-9f12eb469492)

В логах присутствует только такие строчки. В логах, сообщения могут дублироваться, а могут нет
![image](https://github.com/Unact/yandex_mapkit/assets/95710980/cf13f51c-a725-4bc1-b573-498d57d78d46)
![image](https://github.com/Unact/yandex_mapkit/assets/95710980/b91be9da-285e-4ce1-b91c-92aec11c4c41)

Версия карты full - 4.3.1 пробовал так же 4.3.0. Когда перестала работать была версия 4.2.2.

**Comment by YandexMapKit** [comment]
Пришлите, пожалуйста, ссылку на ваш проект или минимальный собранный пример, где воспроизводится такое поведение. Можно приложить ссылку на **[GitHub](https://github.com/)** или загрузить проект в архиве на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку. Посмотрим, что можно предпринять.

**Comment by PetrGrebnev** [comment]
Закрываю проблема решена
