### ISSUE TITLE
cameraPosition(BoundingBox): CameraPosition' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by georrge1994** [yandex/mapkit-android-demo#337]
Hi, Yandex team. `CameraPosition(BoundingBox)` was deprecated, but an "developer" didn't add any usefull comment for it, So, how can we replace the deprecated method? Thx.

**Updated**: version of lib `yandexMapKitVersion = '4.3.1-lite'`

**Comment by YandexMapKit** [comment]
Hi, you can use this method: https://yandex.com/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/map/Map.html#cameraPosition-com.yandex.mapkit.geometry.Geometry-java.lang.Float-java.lang.Float-com.yandex.mapkit.ScreenRect-
Also you can use [Geometry.fromBoundingBox(bbox)](https://yandex.com/dev/maps/mapkit/doc/android-ref/lite/com/yandex/mapkit/geometry/Geometry.html?lang=ru#_12).
