### ISSUE TITLE
Yandex map view not working on API 19

### ISSUE THREAD

**Issue by abdlkdrisiktan** [yandex/mapkit-android-demo#34]
I'm trying to run application on API19 emulator and device but not working
Application is crash and gives error like below
` Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class com.yandex.mapkit.mapview.MapView`

what's the problem please help me 

Thank you

**Comment by IUdalov** [comment]
Hi Abdulkadir!  
Sorry for long response. Can you please test it on MapKit 3.1.1, it should work just fine.
Reopen issue with reproducing example otherwise.
