### ISSUE TITLE
Карта постоянно перезагружается

### ISSUE THREAD

**Issue by dend90** [yandex/mapkit-android-demo#340]
Добавленные во фрагмент постоянно сбрасываются (перезагружаются, т.е. сначала появляется одноцветный фон и через какое-то время отображается сама карта) при переходе на другой фрагмент и обратно. Сам fragment при этом не пересоздается. Так же такого не происходит при сворачивании приложения в фон и возвращения в приложение. Есть предположение, что это может быть связанно с вызовами mapView.onStop() и mapView.onStart(). Непонятно то ли это ожидаемое поведение в данной конфигурации, то ли ошибка в интеграции карт.

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

Мы постараемся помочь.

**Comment by kuzmaMinin** [comment]
Какое было решение? Столкнулся с такой же проблемой
