### ISSUE TITLE
Отключение логов мапкита

### ISSUE THREAD

**Issue by polyblack** [yandex/mapkit-android-demo#341]
Здравствуйте. Каким способом можно отключить вывод логов мапкита на андроид?
![image](https://github.com/yandex/mapkit-android-demo/assets/43234533/b9a1ee59-397e-4977-a657-5677b68e0e10)

**Comment by YandexMapKit** [comment]
Наши специалисты уже устранили данную ситуацию. Пожалуйста, дождитесь выхода [новой версии MapKit](https://yandex.ru/dev/mapkit/doc/ru/versions) и обновитесь на неё.

**Comment by YandexMapKit** [comment]
15 сентября 2023 года вышел MapKit SDK 4.4.0. Обновитесь до новой версии — указанная ситуация в ней предотвращена.

2023-06-30 10:49:8, polyblack <devnull@yandex.ru>:
> Здравствуйте. Каким способом можно отключить вывод логов мапкита на андроид?
> ![image](https://github.com/yandex/mapkit-android-demo/assets/43234533/b9a1ee59-397e-4977-a657-5677b68e0e10)
