### ISSUE TITLE
Слежение камеры за меткой (PlaceMark)

### ISSUE THREAD

**Issue by Child0fTheSun** [yandex/mapkit-android-demo#348]
Как можно повесить якорь на метку, чтобы камера перемещалась вместе с изменением местоположения метки?
Ожидаемое поведение как setAnchor() для UserLocationLyer

**Comment by YandexMapKit** [comment]
Используйте метод [setGeometry](https://yandex.com/dev/mapkit/doc/en/com/yandex/mapkit/map/PlacemarkMapObject#setgeometrypoint), выставляя текущее положение пользователя.

2023-09-03 17:45:58, Child0fTheSun <devnull@yandex.ru>:
> Как можно повесить якорь на метку, чтобы камера перемещалась вместе с изменением местоположения метки?
> Ожидаемое поведение как setAnchor() для UserLocationLyer
