### ISSUE TITLE
Задержка при получении локации пользователя через locationManager.requestSingleUpdate

### ISSUE THREAD

**Issue by Arkuda** [yandex/mapkit-android-demo#351]
Есть код. 
 ```kotlin
  private val locationManager = mapKit.createLocationManager()
  private var singleUpdateLocationListener: LocationListener? = null
   
   override fun requestCurrentLocation() {
        singleUpdateLocationListener = createSingleUpdateLocationListener()
        locationManager.requestSingleUpdate(singleUpdateLocationListener!!)
    }
 
 ```
 
 И когда вызывается `requestCurrentLocation` проходит около 5 секунд пока вернется значение локации.  Это особенность сдк или баг ? Гугл в такие моменты отрабатывает моментально.

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.


2023-09-15 9:49:42, Arkuda <devnull@yandex.ru>:
> Есть код. 
>  ```kotlin
>   private val locationManager = mapKit.createLocationManager()
>   private var singleUpdateLocationListener: LocationListener? = null
>    
>    override fun requestCurrentLocation() {
>         singleUpdateLocationListener = createSingleUpdateLocationListener()
>         locationManager.requestSingleUpdate(singleUpdateLocationListener!!)
>     }
>  
>  ```
>  
>  И когда вызывается `requestCurrentLocation` проходит около 5 секунд пока вернется значение локации.  Это особенность сдк или баг ? Гугл в такие моменты отрабатывает моментально.

**Comment by Arkuda** [comment]
> Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.
> 
> 2023-09-15 9:49:42, Arkuda [devnull@yandex.ru](mailto:devnull@yandex.ru):
> 
> > Есть код.
> > ```kotlin
> >  private val locationManager = mapKit.createLocationManager()
> >  private var singleUpdateLocationListener: LocationListener? = null
> >   
> >   override fun requestCurrentLocation() {
> >        singleUpdateLocationListener = createSingleUpdateLocationListener()
> >        locationManager.requestSingleUpdate(singleUpdateLocationListener!!)
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > И когда вызывается `requestCurrentLocation` проходит около 5 секунд пока вернется значение локации.  Это особенность сдк или баг ? Гугл в такие моменты отрабатывает моментально.

в вопросе и так есть минимальный пример ситуации

**Comment by YandexMapKit** [comment]
Минимальный пример подразумевает тот набор кода, на котором возможно воспроизвести ситуацию. Несколько показанных вами строк не дают представления об инициализации карты, используемом окружении, размещении в коде показанных вами строк и прочих методах.
Если описанное поведение актуально в вашем случае для [минимального примера Яндекс](https://github.com/yandex/mapkit-android-demo/blob/master/mapkit-demo/src/main/java/com/yandex/mapkitdemo/UserLocationActivity.java), уточните, идёт ли речь о реальных устройствах или эмуляторе.

2023-09-18 7:18:58, Arkuda <devnull@yandex.ru>:
>> Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.
>> 
>> 2023-09-15 9:49:42, Arkuda [devnull@yandex.ru](mailto:devnull@yandex.ru):
>> 
>> > Есть код.
>> > ```kotlin
>> >  private val locationManager = mapKit.createLocationManager()
>> >  private var singleUpdateLocationListener: LocationListener? = null
>> >   
>> >   override fun requestCurrentLocation() {
>> >        singleUpdateLocationListener = createSingleUpdateLocationListener()
>> >        locationManager.requestSingleUpdate(singleUpdateLocationListener!!)
>> >    }
>> > ```
>> > 
>> > 
>> >     
>> >       
>> >     
>> > 
>> >       
>> >     
>> > 
>> >     
>> >   
>> > И когда вызывается `requestCurrentLocation` проходит около 5 секунд пока вернется значение локации.  Это особенность сдк или баг ? Гугл в такие моменты отрабатывает моментально.
> 
> в вопросе и так есть минимальный пример ситуации

**Comment by Arkuda** [comment]
> минимального примера Яндекс

Да, похож на пример яндекса. Происходит и на реальных устройствах и на эмуляторах

**Comment by vkatzyn** [comment]
Наблюдаю такую же проблему, версия 4.4.0-full

**Comment by YandexMapKit** [comment]
@Arkuda

Это особенность SDK. 

`requestSingleUpdate()` по смыслу является вызовом подписки `subscribeForLocationUpdates(desiredAccuracy=0, minTime=0, minDistance=0, allowUseInBackground=false, filteringMode=.On, locationListener=locationListener)` с отпиской после получения первого значения. 

Исходя из параметров, этот запрос получает актуальную (не из прошлого) локацию с высокой точностью, что и приводит к задержке. Для быстрого получения локации можно использовать `lastKnownLocation()` (в [Android SDK](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/location/LocationManagerUtils#getlastknownlocation) и в [iOS SDK](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKLocationManager%28LocationManagerUtils%29#lastknownlocation))

Мы отметили себе возникшее затруднение при использовании этой функции — подумаем над тем, как можно улучшить опыт работы с ней. Сроков, когда у нас появится оптимальное решение на этот счёт, назвать не сможем.

**Comment by DanilaYazykov** [comment]
Так и не нашли оптимального решения? Проблема до сих пор остаётся
