### ISSUE TITLE
Как выделить область на карте Yandex?

### ISSUE THREAD

**Issue by dckrOff** [yandex/mapkit-android-demo#352]
Как выделить нужную мне область которая уже есть на карте Yandex. (Yandex карты) Например в городе УФА есть "Советский район", когда я нажимаю на название этой области, она выделяется. Как это сделать в своем коде? То есть при нажатие на название какой либо области\города\страны выделялась это область. Желательно без сторонних сервисов, используя только Yandex Mapkit.

![image](https://github.com/yandex/mapkit-android-demo/assets/92970686/3d5e8041-09af-4156-8700-4c24b0d66f6a)

**Comment by YandexMapKit** [comment]
Пожалуйста, попробуйте выполнить геопоисковый запрос. Документацию вы можете посмотреть [в нашем блоге на Хабре](https://habr.com/ru/companies/yandex/articles/428564/).

В качестве [SearchType](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/search/SearchType) нужно указать Geo.

Геометрию полученную в ответе на запрос можно отобразить на карте с помощью [PolygonMapObject](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/PolygonMapObject).

Также, вы можете ознакомиться с примером добавления полигона на [GitHub](https://github.com/yandex/mapkit-android-demo/blob/8bb3d416a3466657280f0150e04ff45ff189cc3f/mapkit-demo/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L95)
