### ISSUE TITLE
setting .userData() to large quantity mapObjects throwing error

### ISSUE THREAD

**Issue by BekzodYusupov** [yandex/mapkit-android-demo#354]
![image](https://github.com/yandex/mapkit-android-demo/assets/101949099/24bdb201-c08a-45f5-8936-e0a769694056)
if I want to add `.userData()`  to 15k+ objects. Throwing **global reference table overflow**

is there any other right way of doing it?

**Comment by BekzodYusupov** [comment]
@YandexMapKit Hello, any advice/feedback would help me a lot

**Comment by YandexMapKit** [comment]
We cannot guarantee the stable operation of MapKit with a large number of objects. Please try to limit the volume to 1000 objects.
