### ISSUE TITLE
Cluster not working properly

### ISSUE THREAD

**Issue by BekzodYusupov** [yandex/mapkit-android-demo#355]
Sometimes, I have to reopen the screen to make cluster appear. In some cases, cluster stops working in specific zoom level. what could be the reason. What are the some best practices

**Comment by YandexMapKit** [comment]
If you can, send us a minimal compiled example, that demonstrates the situation. It can be uploaded on [GitHub](https://github.com/), attached to mail as an archive, or uploaded to [Yandex Disk](https://disk.yandex.com/) and sent to us via link.

We will try to find a solution.

**Comment by BekzodYusupov** [comment]
Sorry for bothering you. I removed all unnecessary code and optimized. Now it is working smoothly. It is quite challenging to implement it inside compose :).
