### ISSUE TITLE
Построение маршрута до точки

### ISSUE THREAD

**Issue by McFamous** [yandex/mapkit-android-demo#360]
Добрый день! В данный момент добавляем возможность отслеживания маршрута на карте с помощью коммерческой лицензии
В документации не нашли способа, как это можно сделать с помощью инструментов YandexMapkit, кроме как перерисовывания маршрута заново после обновления местоположения пользователя: по итогу движение по маршруту получается дёрганным, а хотелось бы плавное перемещение, как в Яндекс Навигаторе
Подскажите, как это можно реализовать или может есть отдельная документация для коммерческой лицензии?

Видели похожий вопрос ([265](https://github.com/yandex/mapkit-android-demo/issues/265)), но хотелось бы получить более развёрнутый ответ

**Comment by YandexMapKit** [comment]
Вопрос про возможность ведения по маршруту на вашем тарифном плане и запрос необходимой документации вам следует задать своему коммерческому менеджеру API Яндекс или обратиться в поддержку по [форме](https://forms.yandex.ru/surveys/10017458/).
