### ISSUE TITLE
Discontinuing the SafetyNet Attestation API

### ISSUE THREAD

**Issue by svsorokina** [yandex/mapkit-android-demo#361]
Продолжат ли работу старые версии сдк до 4.3.2, которые используют SafetyNet API?

https://developer.android.com/privacy-and-security/safetynet/deprecation-timeline

**Comment by YandexMapKit** [comment]
Отключение **SafetyNet API** не повлияет на работоспособность MapKit.

2023-10-31 8:13:41, svsorokina <devnull@yandex.ru>:
> Продолжат ли работу старые версии сдк до 4.3.2, которые используют SafetyNet API?
> 
> https://developer.android.com/privacy-and-security/safetynet/deprecation-timeline
