### ISSUE TITLE
Тёмная тема | Thema dark

### ISSUE THREAD

**Issue by Dizic** [yandex/mapkit-android-demo#364]
В основной версии [https://yandex.ru/maps/](https://yandex.ru/maps/) есть тёмная тема, можно как то включить тёмную тему на MapKitFactory Android ?

**Comment by YandexMapKit** [comment]
MapKit поддерживает тёмную тему, это настраивается с помощью [Map.setNightModeEnabled(true)](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/Map#setnightmodeenabledboolean).

**Comment by Dizic** [comment]
ещё есть вопрос, как сделать так чтобы при нажатие камера автоматически поворачивалась на север, как сделано в основной карте

**Comment by kolychev** [comment]
Подскажите пожалуйста, как можно поменять цвет фона в светлой/темной теме или совсем спрятать эту фоновую подложку ? В документации по стилям https://yandex.ru/dev/mapkit/doc/ru/style не нашел что можно цвет фона менять через стили, но может еще как-то можно ?
Суть в том, что я оставляю на карте только слой дорог, прячу стилями все остальное и хочу показать карту на своем фоне.
