### ISSUE TITLE
Simple Routing in Lite version

### ISSUE THREAD

**Issue by BekzodYusupov** [yandex/mapkit-android-demo#366]
Is it possible to draw a simple route between two points? I don't need the advanced features mentioned in the full version.
![Screenshot20210706171629MyApplication2](https://github.com/yandex/mapkit-android-demo/assets/101949099/37ff0b01-9251-4b20-b7c1-9a955e572f69)

**Comment by YandexMapKit** [comment]
Only the [Full version of MapKit](https://yandex.com/dev/mapkit/doc/en/#versions) includes a router that can build point-to-point routes.
If you need to display a path between two fixed points on the Lite version, this can only be done with a [polyline](https://yandex.com/dev/mapkit/doc/en/com/yandex/mapkit/geometry/Polyline).
