### ISSUE TITLE
 Fatal Exception: java.lang.UnsatisfiedLinkError dlopen failed

### ISSUE THREAD

**Issue by JohannStolz** [yandex/mapkit-android-demo#367]
Рандомные ошибка в крашлитике, 70% устройств - Сяоми, 65% - андроид 11, версия карт - com.yandex.android:maps.mobile - 4.3.2-full
 
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/user/0/by.shop.evropb/app_lib/libmaps-mobile.so"
java.lang.Runtime.load0 (Runtime.java:939)
java.lang.System.load (System.java:1628)
com.yandex.runtime.internal.ReLinker.loadLibrary (ReLinker.java:82)
com.yandex.runtime.Runtime.loadLibrary (Runtime.java:131)
com.yandex.runtime.Runtime.init (Runtime.java:98)
com.yandex.runtime.Runtime.init (Runtime.java:105)
com.yandex.mapkit.MapKitFactory.initialize (MapKitFactory.java:26) 

Все ошибки имеют одинаковый стектрейс, за исключением одной буквы в пути "/data/user/0/by.shop.europn/app_lib/libmaps-mobile.so", последней буквы в части "by.shop.europe", корректное написание - "by.shop.europe", в ошибках в последнем символе всегда неправильная буква типа "by.shop.europw", "by.shop.europx", "by.shop.europy", "by.shop.europz" и т.д.
![изображение](https://github.com/yandex/mapkit-android-demo/assets/34033850/c060eba1-be59-4be2-be52-bfe4679a0f6c)

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

**Comment by JohannStolz** [comment]
> Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

К сожалению, проект и код под NDA, ошибка происходит во время инициализации компонента с мапкитом, независимо от стека методов, вызвавших инициализацию в примерно таком блоке :

```
@[Provides Reusable]
        fun provideMapKit(appContext: Context, apiKey: String): MapKit {
            MapKitFactory.setApiKey(apiKey)
            MapKitFactory.initialize(appContext)
            return MapKitFactory.getInstance()
        }
```

**Comment by CBBBrother** [comment]
@JohannStolz App bundle используете?

**Comment by JohannStolz** [comment]
> @JohannStolz App bundle используете?

Да, App bundle

**Comment by CBBBrother** [comment]
@JohannStolz Не похоже на типичную проблему и без воспроизведения трудно помочь. Есть два варианта:

1. Попробовать обновиться на более свежую версию: 4.4.0, 4.5.0
2. Попробовать убрать из кода проекта все лишнее пока проект не станет совсем минимальным, чтобы можно было сделать из него воспроизводимый пример.

**Comment by romankulykov** [comment]
The same problem on devices with API 35 @YandexMapKit please take a look on this

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.


2023-12-21 17:30:23, JohannStolz <devnull@yandex.ru>:
>  
>  Рандомные ошибка в крашлитике, 70% устройств - Сяоми, 65% - андроид 11, версия карт - com.yandex.android:maps.mobile - 4.3.2-full
>  
> Fatal Exception: java.lang.UnsatisfiedLinkError
> dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/user/0/by.shop.evropb/app_lib/libmaps-mobile.so"
> java.lang.Runtime.load0 (Runtime.java:939)
> java.lang.System.load (System.java:1628)
> com.yandex.runtime.internal.ReLinker.loadLibrary (ReLinker.java:82)
> com.yandex.runtime.Runtime.loadLibrary (Runtime.java:131)
> com.yandex.runtime.Runtime.init (Runtime.java:98)
> com.yandex.runtime.Runtime.init (Runtime.java:105)
> com.yandex.mapkit.MapKitFactory.initialize (MapKitFactory.java:26) 
> 
> Все ошибки имеют одинаковый стектрейс, за исключением одной буквы в пути "/data/user/0/by.shop.europn/app_lib/libmaps-mobile.so", последней буквы в части "by.shop.europe", корректное написание - "by.shop.europe", в ошибках в последнем символе всегда неправильная буква типа "by.shop.europw", "by.shop.europx", "by.shop.europy", "by.shop.europz" и т.д.
> ![изображение](https://github.com/yandex/mapkit-android-demo/assets/34033850/c060eba1-be59-4be2-be52-bfe4679a0f6c)
> 
> 
>

**Comment by romankulykov** [comment]
Ошибка при загрузке нативной библиотеки на Android 15 (API 35)

Описание проблемы:
При попытке инициализации Yandex Maps SDK на устройстве с Android 15 (API 35) возникает ошибка загрузки нативной библиотеки. Эта проблема воспроизводится как в существующем проекте, так и в новом чистом проекте.

Сообщение об ошибке:
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~4NMPv6xgUj1ehLsaZbtDLg==/dev.roman.testyandexmapapp-5IA02AuBIbY54AQm9XM7cQ==/base.apk!/lib/arm64-v8a/libmaps-mobile.so" (new hash type from the future?)

Шаги для воспроизведения:

Создать новый проект Android
Добавить зависимость Yandex Maps SDK (версия 4.8.0-lite)
Инициализировать MapKit в коде
Запустить приложение на устройстве или эмуляторе с Android 15 (API 35)
Ожидаемое поведение:
SDK должен успешно инициализироваться без ошибок.

Фактическое поведение:
Приложение крашится с ошибкой UnsatisfiedLinkError при попытке загрузить нативную библиотеку.

Дополнительная информация:

Версия Yandex Maps SDK: 4.8.0-lite
Версия Android: 15 (API 35)
Устройство: Эмулятор Android (Resizable Experimental API 35)
Характеристики эмулятора:

Имя: Resizable (Experimental) API 35
AvdId: Resizable_Experimental_API_35
Производитель: Generic
Имя устройства: resizable
Разрешение экрана: 1080x2400
Плотность экрана: 420 dpi
RAM: 2048 MB
CPU: 4 ядра
GPU: включен, режим auto
Архитектура: arm64-v8a
Версия API: 35
Тип системного образа: Google APIs (16 KB Page Size) (ЭТО ВАЖНО!!!)
Прошу рассмотреть этот вопрос и предоставить решение или обходной путь для использования SDK на Android 15.

Ссылка на проект: https://github.com/romankulykov/TestYandexMapApp/tree/main

@YandexMapKit Please take a look ASAP. Thanks!

**Comment by romankulykov** [comment]
Более того, само приложение YandexMaps крашится при таких условиях

**Comment by YandexMapKit** [comment]
Сейчас MapKit не поддерживает 16 КБ страницы.
Мы рассмотрим возможность добавления такой поддержки в будущих версиях. Каких-либо сроков такой доработки пока назвать не сможем.
