### ISSUE TITLE
Blurring is non operational

### ISSUE THREAD

**Issue by naltynbekkz** [yandex/mapkit-android-demo#369]
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
    val effect = RenderEffect.createBlurEffect(10f, 10f, Shader.TileMode.CLAMP)
    mapView.setRenderEffect(effect)
}
```
не работает blur

**Comment by YandexMapKit** [comment]
@naltynbekkz

Сейчас нет возможности использовать блюр для нашей карты, но мы ведём работу над внедрением поддержки эффекта. Точных сроков появления поддержки размытия нет.

**Comment by naltynbekkz** [comment]
Может хотя бы opacity сделаете?
