### ISSUE TITLE
Обёртка для Jetpack Compose. Попытка №2

### ISSUE THREAD

**Issue by maxim-yudin** [yandex/mapkit-android-demo#371]
Прошел почти год с обещания добавить обёртку для Compose. Скажите в новой версии обертка планируется? А то вы прошлый issue закрыли и видимо не видите комментариев разработчиков.

**Comment by anton165** [comment]
Похоже Яндекс всех в игнор поставили по данному вопросу

**Comment by YandexMapKit** [comment]
Сервис планирует в будущем добавить такую поддержку, но каких-либо сроков реализации этой возможности мы пока назвать не сможем.
