### ISSUE TITLE
Yandex mapkit sdk on c+/qt

### ISSUE THREAD

**Issue by yaing11** [yandex/mapkit-android-demo#372]
What's up guys.

I have been porting some applications on the russian mobile operating system Aurora.

Is there any version of Yandex's mapkit sdk in c++ or qt?

**Comment by YandexMapKit** [comment]
At the moment, Yandex has an SDK only for development for iOS (Objective-C, Swift) and Android (Java, Kotlin). Support for other platforms and languages, including C\+\+ and Qt, has not yet been implemented.
