### ISSUE TITLE
Как идентифицировать метку

### ISSUE THREAD

**Issue by Allizar** [yandex/mapkit-android-demo#374]
Моя задача заключаеся в следующем.
Я создаю на карте метке на основанни координат объектов из некой БД.
Далее при тапе на метке мне нужно вывести некое сообщение, например в Toast, в котором содержится описание объекта.

Мне не совсем понтяно, как это сделать в листнере, так у метки нет никаких признаков, которые однозначно бы её идентифицировали или в которые я мог бы записать данные из объекта-основания.  Даже координаты метки не являются строго поятоянными.

Как можно решить данную задачу?

**Comment by YandexMapKit** [comment]
Вы можете либо задать каждой метке свой листенер, либо добавить к метке произвольные данные через метод 
[setUserData()](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/MapObject#setuserdatajavalangobject) класса [MapObject](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/MapObject). Тогда при возникновении события тапа можно будет идентифицировать метку и её данные через [getUserData()](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/MapObject#getuserdata).

**Comment by Allizar** [comment]
@YandexMapKit 
Спасибо за ответ!
Но можете дать какой-то простой пример на Kotlin? 
Из документации не понятно как использовать эти подходы.
