### ISSUE TITLE
Срабатывает движение карты при жесте "назад"

### ISSUE THREAD

**Issue by MaxFinit** [yandex/mapkit-android-demo#376]
Здравствуйте! При жесте "назад" срабатывает движение камеры, также иногда движение срабатывает, когда перетягиваешь view над картой. Может быть как-то можно ограничить область слушателя? Прикрепил видео с актуального сэмпла.

https://github.com/yandex/mapkit-android-demo/assets/38804229/d7555186-7989-4b79-964e-16c1b6b7d5f7

**Comment by YandexMapKit** [comment]
"Область слушателя" ограничить нельзя, карта получив touch-событие будет его обрабатывать

**Comment by MaxFinit** [comment]
> "Область слушателя" ограничить нельзя, карта получив touch-событие будет его обрабатывать

Но как мне кажется не совсем правильное поведение сейчас у карты. Почему она реагирует на жест "назад" и на другие "скролл" слушатели

**Comment by SuperCatDev** [comment]
Вообще тут вопрос а почему карта получает эти события. Тоже столкнулся с этой проблемой, причем на Картах такой проблемы нет

**Comment by ibabuk** [comment]
Кто-нибудь уже решил проблему?
