### ISSUE TITLE
При загрузке карты mapKit приложение крашится или уходит в ANR, иногда карта может отобразиться, но отображается просто сеткой, это все логи, что есть

### ISSUE THREAD

**Issue by ForWorks** [yandex/mapkit-android-demo#378]
Cmdline: com.platfomni.asna.dev
pid: 26258, tid: 26417, name: YMK_Platform-N  >>> com.platfomni.asna.dev <<<
      #01 pc 0000000000b6e37d  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #02 pc 0000000000b730ba  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #03 pc 0000000000b73217  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #04 pc 0000000000b5c046  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #05 pc 0000000000b6878c  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #06 pc 0000000000b72f4c  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #07 pc 0000000000b62471  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so
      #08 pc 0000000000b62700  /data/app/~~-nXwoKsHFjnJaP9kuwwWUA==/com.platfomni.asna.dev-j-3LOahoLE_Qx9fo1OyOfQ==/lib/x86_64/libmaps-mobile.so

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.
