### ISSUE TITLE
Как скрывать пройденные сегменты маршрута Mapkit SDK

### ISSUE THREAD

**Issue by ows5ut** [yandex/mapkit-android-demo#380]
Как можно скрывать маршрут вслед за движением пользователя?
Маршрут отрисован сегментами

**Comment by YandexMapKit** [comment]
У PolylineMapObject есть метод [hide](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/PolylineMapObject#hidesubpolyline), который позволяет скрыть часть маршрута.

2024-03-12 14:41:58, ows5ut <devnull@yandex.ru>:
> Как можно скрывать маршрут вслед за движением пользователя?
> Маршрут отрисован сегментами

**Comment by ows5ut** [comment]
С методом hide знакомы, вопрос в том, как понять что сегмент пройден, или что мы на нём находимся, чтобы его скрыть под меткой пользователя ? Из предложенных вариантов я видел только пересечение точки пользователя по радиусу и попадание в него сегмента, но может есть более правильный подход?
