### ISSUE TITLE
Нахождение точки в полигоне

### ISSUE THREAD

**Issue by jose4ka** [yandex/mapkit-android-demo#381]
Всем привет!
Как я могу узнать, находится ли позиция камеры в нарисованном мною полигоне?

**Comment by YandexMapKit** [comment]
2024-03-26 11:55:43, jose4ka <devnull@yandex.ru>:
> Всем привет!
> Как я могу узнать, находится ли позиция камеры в нарисованном мною полигоне?

**Comment by jose4ka** [comment]
Решил этот момент с использованием сторонних средств - создаю список с объектами полигонов (https://github.com/sromku/polygon-contains-point, эта библиотека как-раз таки позволяет проверять, находится ли точка внутри полигона), и когда двигаю камеру - прохожусь по каждому элементу в списке, и через метод contains() проверяю, находится ли текущая точка в зоне
