### ISSUE TITLE
какая версия flutter, dart нужна?

### ISSUE THREAD

**Issue by eliot58** [yandex/mapkit-android-demo#385]
../../../.pub-cache/hosted/pub.dev/yandex_maps_mapkit_lite-4.6.1-beta1/lib/src/bindings/ui_view/view_provider.dart:36:11: Error: No named parameter with the name 'size'.
          size: mediaQuery.size,
          ^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/rendering/view.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const ViewConfiguration({
        ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/aimesh777/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
какая версия flutter, dart нужна?

**Comment by YandexMapKit** [comment]
Исправили в [версии 4.6.1-beta2](https://pub.dev/packages/yandex_maps_mapkit_lite/versions/4.6.1-beta2) совместимость с flutter 3.22.0. Проверьте, пожалуйста.
