### ISSUE TITLE
Карта отображается в виде сетки

### ISSUE THREAD

**Issue by dreamerenigma** [yandex/mapkit-android-demo#387]
Добрый день, столкнулся с проблемой когда карта отображается в виде сетки 
<img src="https://github.com/yandex/mapkit-android-demo/assets/55082710/6fb41c28-206d-407a-a7f4-49e8a8c51ca3"
     alt="Screenshot"
     width="200" />
Проект на Flutter 
весь код:

```
import 'package:flutter/material.dart';
import 'package:logger/logger.dart';
import 'package:yandex_maps_mapkit_lite/mapkit.dart';
import 'package:yandex_maps_mapkit_lite/yandex_map.dart';

class MapsScreen extends StatefulWidget {
  const MapsScreen({super.key});

  @override
  State<MapsScreen> createState() => MapsScreenState();
}

class MapsScreenState extends State<MapsScreen> {
  MapWindow? mapWindow;
  final logger = Logger();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: YandexMap(
        onMapCreated: (MapWindow mapWindow) {
          logger.d("Map created!");
          setState(() {
            this.mapWindow = mapWindow;
          });

          // Move the map camera after the map is created
          try {
            mapWindow.map.move(
              const CameraPosition(
                Point(latitude: 55.751225, longitude: 37.629540),
                zoom: 17.0,
                azimuth: 150.0,
                tilt: 30.0,
              ),
            );
            logger.d("Camera moved to the position");
          } catch (error) {
            logger.e("Error moving camera: $error");
          }
        },
      ),
    );
  }
}
```

вывод в консоль сообщений:
I/flutter (25391): │ #0   MapsScreenState.build.<anonymous closure> (package:easyshoppin_eshop/features/personalization/screens/maps/maps.dart:22:18)
I/flutter (25391): │ #1   new YandexMap.<anonymous closure> (package:yandex_maps_mapkit_lite/src/bindings/widgets/yandex_map.dart:20:25)
I/flutter (25391): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (25391): │ 🐛 Map created!
I/flutter (25391): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (25391): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (25391): │ #0   MapsScreenState.build.<anonymous closure> (package:easyshoppin_eshop/features/personalization/screens/maps/maps.dart:37:20)
I/flutter (25391): │ #1   new YandexMap.<anonymous closure> (package:yandex_maps_mapkit_lite/src/bindings/widgets/yandex_map.dart:20:25)
I/flutter (25391): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (25391): │ 🐛 Camera moved to the position
I/flutter (25391): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/libEGL  (25391): call to OpenGL ES API with no current context (logged once per thread)
W/ImageReaderSurfaceProducer(25391): ImageTextureEntry can't wait on the fence on Android < 33

как решить данную проблему? В других приложения Яндекс.карта отображается не написанных мной.

**Comment by YandexMapKit** [comment]
Неправильно инициализируется MapKit. Необходимо вызвать **onStart** в **activity**.

Подробности в документации в разделе [Начало работы](https://yandex.ru/dev/mapkit/doc/ru/android/generated/getting_started#add-map). Пример в репозитории в файле [MapActivity.java](https://github.com/yandex/mapkit-android-demo/blob/da420f84eba8b527cf22d9ce3d7630ee1b973bd7/src/main/java/com/yandex/mapkitdemo/MapActivity.java#L44).
