### ISSUE TITLE
Panorama

### ISSUE THREAD

**Issue by iFr0z** [yandex/mapkit-android-demo#39]
On the emulator (API 28) works perfectly.
![untitled-1](https://user-images.githubusercontent.com/4560636/46916820-0f40c500-cfea-11e8-96b7-d82f25206171.jpg)

On the real device Xperia XA1 Plus (API 26):
![20181014_121118729_ios](https://user-images.githubusercontent.com/4560636/46916790-904b8c80-cfe9-11e8-9ef1-b4ac97d36194.jpg)

**How fix it?**

code:
```
if (!setPanorama) {
    showPanorama()
}

private fun showPanorama() {
      val panoramaService = MapKitFactory.getInstance().createPanoramaService()
      panoramaService.findNearest(routeEndLocation, this)
}

override fun onPanoramaSearchResult(panoramaId: String) {
      panoview.visibility = VISIBLE

      panoview.player.openPanorama(panoramaId)
      panoview.player.enableLoadingWheel()
      panoview.player.onMemoryWarning()

      setPanorama = true
}

<com.yandex.mapkit.panorama.PanoramaView
            android:id="@+id/panoview"
            android:layout_width="match_parent"
            android:layout_height="120dp"
            android:layout_marginTop="4dp"
            android:paddingBottom="8dp"
            android:visibility="gone" />
```

**Comment by Tagakov** [comment]
Besides on screenshots layouts look different, I suppose that your panorama is embedded into scrollable bottomsheet or something similar. Try to add `app:movable="true"` attribute to your PanoramaView tag.

**Comment by iFr0z** [comment]
@Tagakov 

> Besides on screenshots layouts look different, I suppose that your panorama is embedded into scrollable bottomsheet

You're absolutely right. I totally forgot to mention it.

---
Thank you so much for your help! `app:movable="true"` - this attribute has helped me :)
