### ISSUE TITLE
Set the initial route azimuth correctly

### ISSUE THREAD

**Issue by AlexSuvorov2k** [yandex/mapkit-android-demo#391]
How to explicitly specify the lane when building a route? The documentation has a method _setInitialAzimuth(double)_.

Should I specify the rotation of the current location or the angle between the start and end points of the route?
![degree](https://github.com/user-attachments/assets/078ebd4d-a416-494a-bdc1-1bfcee4bd1b6)

Which option in the picture is correct?

**Comment by YandexMapKit** [comment]
With **setInitialAzimuth** you can set the angle of rotation relative to the north when creating a route. It helps to more accurately determine on which side of the road the movement will start.
