### ISSUE TITLE
Невозможно использовать на Android 15 c 16 KB размером страниц

### ISSUE THREAD

**Issue by Grouen** [yandex/mapkit-android-demo#394]
На данный момент нет возможности установить приложение, использующее Yandex Maps, на эмулятор с включённым режимом 16 KB page sizes. Необходимо пересобрать нативную часть с поддержкой 16 KB.

https://developer.android.com/guide/practices/page-sizes#build

**Comment by YandexMapKit** [comment]
Сейчас MapKit не поддерживает 16 КБ страницы.
Мы рассмотрим возможность добавления такой поддержки в будущих версиях. Каких-либо сроков такой доработки пока назвать не сможем.

2024-10-02 10:34:20, Grouen <devnull@yandex.ru>:
> На данный момент нет возможности установить приложение, использующее Yandex Maps, на эмулятор с включённым режимом 16 KB page sizes. Необходимо пересобрать нативную часть с поддержкой 16 KB.
> 
> https://developer.android.com/guide/practices/page-sizes#build
