### ISSUE TITLE
Ошибка во время построения пешего маршрута

### ISSUE THREAD

**Issue by YourX36** [yandex/mapkit-android-demo#395]
Здравствуйте, работал с маршрутами для машин и всё прекрасно, понадобилось строить пешие маршруты и приложение начинает безбожно крашится. Очень надеюсь, что вы сможете мне помочь. 

Примеры использования и ошибку так же прикладываю.
![image](https://github.com/user-attachments/assets/255dd41e-316c-4964-abf1-e2614df4734f)

[PedestrianRouteManager.txt](https://github.com/user-attachments/files/17524700/PedestrianRouteManager.txt)

[PedestrianRouteManager(example).txt](https://github.com/user-attachments/files/17524670/PedestrianRouteManager.example.txt)

[error.txt](https://github.com/user-attachments/files/17524672/error.txt)

**Comment by YandexMapKit** [comment]
Пришлите, пожалуйста, полноценный проект, чтобы мы могли воспроизвести проблему на своей стороне.

2024-10-25 15:59:15, YourX36 <devnull@yandex.ru>:
> Здравствуйте, работал с маршрутами для машин и всё прекрасно, понадобилось строить пешие маршруты и приложение начинает безбожно крашится. Очень надеюсь, что вы сможете мне помочь. 
> 
> Примеры использования и ошибку так же прикладываю.
> ![image](https://github.com/user-attachments/assets/255dd41e-316c-4964-abf1-e2614df4734f)
> 
> 
> [PedestrianRouteManager.txt](https://github.com/user-attachments/files/17524700/PedestrianRouteManager.txt)
> 
> 
> [PedestrianRouteManager(example).txt](https://github.com/user-attachments/files/17524670/PedestrianRouteManager.example.txt)
> 
> [error.txt](https://github.com/user-attachments/files/17524672/error.txt)

**Comment by YourX36** [comment]
@YandexMapKit 
Создал отдельный проект
https://github.com/YourX36/YandexMapKitTest/tree/main
В данный момент в проекте оставлено построение маршрута для машины и оно работает, закомментированный код для пешего.
Ошибка точно такая же.

**Comment by YandexMapKit** [comment]
Мы проанализировали вашу ошибку и видим несколько причин.

1. **Методы mapView.onStart() и mapView.onStop() не вызываются.**
У вас не вызываются методы "onStart()" и "onStop()". Мы указали их в пункте 3 из шага 4 нашей [документации](https://yandex.ru/dev/mapkit/doc/ru/android/generated/getting_started#add-map).

2. **Создание пешеходного маршрута должно выполняться через TransportFactory.**
Для создания пешеходных маршрутов рекомендуется использовать **PedestrianRouter** через **TransportFactory**. Пример кода:
```
private PedestrianRouter mtRouter;
mtRouter = TransportFactory.getInstance().createPedestrianRouter();
mtRouter.requestRoutes(points, new TimeOptions(), routeOptions, this);
```

**Comment by YourX36** [comment]
@YandexMapKit , вынес инциализацию mapView в MainActivity чтобы оттуда напрямую следить за жизненным циклом, реализовал методы из документации. 
Роутер у меня так и создаётся, по логу видно, что он инициализируется, избавился от менеджера и сохранил слушатель в отдельной переменной, но ошибка остаётся той же, при этом, DrivingRouter так же работает, не работает только пеший маршрут.
https://github.com/YourX36/YandexMapKitTest

**Comment by YandexMapKit** [comment]
При построении маршрута для пешехода нужно в [RouteOptions](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/transport/masstransit/RouteOptions) определить [FitnessOptions](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/transport/masstransit/FitnessOptions). Например, так:
```
val avoidSteep = false
val routeOptions = RouteOptions(FitnessOptions(avoidSteep))
```
