### ISSUE TITLE
Ошибка при добавлении иконки маркеров на карте.

### ISSUE THREAD

**Issue by WhatuWannaDo** [yandex/mapkit-android-demo#396]
При использовании метода setIcon(icon) проявляется ошибка.
```kotlin
        val icon = ImageProvider.fromResource(context, R.drawable.ic_test_drawable)

        val mrk = map.mapObjects.addPlacemark().apply {
            geometry = pos
            setText("plainText")
            setIcon(icon) // ошибка здесь
        }
```

```
WrPKh0hB5TeE3RaKMs1c: AndroidBitmap_getInfo() failed! Error code: -1
```

**Comment by YandexMapKit** [comment]
Пришлите, пожалуйста, нам минимальный пример, на котором будет видна проблема. Его можно выложить проектом на [GitHub](https://github.com/) или загрузить на [Яндекс Диск](https://disk.yandex.ru/client/disk) и указать ссылку.

**Comment by WhatuWannaDo** [comment]
@YandexMapKit так я собственно и дал пример. ошибка проявляется сразу же, как затрагивается этот участок кода

**Comment by YandexMapKit** [comment]
Мы не можем воспроизвести ошибку на вашем кратком участке кода, чтобы однозначно определить причину. Поэтому просим вас выложить в доступ тот минимальный пример, который можно собрать и протестировать, получив описанный вами результат.
