### ISSUE TITLE
How to add shadow to a placemark?

### ISSUE THREAD

**Issue by romankulykov** [yandex/mapkit-android-demo#397]
Hello Yandex Maps team,

I am trying to add a shadow effect to a placemark, but I couldn’t find any options or properties in the API documentation to achieve this. Is there a way to add a shadow to a placemark natively in the API, or would I need to implement a custom solution (e.g., overlaying a shadow image manually)?

If it’s not currently supported, is this feature planned for future releases?

Thank you for your help!

**Comment by YandexMapKit** [comment]
The service doesn't currently have this feature. There are no plans to add it yet.

2024-11-15 8:45:57, romankulykov <devnull@yandex.ru>:
> Hello Yandex Maps team,
> 
> I am trying to add a shadow effect to a placemark, but I couldn’t find any options or properties in the API documentation to achieve this. Is there a way to add a shadow to a placemark natively in the API, or would I need to implement a custom solution (e.g., overlaying a shadow image manually)?
> 
> If it’s not currently supported, is this feature planned for future releases?
> 
> Thank you for your help!
