### ISSUE TITLE
panoramaView with kotlinx syntehtic

### ISSUE THREAD

**Issue by iFr0z** [yandex/mapkit-android-demo#42]
After updating to MapKit 3.1.1

> widget has an unresolved type 'com.yandex.mapkit.panorama.panoramaview', and thus it was upcasted to 'android.view.view'

**Comment by vbazhenov** [comment]
Panorama module and related classes were moved to a separate package com.yandex.android.places in 3.1 release.

**Comment by iFr0z** [comment]
@vbazhenov You're absolutely right.

```
<com.yandex.mapkit.places.panorama.PanoramaView
            …  />
```

This helped me. 

---

But I don't understand. When I want to show the user's location:

> 2018-10-23 01:21:14.184 6560-6590/... E/yandex.maps: decltype : Ratelimiter rejected access e883e872-9177-4679-9260-82965ef433d7 to maps_mobile_offline_caches@free
> 2018-10-23 01:21:16.244 6560-6560/... E/EnhancedIntentService: binding to the service failed
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: yandex::maps::runtime::async::internal::PackagedTaskCommon: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	com.yandex.runtime.sensors.internal.FusedLocationSubscription.<init>(FusedLocationSubscription.java:45)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 		Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/base.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_dependencies_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_resources_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_0_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_1_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_2_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_3_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_4_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqjZ6hL1fQ==/split_lib_slice_5_apk.apk", zip file "/data/app/...-IQO6tn6RST_hxqj
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0)
> 2018-10-23 01:21:17.442 6560-6589/... E/yandex.maps: 	com.yandex.runtime.sensors.internal.FusedLocationSubscription.<init>(FusedLocationSubscription.java:45)
> 2018-10-23 01:21:19.253 6560-6590/... E/yandex.maps: decltype : Ratelimiter rejected access e883e872-9177-4679-9260-82965ef433d7 to maps_mobile_offline_caches@free
