### ISSUE TITLE
Runtime error: invalid argumentfailed parses the internal address structure from web.adfox.ru.

### ISSUE THREAD

**Issue by SrgRych** [yandex/mapkit-android-demo#5]
Thanks for the new version. 
The project was built and started, however when I trying to call any activity an error occurs: mapview works properly (i.e. the location is found and so on...), but does not load the map. Logcat shows: 27824-27880 / com.Yandex.map kit demo E / yandex.maps: Yandex:: maps:: environment:: networks:: General:: dnscache:: resetLocalResolver: invalid argumentfailed parses the internal address structure from web.adfox.ru.

**Comment by IUdalov** [comment]
Do you have internet connection on the device?

**Comment by IUdalov** [comment]
Can you share sample minimal reproducible code sample?

**Comment by SrgRych** [comment]
Yes, of course, but it was just the example from github, without any changes. Thanks a lot, I`ll wait more stable version, thanks again.
