### ISSUE TITLE
How can i get a TrafficLayer in MapKit 3.1.2?

### ISSUE THREAD

**Issue by AlexRU18** [yandex/mapkit-android-demo#50]
In version 3.0.0 i can get this layer by this:
`trafficLayer = mapView.getMap().getTrafficLayer();`
Now it's not working

**Comment by vbazhenov** [comment]
```
trafficLayer = MapKitFactory.getInstance().createTrafficLayer(mapview.getMapWindow());
```
We'll probably add a traffic layer example a bit later.
