### ISSUE TITLE
Проблемы с определением местоположения

### ISSUE THREAD

**Issue by Vladulka** [yandex/mapkit-android-demo#53]
На некоторых телефонах не находится местоположение пользователя, используя Можно ли это как то отследить? Или от чего зависит нахождение местоположения, что нужно включить?

**Comment by iFr0z** [comment]
Пользователь должен дать добро на определение местоположение c API 23

**Comment by Vladulka** [comment]
То есть даже при выключенном местоположении он должен найти позицию? А есть ли вариант ее ненахождения? Если да, то как это можно отследить?

**Comment by iFr0z** [comment]
При выключенном местоположении, он не найдёт новую позицию, а лишь запомнит последнюю.

**Comment by Vladulka** [comment]
То есть надо проверять включено ли определение местоположения, после этого начинать поиск геолокации?

**Comment by vbazhenov** [comment]
Да, начиная с android 6.0 надо проверять разрешение на определение местоположения и запрашивать его, если оно отсутствует: https://developer.android.com/training/permissions/requesting
Это нужно делать в приложении, со стороны мапкита разрешение не запрашивается.

**Comment by Vladulka** [comment]
Все есть, только вот на Xiami и LeEco не определяется, даже при вкл. местоположении и данных разрешениях. Уже месяц с этим бьюсь, не могу понять где ошибка....
