### ISSUE TITLE
com.yandex.android:search

### ISSUE THREAD

**Issue by alme1990** [yandex/mapkit-android-demo#59]
Хочу использовать возможности com.yandex.android:search для геокодинга, который раньше делался через запрос https://geocode-maps.yandex.ru/1.x/. Но возникли проблемы с пониманием, какие параметры за что отвечают. 
Мне необходимо сделать следующие вещи, которые раньше делались через запрос:
1. По входным координатам получить адрес
2. По неполному адресу вывести подсказки, которые будут дополнять его
Возможности библиотеки это позволяют сделать или нет? Если да, то как?
Спасибо

**Comment by elricbk** [comment]
1. Для этого нужно использовать [обратное геокодирование](https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/SearchManager-docpage/#method_detail__method_submit___NonNullPoint___NullableInteger___NonNullSearchOptions___NonNullSearchListener) с типом GEO
2. А для этого метод [suggest](https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/SearchManager-docpage/#method_detail__method_suggest___NonNullString___NonNullBoundingBox___NonNullSearchOptions___NonNullSuggestListener). Если хотите подсказывать только адреса, то тоже с типом GEO.
