### ISSUE TITLE
On touch example

### ISSUE THREAD

**Issue by valerytamashevich** [yandex/mapkit-android-demo#6]
Hello guys!
Can you help me with such case:
Catch onTap action and get object with full info, e.g. address and building number.
I suppose this 
public  interface  GeoObjectSession.GeoObjectListener 
Can help me, but I didn't find where I should set it.

**Comment by IUdalov** [comment]
Hi!
This is part of Map.
[addTapListene](https://tech.yandex.ru/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/map/Map-docpage/#method_detail__method_addTapListener__GeoObjectTapListener) can help you!

**Comment by valerytamashevich** [comment]
Thank you for a quick reply.
I'm sorry, but how I can [request detailed info for the specified object](https://tech.yandex.ru/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/GeoObjectSession.GeoObjectListener-docpage/)?
With help of [GeoObjectTapListener](https://tech.yandex.ru/mapkit/doc/3.x/concepts/android/mapkit/ref/com/yandex/mapkit/layers/GeoObjectTapListener-docpage/) I get in `onObjectTap(GeoObjectTapEvent event)` callback only short info, all fields are `null` and all boolean fields are `false`.
