### ISSUE TITLE
Черный экран при переходе назад

### ISSUE THREAD

**Issue by mancj** [yandex/mapkit-android-demo#60]
При переходе назад в предыдущее активити, отображается черный экран на месте карты в течение 100-200 мс. Как это исправить?

**Comment by eberkovich** [comment]
Стабильно ли это воспроизводится? 
Не могли бы Вы прислать минимальный пример на котором это можно воспроизвести?

**Comment by Skeptick** [comment]
Воспроизводится стабильно. На некоторых версиях андроида черный экран не только при переходе назад, но и при открытии карты. В вопросе речь про активити, но вот пример на фрагментах:
```kotlin
class MainActivity : AppCompatActivity() {

    private val container by lazy {
        FrameLayout(this).apply {
            id = ViewCompat.generateViewId()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(container)
        supportFragmentManager.beginTransaction()
            .add(container.id, FirstFragment())
            .commit()
    }

    fun openSecondFragment() {
        supportFragmentManager.beginTransaction()
            .replace(container.id, SecondFragment())
            .addToBackStack(null)
            .commit()
    }

    override fun onBackPressed() {
        if (supportFragmentManager.backStackEntryCount > 0) supportFragmentManager.popBackStack()
        else super.onBackPressed()
    }

}

class FirstFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = FrameLayout(context).apply {
        addView(Button(context).apply {
            text = "Open Map"
            setOnClickListener { (activity as MainActivity).openSecondFragment() }
        })
    }
}

class SecondFragment : Fragment() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        MapKitFactory.setApiKey("key_not_needed")
        MapKitFactory.initialize(context)
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? = FrameLayout(context).apply root@{
        addView(MapView(context))
    }
}
```

**Comment by nitrodenov** [comment]
Стабильно воспроизводится такое поведение на сторонних приложениях, использующие Yandex Mapkit. Нужно перейти на экран с картой и нажать "Назад". Будет мелькание черного экрана. Стабильно воспроизводится на Sony Xperia X с Android 8.0.0

**Comment by youlovejohnny** [comment]
Присоединяюсь. Наблюдается каждый раз при смене фрагментов, в одном из которых находится карта.

**Comment by Skeptick** [comment]
Уточню, что особой связи с активити/фрагментами нет, и предположу, что дело в используемом TextureView. Нужно было сделать карту в горизонтальном RecyclerView/ViewPager, и каждый раз при свайпах на следующую/предыдущую, при появлении и исчезновении, карта неприятно моргала черным, а если ещё и анимации навернуть на перелистывание, то это всё усугублялось вдвойне. Чем старее версия андроида - тем хуже.

**Comment by eberkovich** [comment]
> Уточню, что особой связи с активити/фрагментами нет, и предположу, что дело в используемом TextureView. Нужно было сделать карту в горизонтальном RecyclerView/ViewPager.

Это отдельная проблема, нормально использовать RecyclerView вместе с MapView (так же и с любой другой view использующей opengl для отрисовки) не получится. Дело в том,  что RecyclerView детачит view в результате чего пересоздается open gl context. Теоретически RecyclerView должен позволять отлючать detach, но эта функциональность в нем не работает: https://stackoverflow.com/questions/40397778/prevent-recyclerview-item-from-detaching

**Comment by eberkovich** [comment]
> Воспроизводится стабильно. На некоторых версиях андроида черный экран не только при переходе назад, но и при открытии карты. В вопросе речь про активити, но вот пример на фрагментах:

Зовется ли MapView.onStart/onStop?

**Comment by youlovejohnny** [comment]
> > Воспроизводится стабильно. На некоторых версиях андроида черный экран не только при переходе назад, но и при открытии карты. В вопросе речь про активити, но вот пример на фрагментах:
> 
> Зовется ли MapView.onStart/onStop?

Да, оба метода отрабатывают при смене фрагмента

**Comment by TheRunny** [comment]
Стабильно воспроизводится.

У меня сначала была проблема, когда один фрагмент над другим был и в обоих имелась MapView. Решил изменить навигацию, чтобы фрагмент не добавлялся(add) поверх, а заменялся(replce). В такое реализации при навигации туда-обратно MapView область мерцает черным.

**Comment by teshca** [comment]
Воспроизводится только при использовании фрагментов,
связано с особенностями реализации SurfaceView

При необходимости использовать MapView в сценарии с фрагментами избежать
мерцания черным можно только переключив MapView на использование TextureView
Это можно сделать указать в xml атрибут movable=true
Стоит иметь ввиду, что отрисовка через TextureView работает медленнее, чем через SurfaceView.

**Comment by alexxxdev** [comment]
Стабильно воспроизводится, movable=true не помогает

**Comment by hikkidev** [comment]
Fix?

**Comment by nikiJava** [comment]
Вы планируете править этот баг?

**Comment by eberkovich** [comment]
Как писали выше, мы считаем это проблемой android: SurfaceView, по этому планов исправлять нет.

**Comment by georrge1994** [comment]
аналогичная проблема. Как можно делать single activity приложение в таком случае?

**Comment by ge0graff** [comment]
Если еще актуально... Попробуйте переходить с фрагмента с картой не .replace, а с .add. Как я понял, что mapView тяжелая для отрисовки и поэтому время смены фрагментов увеличивает, и в эту паузу вы и видите черный экран.
