### ISSUE TITLE
How get address (point or search)?

### ISSUE THREAD

**Issue by EvgenBES** [yandex/mapkit-android-demo#61]
Подскажите как можно или как нужно правильно делать, что бы я мог получить Адрес места в который кликнул по карте?

И вторая задача, как я могу получить координаты места по поиску: типа г. Москва, ул. Чебуречная 25 и в ответ получить Point с координатами.

**Comment by EvgenBES** [comment]
Неужели не кто никто не знает :(

**Comment by iFr0z** [comment]
Просто сделайте [HTTP geocoding](https://tech.yandex.com/maps/doc/geocoder/desc/concepts/input_params-docpage/) запрос (заранее предупреждаю, что для этого нужно взять отдельный ключик в кабинете разработчика) и распарсите JSON или сразу Retrofit используйте. Не забывайте также использовать асинхронный код, т.к. это запрос к сети и его нельзя осуществлять в основном потоке. А также проверка связи с интернетом. Ну и контролировать ситуацию, а то накликают. 

По второй задаче поможет пример, который, собственно, [тут](https://github.com/yandex/mapkit-android-demo/blob/master/src/main/java/com/yandex/mapkitdemo/SearchActivity.java) и находится.

```
@Override
    public void onSearchResponse(Response response) {
        MapObjectCollection mapObjects = mapView.getMap().getMapObjects();
        mapObjects.clear();
        for (GeoObjectCollection.Item searchResult : response.getCollection().getChildren()) {
            Point resultLocation = searchResult.getObj().getGeometry().get(0).getPoint();
            if (resultLocation != null) {
                mapObjects.addPlacemark(
                        resultLocation,
                        ImageProvider.fromResource(this, R.drawable.search_result));
            }
        }
    }
```

**Comment by iFr0z** [comment]
А что-то конкретное не получается? А то всевозможные способы вроде уже перечислили)

**Comment by EvgenBES** [comment]
Всем спасибо.
HTTP geocoding - помог решить данную проблему.
Хоть и пришлось сделать себе еще один ключ + реализацию запроса, но это не столько проблематично было)
