### ISSUE TITLE
UserLocationLayer перепрыгивает на местоположение пользователя

### ISSUE THREAD

**Issue by alinaSib** [yandex/mapkit-android-demo#63]
Мне нужно показать местоположение пользователя на карте и сделать в эту точку зум при открытии карты и при нажатии кнопки. Делаю userLocationLayer.setEnabled(true). Но, если потом переместитья в другое место на карте через пару секунд камера опять перескакивает на местоположение пользователя. Какой метод позволяет от этого избавиться? В документации не нашла. (

**Comment by EvgenBES** [comment]
Поделись кусочком кода как ты это реализовал!
У меня сейчас тоже такая задача ... и возможно поможешь мне поберечь пару часов моего времени.

Я думаю сделать это вызовом в 1 раз ...
То есть создам метом в onCreate , какой то типа initUserLocation();
в данном методе я сделаю данную реализацию и по итогу должно получиться что мы будем вызвать этот метод только при иницилизации активности.

**Comment by EvgenBES** [comment]
Сорри не сразу заметил что девушка)  - реализовал(а).
Пример из demo не передвигается на место расположения юзера когда смотрел его, возможно что-то забыл дописать или сделать, что бы он начал работать.

**Comment by alinaSib** [comment]
```
        //Show user location on map
        userLocationLayer = mapView.getMap().getUserLocationLayer();
        userLocationLayer.setEnabled(false);
        userLocationLayer.setHeadingEnabled(true);
        userLocationLayer.setObjectListener(this);

        moveCameraToPosition(userLocationLayer.cameraPosition().getTarget());

```
В onCreate  это все и делается. 

```
    public void moveCameraToPosition(@NonNull Point target) {
               mapView.getMap().move(
                        new CameraPosition(target, 15.0f, 0.0f, 0.0f),
                        new Animation(Animation.Type.SMOOTH, 2), null);
    }
```

**Comment by EvgenBES** [comment]
Нашёл проблему ... В настройках эмулятора (геолокации) не было разрешено моему приложение отслеживать моё место положение!
После предоставления этих возможностей всё получилось и определилось!

Вот нашёл проект в котором нету такой проблемы как описано у тебя:
https://github.com/MobileMirea/YandexMaps

у него нету такого метода moveCameraToPosition(.....)

за то он вызывает onObjectAdded(@NonNull UserLocationView userLocationView) .... и там всё это сделано ...
Пока писал данный коммит карта не сдвинулась не на дюйм... 
Так что советую попробовать его реализацию ;)

**Comment by alinaSib** [comment]
Я использовала moveCameraToPosition для зума в эту точку. Но даже если я его закомментирую - зума не будет, а прыгать будет. Складывается впечатление, что виновата com.google.android.gms:play-services-location:16.0.0 и ее сервисы. Буду еще искать в чем проблема. 
По поводу onObjectAdded - там просто иконки для метки, ничего более. 
Спасибо.

**Comment by ShtefanES** [comment]
Подойдет вариант определения местоположения с использованием com.yandex.mapkit.location.LocationListener и com.yandex.mapkit.location.LocationManager  или нужно использовать именно userLocationLayer?

**Comment by ShtefanES** [comment]
Вот пример рабочего кода(нет проверки разрешения для api>=23) для определения местоположения при старте и по клику fab:

    public class MainActivity extends AppCompatActivity {
  
    private static final String TAG = MainActivity.class.getSimpleName();
    private static final double DESIRED_ACCURACY = 0;
    private static final long MINIMAL_TIME = 0;
    private static final double MINIMAL_DISTANCE = 50;
    private static final boolean USE_IN_BACKGROUND = false;
    public static final int COMFORTABLE_ZOOM_LEVEL = 18;
    private final String MAPKIT_API_KEY = "your_api_key";
    private MapView mapView;
    private CoordinatorLayout rootCoordinatorLayout;
    private LocationManager locationManager;
    private LocationListener myLocationListener;
    private Point myLocation;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MapKitFactory.setApiKey(MAPKIT_API_KEY);
        MapKitFactory.initialize(this);
        setContentView(R.layout.activity_main);

        mapView = (MapView) findViewById(R.id.mapview);
        rootCoordinatorLayout = (CoordinatorLayout) findViewById(R.id.root_coordinator);

        locationManager = MapKitFactory.getInstance().createLocationManager();
        myLocationListener = new LocationListener() {
            @Override
            public void onLocationUpdated(Location location) {
                if (myLocation == null) {
                    moveCamera(location.getPosition(), COMFORTABLE_ZOOM_LEVEL);
                }
                myLocation = location.getPosition();
                Log.w(TAG, "my location - " + myLocation.getLatitude() + "," + myLocation.getLongitude());
            }

            @Override
            public void onLocationStatusUpdated(LocationStatus locationStatus) {
                if (locationStatus == LocationStatus.NOT_AVAILABLE) {
                    Snackbar.make(rootCoordinatorLayout, R.string.error_cant_get_my_location, Snackbar.LENGTH_LONG).show();
                }
            }
        };
    }

    @Override
    protected void onStart() {
        super.onStart();
        MapKitFactory.getInstance().onStart();
        mapView.onStart();

        subscribeToLocationUpdate();
    }

    @Override
    protected void onStop() {
        super.onStop();
        MapKitFactory.getInstance().onStop();
        locationManager.unsubscribe(myLocationListener);
        mapView.onStop();
    }

    public void onFabCurrentLocationClick(View view) {
        if (myLocation == null) {
            Snackbar.make(rootCoordinatorLayout, R.string.coordinates_are_not_yet_determinate, Snackbar.LENGTH_SHORT).show();
            return;
        }

        moveCamera(myLocation, COMFORTABLE_ZOOM_LEVEL);
    }

    private void subscribeToLocationUpdate() {
        if (locationManager != null && myLocationListener != null) {
            locationManager.subscribeForLocationUpdates(DESIRED_ACCURACY, MINIMAL_TIME, MINIMAL_DISTANCE, USE_IN_BACKGROUND, FilteringMode.OFF, myLocationListener);
        }
    }

    private void moveCamera(Point point, float zoom) {
        mapView.getMap().move(
                new CameraPosition(point, zoom, 0.0f, 0.0f),
                new Animation(Animation.Type.SMOOTH, 1),
                null);
    }
    }

**Comment by EvgenBES** [comment]
Я сделал так:

private void initUserLocation() {
        userLocationLayer = mapView.getMap().getUserLocationLayer();
        userLocationLayer.setEnabled(true);
        userLocationLayer.setHeadingEnabled(true);
        userLocationLayer.setObjectListener(this);
    }

то есть без метода moveCameraToPosition, и метод zoom убрал тоже ...
в onCreate 
mapView.getMap().move(new CameraPosition(new Point(0, 0), 12, 0, 0));

результат меня устроил.

**Comment by iFr0z** [comment]
https://github.com/iFr0z/FabUserLocation хоть и на kotlin, но не велика разница, т.к. методы используются те же.

**Comment by ShtefanES** [comment]
Пример iFr0z решает проблему, получается для того чтобы камера не перескакивала на текущее местоположение при перемещении по карте(как в демо), нужно в колбек onCameraPositionChanged добавить  userLocationLayer.resetAnchor().

**Comment by alinaSib** [comment]
А у меня не получается с resetAnchor(). Также прыгает (

**Comment by alinaSib** [comment]
Ну и видимо мы все-таки разные задачи с iFr0z решаем. Мне не надо следить за пользователем после нажатии кнопки. А надо только один раз показать где он - при нажатии на кнопку.   Поэтому мне помогло вообще не делать setAnchor()  и плюс boolean флаг showLocation.  
Что, кстати за Anchor mode, который этот метод включает не совсем понятно.

**Comment by ShtefanES** [comment]
Ваша активити или фрагмент должна реализовать интерфейс CameraListener.
 В колбеке:
@Override
    public void onCameraPositionChanged(@NonNull Map map, @NonNull CameraPosition cameraPosition, @NonNull CameraUpdateSource cameraUpdateSource, boolean b) {
        if (b) {
            userLocationLayer.resetAnchor();
        }
    }
Так же стоит назначить слушателя:
mapView.getMap().addCameraListener(this);

**Comment by alinaSib** [comment]
@ShtefanES  Было бы замечательно вообще понять что делает setAnchor() и resetAnchor().

**Comment by iFr0z** [comment]
@alinaSib По порядку:

> Было бы замечательно вообще понять что делает setAnchor() и resetAnchor().

`userLocationLayer` - это подключение слоя, который отобразит значок местоположения пользователя.
` setAnchor()` - это якорь, который следит за значком местоположения пользователя.
`resetAnchor()` - это для того, чтобы его снять, и не следить больше за значком местоположения пользователя.

> Складывается впечатление, что виновата com.google.android.gms:play-services-location:16.0.0 и ее сервисы.

Эти сервисы являются основой :)

> userLocationLayer.setObjectListener(this); // интерфейс UserLocationObjectListener

Добавляя данный слушатель, Вы имеете дело с такими методами, как `onObjectAdded, onObjectRemoved, onObjectUpdated`. Они действительно нужны для отображения значка местоположения пользователя и его состоянием, изменением.

**Comment by alinaSib** [comment]
@iFr0z Ну тогда все правильно. Мне действительно не нужен этот якорь. У меня нет цели следить за пользователем. 
Спасибо за подробный ответ!

**Comment by iFr0z** [comment]
@alinaSib Рад был помочь :)
