### ISSUE TITLE
Как убрать с объекта пин?

### ISSUE THREAD

**Issue by alinaSib** [yandex/mapkit-android-demo#65]
Если кто-то уже решал задачу как на карте отмечать объект пином и переводить на него камеру по тапу - поделитесь, пожалуйста. У меня получается это сделать, но не понятно как потом при тапе на другом объекте убрать пин с предыдущего.

**Comment by eberkovich** [comment]
Снять выделение с объекта можно двумя способами:
- явно позвать: 
```mapview.getMap().deselectGeoObject();```

- выделить другой объект:
```
@Override
    public boolean onObjectTap(GeoObjectTapEvent event) {
        final GeoObjectSelectionMetadata selectionMetadata = event.getGeoObject()
                .getMetadataContainer()
                .getItem(GeoObjectSelectionMetadata.class);

        if (selectionMetadata != null) {
            mapview.getMap().selectGeoObject(selectionMetadata.getId(), selectionMetadata.getLayerId());
            return true;
        }
        return false;
    }
```

**Comment by alinaSib** [comment]
Тогда еще вопрос как их туда правильно добавлять. Сейчас это делается так (пример взят из mapkit android demo с гитхаба):
```
mapObjectsLayer = mapView.getMap().getMapObjects().addCollection();
           Point point = getGeoPoint();
            PlacemarkMapObject mark = mapObjectsLayer.
                    addPlacemark
                            (point);

        CompositeIcon pinIcon = mark.useCompositeIcon();
        pinIcon.setIcon(
                "pin",
                ImageProvider.fromResource(this, R.drawable.pin),
                new IconStyle().setAnchor(new PointF(0.0f, 1.0f))
                        .setRotationType(RotationType.ROTATE)
                        .setZIndex(0f)
                        .setScale(0.4f));

        pinIcon.setIcon(
                "icon",
                ImageProvider.fromResource(this, R.drawable.point),
                new IconStyle().setAnchor(new PointF(0f, 0f))
                        .setRotationType(RotationType.ROTATE)
                        .setZIndex(0f)
                        .setScale(0.6f);
```
Таким образом у меня отображается объект на карте, отмеченный пином. 
И имеется tapListener:  
```
mapObjectsLayer.addTapListener(mapObjectTapListener);
    private MapObjectTapListener mapObjectTapListener = new MapObjectTapListener() {
        @Override
        public boolean onMapObjectTap(@NonNull MapObject mapObject, @NonNull Point point) {
            selectCurrentPoint();
            return false;
        }
    };
```
Если я делаю tapListener как в вашем примере, то на нажатие моих объектов на карте он не реагирует. Т.е. добавлены они на карту как-то не так... 
А тот  tapListener, который я использую (MapObjectTapListener) не возвращает GeoObject. 
Подскажите, можно ли как-то реализовать задачу select/deselect объектов, которые добавлены как у меня. Или мне надо переписать ту часть, где объекты добавляются на карту, чтобы это были GeoObject?

**Comment by eberkovich** [comment]
В мапките поддерживаются два типа точечных объектов: пользовательские - PlacemarkMapObject и точечные объекты в слоях карты. 
Добавлять можно только пользовательские объекты.

- Для обработки нажатий на пользовательские объекты можно использовать только MapObjectTapListener, который возвращает MapObject.

- Для обработки нажатий на объекты в слоях карты нужно использовать GeoObjectTapListener, который возвращает GeoObjectTapEvent из которого можно получить GeoObject.

Получить по пользовательскому объекту GeoObject нельзя, GeoObject - это описание объекта в слое карты.

**Comment by alinaSib** [comment]
Спасибо Вам большое за столь подробные ответы!
 С типами объектов разобрались. С тапом тоже. Осталось только понять можно
ли пользовательский объект выделить (пином, например). А тапом на другом
объекте этот пин снять? Ну или хотя бы удалить и снова добавить?

вт, 15 янв. 2019 г., 22:44 eberkovich notifications@github.com:

**Comment by Baktiyar2018** [comment]
можете подсказать примеры с метками и слушателями, так как в офф только описание

**Comment by eberkovich** [comment]
Создание меток: 
https://github.com/yandex/mapkit-android-demo/blob/e18f5104189fdcc3d3ad1b8f242ae3dcfa15c7d3/src/main/java/com/yandex/mapkitdemo/MapObjectsActivity.java#L81

Добавление слушателей:
`
private MapObjectTapListener mapObjectTapListener = new MapObjectTapListener() {
        @Override
        public boolean onMapObjectTap(MapObject mapObject, Point point) {
            //do something
            return true;
        }
};

mapObject.addTapListener(mapObjectTapListener);
`

Обратите внимание, что в данный момент слушатели сохраняются в мапкит по слабой ссылке, по этому их обязательно нужно сохранять на стороне приложения.

**Comment by Baktiyar2018** [comment]
Благодарю  , получилось сделать.👍👍👍


сб, 30 мар. 2019 г. в 14:59, eberkovich <notifications@github.com>:

**Comment by Baktiyar2018** [comment]
Здравствуйте! , @eberkovich  в данный момент по arraylist прогоняю и проставляю метки, слушатель работает на тап и открывает нужный активити, теперь необходимо передать обьект с данными (model) попробовал сравнивать point.latitude и  point.longitude в слушателе но при каждом табе  значение меняется(незнаю пока почему) .Какие есть варианты передать обьект с данными?

**Comment by eberkovich** [comment]
Здравствуйте @Baktiyar2018,

- Для того чтобы привязать пользовательский объект к placemark можно воспользоваться методом MapObject.setUserData().

- разные координаты при нажатии получается потому, что это координаты точки нажатия, а не точка привязки placemark. Точку привязки placemark можно узнать у MapObject который приходит в MapObjectTapListener, приведя его к нужному типу(в данном случае PlacemarkMapObject).

**Comment by Baktiyar2018** [comment]
Спасибо

пн, 1 апр. 2019 г. в 18:13, eberkovich <notifications@github.com>:
