### ISSUE TITLE
Добавление в проект mapkit

### ISSUE THREAD

**Issue by AsiAsiAsiA** [yandex/mapkit-android-demo#66]
В разделе начало работы:
https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/quickstart-docpage/

Указано, что в dependencies у build.gradle(Module:app) необходимо добавить - 
`compile 'com.yandex.android:mapkit:3.2'`

У меня студия ругалась и не принимала, в общем необходимо добавить вот такую строку:
`implementation 'com.yandex.android:mapkit:3.2.0'`

Поправьте либо меня, либо в туториале.

**Comment by IUdalov** [comment]
Спасибо за сообщение!
Поправим документацию ASAP.
