### ISSUE TITLE
unique id of GeoObject returned from search 

### ISSUE THREAD

**Issue by Xgamefactory** [yandex/mapkit-android-demo#67]
how to get  unique id of GeoObject returned from search
a unique id like placeId as provided from google maps.
did not found anything inside class properties.

**Comment by elricbk** [comment]
There is no such id at the moment. The next best thing is `uri` from `URIMetadata`. _Almost_ every object has it, so for most cases it will do. For rare objects without it you can construct some replacement like string with object name and it's position.

This is how [SearchResultItem.getId()](https://tech.yandex.ru/maps/doc/mapkit/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/search_layer/SearchResultItem-docpage/#method_detail__method_getId) is implemented internally.
