### ISSUE TITLE
И снова про размер APK

### ISSUE THREAD

**Issue by alinaSibiryakova** [yandex/mapkit-android-demo#69]
Библиотеки Yandex mapkit добавляют к APK 34 MB??? С этим можно что-то сделать? В аналогичном вопросе год назад было написано, что ведутся работы по уменьшению размера библиотек, ждите релиза.  Но судя по тому, что я сейчас вижу все только усугубилось?

**Comment by vbazhenov** [comment]
> С этим можно что-то сделать?

Есть два простых решения:
- Строить отдельные apk для каждой архитектуры
- Начиная с версии 3.1 мы разбили mapkit на части, которые можно подключать по отдельности. Теперь можно убрать directions, search, places и masstransit из build.gradle, если их функциональность не используется. Если получится убрать их все, размер должен уменьшиться раза в два.

Большую часть мапкита сейчас занимают нативные библиотеки, уменьшать их размер дальше довольно сложно, и мы пока не планируем этим заниматься.

**Comment by vbazhenov** [comment]
В качестве заключения: в версии 3.0 у нас было 2 архитектуры, сейчас их уже 4. Стройте отдельные apk для каждой — это может очень сильно уменьшить размер, добавляемый мапкитом.

**Comment by sicilla** [comment]
Подскажете, я столкнулся с этой же проблемой. 
`Теперь можно убрать directions, search, places и masstransit из build.gradle, если их функциональность не используется`

Как это сделать? Спасибо
