### ISSUE TITLE
Наслоение фрейма карты из предыдущего фрагмента

### ISSUE THREAD

**Issue by ilya842** [yandex/mapkit-android-demo#70]
Ситуация следующая. Есть 2 фрагмента, на 1 фрагменте имеется список объектов и карта, на которой они отображаются. При клике на элемент списка, я перехожу во 2 фрагмент, где отображается карта с выбранным объектом.

Переход на новый фрагмент осуществляется следующим образом:
```java
FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
transaction.add(R.id.container, newFragment);
transaction.addToBackStack(screenKey);
transaction.commit();
````

Когда я осуществляю переход на новый фрагмент через `transaction.add()`, то происходит наслоение предыдущей карты на новую. Карта на заднем фоне остается интерактивной, но поверх нее всегда висит статический фрейм, который никак не реагирует на нажатия.
![image](https://user-images.githubusercontent.com/19783537/52324061-1ce6e400-29f9-11e9-841c-3c61d7166707.png)

Если заменить `transaction.add()` на `transaction.replace()`, то все работает корректно. Я так понял это происходит из-за того, что при вызове `transaction.add()` не происходит уничтожение предыдущего фрагмента и кеш карты все еще присутствует в памяти (не вызывается метод `onStop()`). 

Как можно избавиться от данной проблемы не прибегая к замене одного фрагмента на другой?

**Comment by eberkovich** [comment]
По умолчанию MapView использует для отрисовки GLSurfaceView, к сожалению android не поддерживает корректную отрисовку одного GLSurfaceView поверх другого, что приводит к разного рода проблемам.
В качестве обходного варианта, можно попробовать одной из этих MapView выставить атрибут movable=true, тогда для отрисовки карты будет использоваться TextureView. Стоит иметь ввиду, что отрисовка через TextureView работает медленнее, чем через GLSurfaceView. Кроме того, каждая MapView занимает довольно много оперативной памяти, так что по возможности стоит минимизировать количество одновременно живущих MapView.

**Comment by ilya842** [comment]
> В качестве обходного варианта, можно попробовать одной из этих MapView выставить атрибут movable=true, тогда для отрисовки карты будет использоваться TextureView.

Спасибо большое за ответ. Да, такой способ помог избавиться от проблемы, но как Вы и говорили, карта стала работать заметно медленнее. Вероятнее всего придется прибегнуть к способу замены фрагмента, а не добавления.

**Comment by mkrustam96** [comment]
А есть ли иной способ решения данной проблемы? Не очень хочется жертвовать скоростью работы карты)

**Comment by eberkovich** [comment]
Думаю, что нет, это ведь ограничение android.
