### ISSUE TITLE
как правильно добавить TapListener на MapObject 

### ISSUE THREAD

**Issue by Goolpe** [yandex/mapkit-android-demo#72]
Здравствуйте. Добавил многоугольники
```
MapObjectCollection mapObjects = mapView.getMap().getMapObjects();
ArrayList<Point> polygonPoints = new ArrayList<>();

for(int i = 0; i < coords.size(); i++){
    double longitude = (double) (coords.get(i)).get(0);
    double latitude = (double) (coords.get(i)).get(1);
    polygonPoints.add(new Point(longitude, latitude));
}

PolygonMapObject polygon = mapObjects.addPolygon(
  new Polygon(new LinearRing(polygonPoints), new ArrayList<LinearRing>())
);
polygon.addTapListener(yandexMapObjectTapListener);

private class YandexMapObjectTapListener implements MapObjectTapListener {
    public boolean onMapObjectTap(MapObject mapObject, Point point) {
      System.out.println("something");
      return true;
    }
  }
```
Данные выводятся только при нажатии на границы многоугольников, как сделать так, чтобы вывод срабатывал при нажатии на любое место многоугольника?

**Comment by eberkovich** [comment]
Здравствуйте, 
Не удается воспроизвести проблему. 

Насколько я понимаю корректная работа System.out.println не гарантируется даже на эмуляторе.
Воспроизводится ли проблема, если пользоваться стандартным android.util.Log и если да, то
не могли бы Вы приложить полный код минимального примера?

**Comment by Goolpe** [comment]
Ошибка оказалась в том, что я сделал polygon.setFillColor(Color.TRANSPARENT), а strokeColor заполнял цветом, поэтому нажимались только границы, а не весь объект, когда я заполнил fillColor цветом, то tap на всей площади объекта срабатывал, не знаю баг это или так и должно быть

**Comment by eberkovich** [comment]
Да, так и должно быть.

**Comment by Goolpe** [comment]
А как поменять цвет при нажатии на объект?

**Comment by eberkovich** [comment]
setFillColor/setStrokeColor.

**Comment by Goolpe** [comment]
Я имею ввиду, как вызвать setFillColor в этой функции?

```
public boolean onMapObjectTap(MapObject mapObject, Point point) {
      return true;
}
```

**Comment by eberkovich** [comment]
`
public boolean onMapObjectTap(MapObject mapObject, Point point) {
      if (mapObject instanceof PolygonMapObject) {
         PolygonMapObject polygon = (PolygonMapObject)mapObject;
         polygon.setFillColor(...);
         return true;
      }
      return false;
}
`

**Comment by Goolpe** [comment]
Спасибо большое

**Comment by NomadicWarrior** [comment]
onMapObjectTap не вызывается Xcode 13.2.1 iPhone SE iOS 13.3.1. На симуляторе iOS 15.2 работает. 
YandexMapsMobile', '4.0.0-full'
