### ISSUE TITLE
Не отображаются здания на карте

### ISSUE THREAD

**Issue by DrTeel** [yandex/mapkit-android-demo#76]
Здравствуйте. Столкнулся с проблемой.
Есть Android-приложение, использующее mapkit версии 3.3.1.
На карте не отображаются здания. См. скриншот:

![](https://s8.hostingkartinok.com/uploads/images/2019/03/0b93654e8ba1a39d36e5ef13f721006c.png)

Хотелось бы, чтобы карта выглядела примерно так:
![](https://s8.hostingkartinok.com/uploads/images/2019/03/1bca25bbe68a21747e6ccfd809d1ff9d.png)

Код:

```
public class MainActivity extends AppCompatActivity {

    private MapView mapView;

    private final String YMAP_API_KEY = "ключ";
    private final Point CENTER = new Point(40.0, 50.0);
    private final float ZOOM = 14.0f;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        MapKitFactory.setApiKey(YMAP_API_KEY);
        MapKitFactory.initialize(this);

        setContentView(R.layout.activity_main);
        mapView = findViewById(R.id.mapview);

        mapView.getMap().move(new CameraPosition(CENTER, ZOOM, 0.0f, 0.0f));
    }
    @Override
    protected void onStop() {
        mapView.onStop();
        MapKitFactory.getInstance().onStop();
        super.onStop();
    }
    @Override
    protected void onStart() {
        super.onStart();
        MapKitFactory.getInstance().onStart();
        mapView.onStart();
    }
}
```

Что нужно сделать, чтобы на карте появились здания?

**Comment by eberkovich** [comment]
Видимо, по какой-то причине не скачиваются тайлы в результате показывается закешированный тайл с обзорного масштаба.
Скорее всего в логе есть какие-то ошибки.

**Comment by DrTeel** [comment]
В логе только следующие ошибки:
```
E/yandex.maps: decltype: Config does not have information for coverage indoor
E/yandex.maps: decltype: Config does not have information for layer vmap3
E/yandex.maps: decltype: Config does not have information for layer indoor
E/yandex.maps: decltype: Ratelimiter rejected access <ключ> to maps_mobile_offline_caches@free
```
Ошибка Ratelimiter rejected access часто повторяется.
Попробовал сегодня зайти через WiFi вместо 3G -  здания прогрузились как надо.
Подозреваю, что дело в нестабильности сигнала сотовой сети.
