### ISSUE TITLE
Получение информации о пробках

### ISSUE THREAD

**Issue by cdump** [yandex/mapkit-android-demo#77]
Создаю `trafficLayer = MapKitFactory.getInstance().createTrafficLayer(mapView!!.mapWindow)` и включаю/отключаю отображение на карте через `isTrafficVisible`.
Как мне получить текущее значение пробок в баллах?

Пробовал через `addTrafficListener`, который вызываю следующей строчкой после `createTrafficLayer` - результат плавающий, методы листера вызываются где-то 1 раз из 4..5 загрузок приложения, будто бы информация о пробках приходит раньше, чем я успеваю добавить листенер, а после его добавления текущая информация ему не сообщается (только обновления).
Когда "везет", то в `onTrafficChanged` все получаю.

Вот более полный код:
```
        trafficLayer = MapKitFactory.getInstance().createTrafficLayer(ymapView!!.mapWindow)
        trafficLayer!!.addTrafficListener(object : TrafficListener {
            override fun onTrafficExpired() { Log.e("trexp", "subj"); }
            override fun onTrafficLoading() { Log.e("trload", "subj"); }
            override fun onTrafficChanged(p0: TrafficLevel?) { Log.e("trchange", p0.toString()); }             
        })
```

**Comment by vbazhenov** [comment]
В приложении надо сохранять сильную ссылку на TrafficListener.
Мы хотим убрать этот неочевидный момент в будущем, но когда это будущее настанет – пока непонятно.

**Comment by cdump** [comment]
Спасибо, помогло.
