### ISSUE TITLE
Создание кластеров объектов

### ISSUE THREAD

**Issue by nikartm** [yandex/mapkit-android-demo#79]
Добрый день! Поддерживает ли версия YMK 3.3.1 кластеры объектов при зуме? Если да, то буду очень признателен за краткий гайд. В моей реализации поинты добавляются, используя mapObjects.addPlacemarks() и смотреть на карту с > 500 объектами, не очень комфортно.

**Comment by nikartm** [comment]
Хорошо, спасибо. Надеемся и верим)

**Comment by z17** [comment]
А когда следующий релиз и можно ли рассчитывать на появление такой фичи?
