### ISSUE TITLE
Failed to remove MapObject

### ISSUE THREAD

**Issue by abdlkdrisiktan** [yandex/mapkit-android-demo#81]
I try to remove PlaceMarkObject with 2 way 
the first one is :>yandexMap.getMap().getMapObjects().addCollection().remove(object) 
second :> yandexMap.getMap().getMapObjects().remove(object)
these methods are not working properly I don't know why here is the exception log : 
java.lang.RuntimeException: Failed to remove MapObject
at com.yandex.mapkit.map.internal.MapObjectCollectionBinding.remove(Native Method)

Yandex Version -- 3.3.1

Can you help me ? 
Any help would be appreciated

**Comment by vbazhenov** [comment]
This error message means that you are trying to remove placemark from wrong collection. You can try to use this snippet:
```java
object.getParent().remove(object);
```

**Comment by abdlkdrisiktan** [comment]
Thanks a lot  @vbazhenov  :+1:
