### ISSUE TITLE
Max and Min zoom level 

### ISSUE THREAD

**Issue by abdlkdrisiktan** [yandex/mapkit-android-demo#82]
How can I set max zoom and min zoom level to yandex map? I want to set a upper/lower bound for the camera zoom. I found the ZoomRange but I don't know how to use or how to set. 

Any help would be appreciated

**Comment by eberkovich** [comment]
It is not supported but you can add CameraListener and call map.move() within onCameraPositionChanged method.

**Comment by abdlkdrisiktan** [comment]
If I try to set max min zoom level to yandex map within every camera update it will be effect our application performance, in my opinion this approach not good solution. Is there any solution for solve this problem ? @eberkovich
