### ISSUE TITLE
Yandex maps display locations in russian

### ISSUE THREAD

**Issue by HolyOne** [yandex/mapkit-android-demo#83]
Yandex set default map language to russian so our map on android become russian.
I can see there is lang=xx_XX parameter when embedding yandex maps with javascript
But I see no solution on mapkit-android

Is there a solution to set language on mapkit-android?

**Comment by vbazhenov** [comment]
Yes, you can set language for mapkit using https://tech.yandex.com/maps/doc/mapkit/3.x/concepts/android/runtime/ref/com/yandex/runtime/i18n/I18nManagerFactory-docpage/#method_detail__method_setLocale___NonNullString___NonNullString___NonNullLocaleUpdateListener

**Comment by AlexRU18** [comment]
You can do it by:
`@Override
public void onStart() {
    super.onStart();
    mapView.onStart();
    MapKitFactory.getInstance().onStart();
    .....
    I18nManagerFactory.setLocale(Locale.getDefault().getLanguage(), new LocaleUpdateListener() {
        @Override
        public void onLocaleUpdated() {
            Log.d(TAG","onLocaleUpdated");
        }

        @Override
        public void onLocaleUpdateError(@NonNull Error error) {
            Log.d(TAG,"onLocaleUpdateError");
        }
    });
}`

**Comment by AlexRU18** [comment]
You can do it like this:
`@Override
public void onStart() {
    super.onStart();
    mapView.onStart();
    MapKitFactory.getInstance().onStart();
    .....
    I18nManagerFactory.setLocale(Locale.getDefault().getLanguage(), new LocaleUpdateListener() {
        @Override
        public void onLocaleUpdated() {
            Log.d(TAG","onLocaleUpdated");
        }

        @Override
        public void onLocaleUpdateError(@NonNull Error error) {
            Log.d(TAG,"onLocaleUpdateError");
        }
    });
}`
