### ISSUE TITLE
Too large size of apk file

### ISSUE THREAD

**Issue by oleg-indusrty** [yandex/mapkit-android-demo#84]
In the issue #16 was mentioned, that next release (sinse 4 Jun 2018) will contain reduced lib size as you worked to reduce the size for almost a year:
> We are currently reducing distribution size.
> Please, wait for the next release:)

How soon we could wait the release?

**Comment by anykey-skylocker** [comment]
MapKit contains native dependencies for x86 and x86_64 platforms. Both of them are about 10 Mb. 

![Снимок экрана 2019-05-08 в 12 29 49](https://user-images.githubusercontent.com/45760179/57365050-046b9e80-718d-11e9-8cf4-1aece690ee6e.png)

If you are targeting only `armv7` and `arm64` platforms, you could reduce your `.apk` size by 20 Mb. You can try to enable `abiFilter` to cut unneeded natives from `.apk` as follows:

``` groovy
android {
    //...
    defaultConfig {
        //...
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }
}
```
