### ISSUE TITLE
отслеживание события перемещения карты

### ISSUE THREAD

**Issue by molochkov** [yandex/mapkit-android-demo#85]
Добрый день! Возникла следующая проблема:
Необходимо отследить события перемещения карты. Когда пользователь пролистывает карту.
использую InertiaMoveListener
вот код :
mapViewY.getMap().addInertiaMoveListener(new InertiaMoveListener() {
            @Override
            public void onStart(@NonNull Map map, @NonNull CameraPosition cameraPosition) {
            Log.d(Data.TAG, "YAMAP onStart");   
            }

            @Override
            public void onCancel(@NonNull Map map, @NonNull CameraPosition cameraPosition) {
	    Log.d(Data.TAG, "YAMAP onCancel");   
              
            }

            @Override
            public void onFinish(@NonNull Map map, @NonNull CameraPosition cameraPosition) {
  	    Log.d(Data.TAG, "YAMAP onFinish");   

            }
        });

 не срабатывает ни одно событие. В чем может быть проблема?

**Comment by eberkovich** [comment]
Здравствуйте, для отслеживания перемещения карты нужно использовать CameraListener. Стоит также иметь ввиду, что мапкит сохраняет все листнеры по слабой ссылке, так что их нужно сохранять на стороне приложения. Что касается InertiaMoveListener, то он нужен для того, чтобы в момент распознавания кинетического жеста примерно предсказать финальную позицию.
