### ISSUE TITLE
Обратный геокодинг (com.yandex.mapkit.search.SearchManager#submit)

### ISSUE THREAD

**Issue by BenderRodirigues** [yandex/mapkit-android-demo#88]
Здравствуйте, 

пытаюсь получить адрес по указанным координатам
`searchManager.submit(
                point,
                18f,
                SearchOptions().apply {
                        searchTypes = SearchType.GEO.value
                 },
                searchPointListener
            )`

но в респонсе можно найти только адрес вида "улица Пушкина 56"  мне же нужен полный адрес, вида "улица Пушкина 56, Новосибирск, Новосибирская область, Россия"

Подскажите как это можно сделать с помощью MapKit

**Comment by elricbk** [comment]
У первого объекта в ответе нужно взять [адрес][1], из него можно получить строку нужного вам виде.

[1]: https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/ToponymObjectMetadata-docpage/#method_detail__method_getAddress
