### ISSUE TITLE
Issue with "Addplacemark" method

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#9]
I've implemented .mapObjects.addPlacemark(Point(43.233553, 76.956219), ImageProvider.fromResource(R.drawable.vector_resource)) with vector drawable, but on map is no any placemark. What should I do? Thank you

**Comment by nassa** [comment]
I think you can only use bitmap drawables for placemarks.

**Comment by eberkovich** [comment]
At this time mapkit does not support vector images.
