### ISSUE TITLE
How to add CameraPosition icon like Yandex.Taxi

### ISSUE THREAD

**Issue by ToleubekRauan** [yandex/mapkit-android-demo#95]
![image](https://user-images.githubusercontent.com/25398143/58857466-2c381e80-86c7-11e9-98fd-221ca14c8d74.png)

I need behavior like this. Thank you!
Необходимо добавить/создать маркер для cameraPosition. Спасибо!

**Comment by ToleubekRauan** [comment]
P.S. Sorry for that stupid question. You can just put any view in center, because MapView itself extends from Relative Layout.

**Comment by Sodiqjon-111** [comment]
> P.S. Sorry for that stupid question. You can just put any view in center, because MapView itself extends from Relative Layout.
It is not stupid question. You are right center view is enough but animation is problem and it is not simple for new developers, so you should  never belittle others.Not everyone is as smart as you
