### ISSUE TITLE
Suggestion text for search

### ISSUE THREAD

**Issue by CeH9** [yandex/mapkit-android-demo#98]
![image](https://user-images.githubusercontent.com/7687412/59763281-ede35780-92a1-11e9-88f4-7b52f3e8d3ba.png)
Как правильно обрабатывать экшен подсказки? Что за json в поле с текстом для поиска?
У предыдущих 7ми элементов все норм, обычный raw текст.

**Comment by elricbk** [comment]
Этот текст тоже можно передавать в `submit`, который ищет по тексту.
