### ISSUE TITLE
Non-structured data for the category

### ISSUE THREAD

**Issue by CeH9** [yandex/mapkit-android-demo#99]
> public synchronized List< String > getTags ()
> Additional non-structured data for the category.

Насколько данный формат стабильный? можно ли его парсить, в надежде что он не поменяется? Контекст: ответ из Searchmanager#submit

![image](https://user-images.githubusercontent.com/7687412/59888256-84616700-93cf-11e9-9515-e27a267bf8fd.png)

![image](https://user-images.githubusercontent.com/7687412/59888292-af4bbb00-93cf-11e9-81bd-f258dd3ad1e6.png)

**Comment by elricbk** [comment]
> можно ли его парсить, в надежде что он не поменяется? 
Ничего business critical лучше не закладывать на этот формат. В принципе, может поменяться в любой момент, никто заранее предупреждать не будет.
